### ISSUE TITLE
Very excited by this project but having installation issues

### ISSUE THREAD

**Issue by kycaver** [jamesiarmes/php-ews#103]
In poking around in the issues, I've made a few changes. Per comments in issue 11 I have recompiled cURL and when I run the test I get a 302 returned, which seems promising.  However, the script below still returns nothing. 

---

I'm very excited by this project and have lots of uses for it. I'm having trouble, though. I've verified my dependencies:

curl 7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3  
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

PHP 5.3.10-1ubuntu3.4 with Suhosin-Patch (cli) (built: Sep 12 2012 19:00:43) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

Have an Exchange 2010 server.

I have downloaded the files to my /var/www directory
git clone git@github.com:jamesiarmes/php-ews.git php-ews

I am using sample code from the wiki (https://github.com/jamesiarmes/php-ews/wiki/Email:-Send-Email) to do a simple send mail (modified to fit my server):

<?php
require_once('ExchangeWebServices.php');
require_once('NTLMSoapClient.php');
require_once('NTLMSoapClient/Exchange.php');
require_once('EWS_Exception.php');
require_once('EWSType.php');

require_once('EWSType/MessageType.php');
require_once('EWSType/EmailAddressType.php');
require_once('EWSType/BodyType.php');
require_once('EWSType/SingleRecipientType.php');
require_once('EWSType/CreateItemType.php');
require_once('EWSType/NonEmptyArrayOfAllItemsType.php');
require_once('EWSType/ItemType.php');

class EwsSendEmail
{
    protected function sendEmail()
    {
        $server = 'mail.domain.org';
        $username = 'user@doman.org';
        $password = 'mypassword;

```
    $ews = new ExchangeWebServices($server, $username, $password);

    $msg = new EWSType_MessageType();

    $toAddresses = array();
    $toAddresses[0] = new EWSType_EmailAddressType();
    $toAddresses[0]->EmailAddress = 'user@domain.org';
    $toAddresses[0]->Name = 'Recipient Name';

    // Multiple recipients
    //$toAddresses[1] = new EWSType_EmailAddressType();
    //$toAddresses[1]->EmailAddress = 'sara.smith@domain.com';
    //$toAddresses[1]->Name = 'Sara Smith';

    $msg->ToRecipients = $toAddresses;

    $fromAddress = new EWSType_EmailAddressType();
    $fromAddress->EmailAddress = 'user@domain.org';
    $fromAddress->Name = 'My Name';

    $msg->From = new EWSType_SingleRecipientType();
    $msg->From->Mailbox = $fromAddress;

    $msg->Subject = 'Test email message';

    $msg->Body = new EWSType_BodyType();
    $msg->Body->BodyType = 'HTML';
    $msg->Body->_ = '<p style="font-size: 18px; font-weight: bold;">Test email message from php ews library.</p>';

    $msgRequest = new EWSType_CreateItemType();
    $msgRequest->Items = new EWSType_NonEmptyArrayOfAllItemsType();
    $msgRequest->Items->Message = $msg;
    $msgRequest->MessageDisposition = 'SendAndSaveCopy';
    $msgRequest->MessageDispositionSpecified = true;

    $response = $ews->CreateItem($msgRequest);
    var_dump($response);
}

function __construct()
{
    $this->sendEmail();
}
```

}
$page = new EwsSendEmail();
?>

When I run this, I get a blank page in response and no email sent/received. 
If I echo("hello"); after the opening <?php tag, I get hello printed at the top of the page but still no email sent/received. I then add echo("hello"); just prior to the closing ?> tag. I go not get a second hello printed when I reload the page; just the first hello. Still no email.

So, I'm wondering if I have neglected to configure something properly in the many files that are installed. Or is there perhaps a permissions problem on a file/directory? I've changed nothing from the vanilla install.

I would sincerely appreciate any help that can be offered.

Many thanks,
Mark

**Comment by jamesiarmes** [comment]
This issue is over four years old. If you are still having trouble with the latest version from master, please open a new issue.
