### ISSUE TITLE
Available Calendar Properties?

### ISSUE THREAD

**Issue by oblogic7** [jamesiarmes/php-ews#104]
Does anybody know how to access the body or extended attributes property for appointment class?  EWS API says that it should be available, but I'm not seeing it in my results.  

Also, I need to know whether or not a meeting has been accepted by the delegate for the calendar, but don't see any property that provides this information.  I can see whether the event has been accepted on the calendar via Outlook, so I would think there should be a way to see the info via the API.  I'm on Exchange 2010.

Any help is appreciated.

**Comment by webermax** [comment]
You don't need a new connection. Just provide the existing one via function getMessageBody($ews, $thisMID){...}
