### ISSUE TITLE
Calendar Read List: error waiting too long "$response=$ews->FindItem($request);" Pls Help

### ISSUE THREAD

**Issue by oltres** [jamesiarmes/php-ews#109]
Hello,

I have the following trouble: trying to get the list of the calendar events with php-ews
(full script at:  https://github.com/jamesiarmes/php-ews/wiki/Calendar:-Get-List-%28Retrieving-Id-and-ChangeKey%29  )

I have an error at the function "FindItem":

$response = $ews->FindItem($request);

Because it takes a long (infinite) time to response.

If I try to create a new calendar event, the script has success. Even a new contact, script has success.
Only if it tries to read calendar or contacts it takes infinite time...

Could anyone help me?

Thank you very much and Regards,
Federico

---

<pre>
$host     = "10.20.30.40";
$username = "name.surname";
$password = "yyxxyyxx";
$version  = "Exchange2010";

$start = "2012-12-01";
$end   = "2012-12-31";

require_once('php-ews-master/EWSType.php');
require_once('php-ews-master/ExchangeWebServices.php');
require_once('php-ews-master/NTLMSoapClient.php');
require_once('php-ews-master/NTLMSoapClient/Exchange.php');
require_once('php-ews-master/EWS_Exception.php');
require_once('php-ews-master/EWSType/FindItemType.php');
require_once('php-ews-master/EWSType/ItemQueryTraversalType.php');
require_once('php-ews-master/EWSType/ItemResponseShapeType.php');
require_once('php-ews-master/EWSType/DefaultShapeNamesType.php');
require_once('php-ews-master/EWSType/CalendarViewType.php');
require_once('php-ews-master/EWSType/NonEmptyArrayOfBaseFolderIdsType.php');
require_once('php-ews-master/EWSType/DistinguishedFolderIdType.php');
require_once('php-ews-master/EWSType/DistinguishedFolderIdNameType.php');

$ews = new ExchangeWebServices($host, $username, $password, $version);

$request = new EWSType_FindItemType();
$request->Traversal = EWSType_ItemQueryTraversalType::SHALLOW;

$request->ItemShape = new EWSType_ItemResponseShapeType();
$request->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::DEFAULT_PROPERTIES;

$request->CalendarView = new EWSType_CalendarViewType();
$request->CalendarView->StartDate = date('c',strtotime($start)); 
$request->CalendarView->EndDate = date('c',strtotime($end)); 

$request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
$request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
$request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;

// Send request
$response = $ews->FindItem($request);

// Loop through each item if event(s) were found in the timeframe specified
if ($response->ResponseMessages->FindItemResponseMessage->RootFolder->TotalItemsInView > 0){
  $events = $response->ResponseMessages->FindItemResponseMessage->RootFolder->Items->CalendarItem;
  foreach ($events as $event){
    $id         = $event->ItemId->Id;
    $change_key = $event->ItemId->ChangeKey;
    $start      = $event->Start;
    $end        = $event->End;
    $subject    = $event->Subject;
    $location   = $event->Location;
    echo "- Found: ". $subject;
  }
} else {
  echo "No items returned";
}
</pre>

---

**Comment by keithslater** [comment]
Did you ever figure this out? I'm running into the exact same issue. 

It works perfect locally but on the production server, it just runs and never produces any output or anything. It gets stuck on FindItem. It must be some sort of server configuration problem but I'm not sure what. I run plenty of other php-ews functions like GetItem with no problem.

**Comment by keithslater** [comment]
For anyone else with this problem, there's some sort of bug in curl 

https://bugs.php.net/bug.php?id=71861

Curl - https://github.com/curl/curl/issues/741

There's some possible workarounds in there. I ended up changing this line - 

curl_setopt($this->ch, CURLOPT_HTTPAUTH, CURLAUTH_NTLM);

**Comment by jamesiarmes** [comment]
With the latest version in master, you can override most of the existing cURL options (including `CURLOPT_HTTPAUTH`) or supply your own by calling `setCurlOptions()` on the `Client`.
