### ISSUE TITLE
EWS Contact List limit?

### ISSUE THREAD

**Issue by Geekbell** [jamesiarmes/php-ews#111]
Everything is working great except for one small issue I'm running into. I'm using the example Contact:Get List in the wiki. This works if I am getting a list of a small number of contacts, say a through c. But, if I get the list of anything more than that here is the output I get:

```
stdClass Object
(
    [ResponseMessages] => stdClass Object
        (
            [FindItemResponseMessage] => stdClass Object
                (
                    [MessageText] => The server cannot service this request right now. Try again later.
                    [ResponseCode] => ErrorServerBusy
                    [DescriptiveLinkKey] => 0
                    [ResponseClass] => Error
                )
    )
)
```
Yes, there is a large amount of contacts in this exchange account.

**Comment by jamesiarmes** [comment]
This issue is almost four years old. If you are still having trouble with the latest version from master, please open a new issue.
