### ISSUE TITLE
Issue for  'SOAP client returned status of 401  add code for u programme

### ISSUE THREAD

**Issue by ychoucha** [jamesiarmes/php-ews#120]
Hello,

well for error 401 and i have the problem i can' t fix it, i have try to update my webserver with the last curl but not working :'(

but i found this code : 
<?php

$host = 'foo.ews-host.com';
$username = 'username'; // just need the name, no domain, nothing else
$password = 'password';
$ch = curl_init('https://'.$host.'/ews/services.wsdl'); 
curl_setopt($ch, CURLOPT_VERBOSE, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_NTLM);
curl_setopt($ch, CURLOPT_USERPWD, $username.':'.$password);
$response = curl_exec($ch);
$info = curl_getinfo( $ch );
$error =  curl_error ($ch);
print_r(array($response,$info,$error));

on this site -- > blog.ianty.com/ubuntu/exchange-web-services-ews-ntlmv2-and-linux/

maybe can u add this code working with old curl v0.22 on the do_request code ?

maybe can add a function who detect the curl version and u this code or the nwest ?

what do u thing please ?
thanks to u
Issa

**Comment by fullmetaljacket** [comment]
For me, the only way to fix it was to uncomment the following line in the NtlmSoapClient.php file:

curl_setopt($this->ch, CURLOPT_HTTPAUTH, CURLAUTH_NTLM);

After uncommenting that line, all my PHP Fatal error:  Uncaught exception 'PhpEws\\Exception\\EwsException' with message 'SOAP client returned status of 401' went away.

**Comment by jamesiarmes** [comment]
With the latest version in master, you can override most of the existing cURL options (including `CURLOPT_HTTPAUTH`) or supply your own by calling `setCurlOptions()` on the `Client`.

**Comment by fullmetaljacket** [comment]
I had this working before I upgraded to 1.0, so I doubt it's the server settings (see my previous post on this topic). The latest version changed the way I was passing those curl options, and I'm suspecting I have it wrong, although I've tried many iterations. Here's what I have:

`$start = '2016-08-22T11:30:00';
$end = '2016-08-22T12:30:00';
$start = new DateTime($start);
$end = new DateTime($end);
$timezone = 'Eastern Standard Time';
$curl_options = array('CURLOPT_HTTPAUTH' => 'CURLAUTH_NTLM'); // suspect format?
$version = Client::VERSION_2010;
$client = new Client($host, $username, $password, $version);
$client->setCurlOptions($curl_options);
$client->setTimezone($timezone);`

and this is the error it's throwing:

`[Sun Feb 12 20:55:46.526132 2017] [:error] [pid 27751] [client my.private.ip:60771] PHP Fatal error:  Uncaught exception 'Exception' with message 'SOAP client returned status of 401.' in /var/www/html/phpews/php-ews/src/Client.php:1650\nStack trace:\n#0 /var/www/html/phpews/php-ews/src/Client.php(1633): jamesiarmes\\PhpEws\\Client->processResponse(NULL)\n#1 /var/www/html/phpews/php-ews/src/Client.php(1126): jamesiarmes\\PhpEws\\Client->makeRequest('GetUserAvailabi...', Object(jamesiarmes\\PhpEws\\Request\\GetUserAvailabilityRequestType))\n#2 /var/www/html/av-schedule/availability_function3.php(74): jamesiarmes\\PhpEws\\Client->GetUserAvailability(Object(jamesiarmes\\PhpEws\\Request\\GetUserAvailabilityRequestType))\n#3 {main}\n  thrown in /var/www/html/phpews/php-ews/src/Client.php on line 1650`

Any help would be greatly appreciated.

**Comment by jamesiarmes** [comment]
`CURLOPT_HTTPAUTH` should be a constant, not a string.

**Comment by fullmetaljacket** [comment]
This seemed to do the job:

`$client -> setCurlOptions(array(CURLOPT_HTTPAUTH => true, CURLAUTH_NTLM => true));`

**Comment by jamesiarmes** [comment]
The `CURLOPT_HTTPAUTH` option takes an integer not a boolean value (see http://us1.php.net/manual/en/function.curl-setopt.php). I believe what's happening here is that `true` is getting casts to an integer which would result in `1` which corresponds to `CURLAUTH_BASIC`. If that is working for you, I would suggest using `CURLAUTH_BASIC` instead.
