### ISSUE TITLE
How To Close Each Connection

### ISSUE THREAD

**Issue by rcavezza** [jamesiarmes/php-ews#121]
Hi,

As far as I have seen in the code, each connection creates a persistent connection (not transient).  Is there a code snippet that will close each persistent connection?  Is this something I need to worry about?

**Comment by jamesiarmes** [comment]
If you want your connections to be closed after processing and not reused, you could use the `setCurlOptions` method on the `Client` to set the `CURLOPT_FORBID_REUSE` option to `true`. To my knowledge, you should not need to worry about this.
