### ISSUE TITLE
Not able to connect online exchange(PHP EWS)

### ISSUE THREAD

**Issue by harshendra123** [jamesiarmes/php-ews#122]
Hi,

I have created Microsoft exchange online trial account. But not able to connect using PHP EWS. Can i get some suggestion to proceed here.  

What should be the host URL to connect exchange online. Used below details.

$host = 'vinniehash.onmicrosoft.com';
$username = 'vinnie_hash@vinniehash.onmicrosoft.com';

Getting below error:

Fatal error: Uncaught exception 'EWS_Exception' with message 'Curl error: Couldn't resolve host 'vinniehash.onmicrosoft.com'' in /services/webpages/util/1/r/1ry5hwgrq.site.aplus.net/dealsdrizzle.com/public/ews/NTLMSoapClient.php:88 Stack trace: #0 [internal function]: NTLMSoapClient->__doRequest('<?xml version="...', 'https://vinnieh...', 'http://schemas....', 1, 0) #1 /services/webpages/util/1/r/1ry5hwgrq.site.aplus.net/dealsdrizzle.com/public/ews/ExchangeWebServices.php(391): SoapClient->__call('FindItem', Array) #2 /services/webpages/util/1/r/1ry5hwgrq.site.aplus.net/dealsdrizzle.com/public/ews/ExchangeWebServices.php(391): NTLMSoapClient_Exchange->FindItem(Object(EWSType_FindItemType))

Regards,
Harsha

**Comment by Levan777** [comment]
I have the same exact problem :(
