### ISSUE TITLE
way to retrieve list of calendar events with description?

### ISSUE THREAD

**Issue by Zxurian** [jamesiarmes/php-ews#124]
Reading through the docs, and googling a bit, I can only find methods to retrieve a list of calendar events with a given date range that provide everything but description, and a separate method (and separate call to go with it) to retrieve the description of a single event.

assuming that a calendar has 20 events within a month, and i'd like to get all 20 events with descriptions, is there a way to do this with a single request, instead of 1 request for the list, and then 20 subsequent separate requests with each event id?

**Comment by Dragnucs** [comment]
@Zxurian Can you please explain how you could get the description?

**Comment by jamesiarmes** [comment]
The `FindItem` response does not include the body for any items, you will need to use a separate `Getitem` operation for this. However, you can group multiple items together into a single `GetItem` request. See contact/describe example in the code to get an idea of how to do that.
