### ISSUE TITLE
Issue for: Uncaught SoapFault exception: [a:ErrorInternalServerError] An internal server error occurred. The operation failed.

### ISSUE THREAD

**Issue by cvachta** [jamesiarmes/php-ews#125]
I can not send mail,  I still getting this error:
PHP Fatal error:  Uncaught SoapFault exception: [a:ErrorInternalServerError] An internal server error occurred. The operation failed. in /var/www/php-ews/ExchangeWebServices.php:293
Stack trace:
#0 /var/www/php-ews/ExchangeWebServices.php(293): SoapClient->__call('CreateItem', Array)
#1 /var/www/php-ews/ExchangeWebServices.php(293): NTLMSoapClient_Exchange->CreateItem(Object(EWSType_CreateItemType))
#2 /var/www/send.php(60): ExchangeWebServices->CreateItem(Object(EWSType_CreateItemType))
#3 /var/www/send.php(66): EwsSendEmail->sendEmail()
#4 /var/www/send.php(69): EwsSendEmail->__construct()
#5 {main}

  thrown in /var/www/php-ews/ExchangeWebServices.php on line 293

My php code is same as here:  https://github.com/jamesiarmes/php-ews/wiki/Email:-Send-Email, of course I use my  credentials.

My curl is curl 7.21.0 (i486-pc-linux-gnu) libcurl/7.21.0 OpenSSL/0.9.8o zlib/1.2.3.4 libidn/1.15 libssh2/1.2.6
Protocols: dict file ftp ftps http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

curl https://mail.domain.cz/EWS/Exchange.asmx -w %{http_code} --ntlm -u myname:mypassword -k 

show this:
&lt;html&gt;&lt;head&gt;&lt;title&gt;Object moved&lt;/title&gt;&lt;/head&gt;&lt;body&gt;
&lt;h2&gt;Object moved to &lt;a href=&quot;%2fEWS%2fServices.wsdl&quot;&gt;here&lt;/a&gt;.&lt;/h2&gt;
&lt;/body&gt;&lt;/html&gt;
302

If I put https://mail.domain.cz/EWS/Exchange.asmx to my browser, after login I see wsdl definitions... 
I think it is good... but why SOAP client fail?

Please help :) thank you in advance. David

**Comment by jamesiarmes** [comment]
This issue is over three years old. If you are still having trouble with the latest version from master, please open a new issue.
