### ISSUE TITLE
Getting User Out of Office Settings

### ISSUE THREAD

**Issue by battlecow** [jamesiarmes/php-ews#133]
Allow me to preface this issue with the fact that I am not having any trouble retrieving user availability utilizing the example provided from the Wiki. The environment is currently an apache webserver running curl 7.28.1.
I am having some trouble using the `EWSType_GetUserOofSettingsRequest` the request appears to work properly, however all I am able to get back is:

stdClass Object
(
    [ResponseMessage] => stdClass Object
        (
            [MessageText] => Connection did not succeed. Try again later.
            [ResponseCode] => ErrorConnectionFailed
            [DescriptiveLinkKey] => 0
            [ResponseClass] => Error
        )
)

There are no errors on the console and I know that the user currently has an OOF response setup.  Is there anyway to debug this issue further?

**Comment by jamesiarmes** [comment]
This issue is over three years old. If you are still having trouble with the latest version from master, please open a new issue.
