### ISSUE TITLE
Contacts/Calendar: Get list --> Attribute "Basepoint" is missing in PHP 5.2.6

### ISSUE THREAD

**Issue by rw268** [jamesiarmes/php-ews#135]
I'm bringing up issue https://github.com/jamesiarmes/php-ews/issues/13 again:

If I use the Wiki examples "Contact: Get list" or "Calendar: Get list" on my development server (PHP 5.2.17 on Windows), everything works fine.

When using exactly the same scripts on my live server (Debian PHP 5.2.6), I get this error:

<blockquote>Fatal error: Uncaught SoapFault exception: [a:ErrorSchemaValidation] The request failed schema validation: The required attribute 'BasePoint' is missing. in /mypath/ExchangeWebServices.php:391
Stack trace:
#0 [internal function]: SoapClient-&gt;__call('FindItem', Array)
#1 /mypath/ExchangeWebServices.php(391): NTLMSoapClient_Exchange-&gt;FindItem(Object(EWSType_FindItemType))
#2 /mypath/_contacts_get_list.php(43): ExchangeWebServices-&gt;FindItem(Object(EWSType_FindItemType))
#3 {main}
  thrown in <b>/mypath/ExchangeWebServices.php</b> on line <b>391</blockquote>

After some research I came to the conclusion, that maybe PHP's SOAP extension is the problem.
--> So I installed PHP 5.2.6 on my Windows development machine, and I got exactly the same error as on the live server.

jamesiarmes mentioned in https://github.com/jamesiarmes/php-ews/issues/13 the problem would not be reproduceable, but from my point of view it is when using the "right" PHP version.

My questions:
- If I must stay with the PHP 5.2.6 system and want to get it running:
  Is there any way to "bypass" <code>$request->CalendarView = new EWSType_CalendarViewType()</code> etc. to get lists of contacts or calendar items?
- Can I edit "types.xsd" and add the "basepoint" attribute in
  <pre>&lt;xs:complexType name="CalendarViewType"&gt;
  &lt;xs:complexContent&gt;
    &lt;xs:extension base="t:BasePagingType"&gt;
      &lt;xs:attribute name="StartDate" type="xs:dateTime" use="required" /&gt;
      &lt;xs:attribute name="EndDate" type="xs:dateTime" use="required" /&gt;
    &lt;/xs:extension&gt;
  &lt;/xs:complexContent&gt;
  &lt;/xs:complexType&gt;</pre>?

I tried this, but it had no influence.

Thanks in advance for your comments!

**Comment by jamesiarmes** [comment]
This issue is over three years old and PHP 5.2 is not supported. If you are having trouble with the latest version in master, please open a new issue.
