### ISSUE TITLE
Opening another account as admin (switching accounts)

### ISSUE THREAD

**Issue by martincollar** [jamesiarmes/php-ews#138]
Hi,

I've one question... I've a system synchronized witch MS Exchange but I don't want store passwords in our system for every user. I want store only one admin user password with exact rights (read/write contacts/task...).
If I login as this admin to owa interface, I can switch between users, it's possible do it with PHP-EWS? And if so, how to do it? Thanks.

Sorry if it's not issue...

![owa_switching_users](https://f.cloud.github.com/assets/3909724/547127/b4968dfe-c2b8-11e2-9808-21195f213065.png)

**Comment by jamesiarmes** [comment]
It seems the original issue here has been resolved. If you are continuing to have trouble using the latest version from master, please open a new issue.
