### ISSUE TITLE
Create CalendarItem with multiple Attendee issue

### ISSUE THREAD

**Issue by nawrasgh** [jamesiarmes/php-ews#139]
Hi,
How could I add multiple attendee to CalendarItem.
I did search in EWS PHp library but did not find any array of attendee:( to use it

The code for one Attendee is:

$request->Items->CalendarItem->RequiredAttendees = new EWSType_NonEmptyArrayOfAllItemsType();
$request->Items->CalendarItem->RequiredAttendees->Attendee = new  EWSType_SingleRecipientType();
$request->Items->CalendarItem->RequiredAttendees->Attendee->Mailbox = new EWSType_EmailAddressType();
$request->Items->CalendarItem->RequiredAttendees->Attendee->Mailbox->EmailAddress = 'test@xxx.com';
$response = $ews->CreateItem($request);

Any thoughts?

Thanks

**Comment by erickengelke** [comment]
I have been working on this for hours, I can create events for myself, and I'm fully privileged on $foruser, but the following code doesn't work for me:

    // Set meeting attendee
    $request->Items->CalendarItem->RequiredAttendees = new 
        EWSType_NonEmptyArrayOfAttendeesType();
    $request->Items->CalendarItem->RequiredAttendees->Attendee[0] = new 
       EWSType_AttendeeType();
$request->Items->CalendarItem->RequiredAttendees->Attendee[0]->Mailbox = 
    new EWSType_EmailAddressType();
$request->Items->CalendarItem->RequiredAttendees->Attendee[0]->Mailbox->EmailAddress 
   = $foruser;
$request->Items->CalendarItem->RequiredAttendees->Attendee[0]->Mailbox->RoutingType ='SMTP';
$request->Items->CalendarItem->RequiredAttendees->Attendee[0]->Name = $foruser;

I don't get any errors, but it just hangs on the call to the Server.

**Comment by jamesiarmes** [comment]
It seems the original issue here has been resolved. If you are continuing to have trouble using the latest code from master, please open a new issue.
