### ISSUE TITLE
SOAP-ERROR: Encoding: object hasn't 'Path' property

### ISSUE THREAD

**Issue by struppinet** [jamesiarmes/php-ews#140]
I am sucessfully connected to our Exchange 2010 SP1 Server. I can get a list of all calendar items but when i want to update the Location or the Subject i get this error:

Fatal error: Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: object hasn't 'Path' property in ./ExchangeWebServices.php:687 Stack trace: #0 [internal function]: SoapClient->__call('UpdateItem', Array) #1 ./ExchangeWebServices.php(687): NTLMSoapClient_Exchange->UpdateItem(Object(stdClass)) #2 ./exchange/write.php(38): ExchangeWebServices->UpdateItem(Object(stdClass)) #3 {main} thrown in ./ExchangeWebServices.php on line 687

I found a Bug Report on the php site without any result. Most isses found by google are very old so i can't understand why this is happening because it should already be fixed. I am using the code of the Calendar Update example.

``` php
$ews = new ExchangeWebServices($host, $username, $password, $version);

$request = new EWSType_UpdateItemType();
$request->ConflictResolution = 'AlwaysOverwrite';
$request->SendMeetingInvitationsOrCancellations = 'SendOnlyToAll';
$request->ItemChanges = array();

$change = new EWSType_ItemChangeType();
$change->ItemId = new EWSType_ItemIdType();
$change->ItemId->Id = $event_id;
$change->ItemId->ChangeKey = $event_change_key;

$field = new EWSType_SetItemFieldType();
$field->FieldURI = new EWSType_PathToUnindexedFieldType();
$field->FieldURI->FieldURI = 'calendar:Location';
$field->CalendarItem = new EWSType_CalendarItemType();
$field->CalendarItem->Location = 'Home';
$change->Updates->SetItemField[] = $field;

$request->ItemChanges[] = $change;

$response = $ews->UpdateItem($request);
```

**Comment by jamesiarmes** [comment]
This was resolved long ago.
