### ISSUE TITLE
example : Folder:-Get-Details don't work

### ISSUE THREAD

**Issue by alexandrems** [jamesiarmes/php-ews#141]
Hi,

I try to access to Exchange's public folder, for check mail. 
when I try this https://github.com/jamesiarmes/php-ews/wiki/Email:-Get-List all are ok.

But when I try this https://github.com/jamesiarmes/php-ews/wiki/Email:-Get-List 
I have got an error : "<b>Fatal error</b>:  Uncaught SoapFault exception: [soap11:Client] Ã‰chec de la validation de schÃ©ma pour la demande :L'attribut 'Id' n'est pas valide - La valeur 'publicfoldersroot' n'est pas valide selon son type de donnÃ©es 'http://schemas.microsoft.com/exchange/services/2006/types:DistinguishedFolderIdNameType' - Ã‰chec de la contrainte Enumeration. ..."
Why example don't work?

Thanks a lot,

**Comment by jamesiarmes** [comment]
This issue is over three years old. If you're still having trouble with the latest code from master, please open a new issue.
