### ISSUE TITLE
Creating a navigation shortcut pointing on a calendar

### ISSUE THREAD

**Issue by Cyraan** [jamesiarmes/php-ews#144]
Hi

We are trying to make a PHP script and Exchange 2013 that will create a calendar in a user's mailbox and we try to create a navigation shortcut pointing on that calendar in another user's mailbox. We want to skip the email asking to share a calendar since we want to make our script 100% automatic.

We asked on the exchange forum to get some informations if it could be done and we got this answer : http://social.msdn.microsoft.com/Forums/exchange/en-US/eb49d42d-f961-42f6-8732-4bc3d0987b18/sharing-a-calendar-using-ews-and-phpews-without-sending-share-invitation

So with this in mind, we tried to use the function CreateItem and add the extended properties we got in the documentation. When we run the script, we aren't getting a navigation shortcut but a draft message.

Here is the code we use:

$a_sExtendedProperties = array();

//PidTagMessageClass 
$sType = new EWSType_PathToExtendedFieldType();
$sType->PropertyTag = "0x001A";
$sType->PropertyType = EWSType_MapiPropertyTypeType::STRING;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = "IPM.Microsoft.WunderBar.Link";
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagNormalizedSubject  
$sType = new EWSType_PathToExtendedFieldType();
$sType->PropertyTag = "0x0E1D";
$sType->PropertyType = EWSType_MapiPropertyTypeType::STRING;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = "Meetings";
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkSaveStamp  
//$sType = new EWSType_PathToExtendedFieldType();
//$sType->PropertyTag = "0x0E1D";
//$sType->PropertyType = EWSType_MapiPropertyTypeType::STRING;
//
//$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
//$objExtendedPropertyType->ExtendedFieldURI = $sType;
//$objExtendedPropertyType->Value = "Meetings";
//$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkType
$sType = new EWSType_PathToExtendedFieldType();
$sType->PropertyTag = "0x6849";
$sType->PropertyType = EWSType_MapiPropertyTypeType::INTEGER;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = 2;
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkFlags
$sType = new EWSType_PathToExtendedFieldType();
$sType->PropertyTag = "0x684A";
$sType->PropertyType = EWSType_MapiPropertyTypeType::INTEGER;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = 1024;
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkOrdinal 
//$sType = new EWSType_PathToExtendedFieldType();
//$sType->PropertyTag = "0x684B";
//$sType->PropertyType = EWSType_MapiPropertyTypeType::BINARY;
//
//$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
//$objExtendedPropertyType->ExtendedFieldURI = $sType;
//$objExtendedPropertyType->Value = 1024;
//$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkEntryId 
$sType = new EWSType_PathToExtendedFieldType();
//$sType->PropertyTag = "0x0FFF";
$sType->PropertyTag = "0x684C";
$sType->PropertyType = EWSType_MapiPropertyTypeType::BINARY;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = $sEntryID;
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkRecordKey  
$sType = new EWSType_PathToExtendedFieldType();
//$sType->PropertyTag = "0x0FF9";
$sType->PropertyTag = "0x684D";
$sType->PropertyType = EWSType_MapiPropertyTypeType::BINARY;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = $sRecordID;
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkStoreEntryId  
$sType = new EWSType_PathToExtendedFieldType();
//$sType->PropertyTag = "0x0FFB";
$sType->PropertyTag = "0x684E";
$sType->PropertyType = EWSType_MapiPropertyTypeType::BINARY;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = $sStoreID;
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkFolderType
$sType = new EWSType_PathToExtendedFieldType();
$sType->PropertyTag = "0x684F";
$sType->PropertyType = EWSType_MapiPropertyTypeType::CLSID;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
//$objExtendedPropertyType->Value = '{0x02780600, 0x0000, 0x0000, {0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46}}';
$objExtendedPropertyType->Value = '0006F063-0000-0000-C000-000000000046';
$a_sExtendedProperties[] = $objExtendedPropertyType;

//PidTagWlinkSection
$sType = new EWSType_PathToExtendedFieldType();
$sType->PropertyTag = "0x6852";
$sType->PropertyType = EWSType_MapiPropertyTypeType::INTEGER;

$objExtendedPropertyType = new EWSType_ExtendedPropertyType();
$objExtendedPropertyType->ExtendedFieldURI = $sType;
$objExtendedPropertyType->Value = '3';
$a_sExtendedProperties[] = $objExtendedPropertyType;

$request = new EWSType_CreateItemType();
$request->Items = new EWSType_CreateItemType();
$request->Items->Item = new EWSType_ItemType();
//$request->Items->Item->ItemClass = "IPM.Microsoft.WunderBar.Link";
//$request->Items->Item->Subject = "SharedCalendar";
$request->Items->Item->ExtendedProperty = $a_sExtendedProperties;

$request->ParentFolderId = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
$request->ParentFolderId->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
$request->ParentFolderId->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;
$request->ParentFolderId->DistinguishedFolderId->Mailbox = new EWSType_MailboxData();
$request->ParentFolderId->DistinguishedFolderId->Mailbox->EmailAddress = 'user@domain.ca';
$request->ParentFolderId->DistinguishedFolderId->Mailbox->RoutingType  = 'SMTP';

$response = $ews->CreateItem($request);

We get the values $sEntryID, $sRecordID and $sStoreID using the function FindItem and adding the extended property 

$sCalendarExchangeID = $response->ResponseMessages->CreateFolderResponseMessage->Folders->Folder->FolderId->Id;
$sCalendarExchangeChangeKey = $response->ResponseMessages->CreateFolderResponseMessage->Folders->Folder->FolderId->ChangeKey;

$request = new EWSType_FindFolderType();
$request->FolderShape = new EWSType_FolderResponseShapeType();
$request->FolderShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;

$request->IndexedPageFolderView = new EWSType_IndexedPageViewType();
$request->IndexedPageFolderView->BasePoint = 'Beginning';
$request->IndexedPageFolderView->Offset = 0;

$a_ExtendedProperties = array();

//PidTagWlinkEntryId 
$status = new EWSType_PathToExtendedFieldType();
$status->PropertyTag = "0x0FFF";
$status->PropertyType = EWSType_MapiPropertyTypeType::BINARY;

$a_ExtendedProperties[] = $status;

//PidTagWlinkRecordKey 
$status = new EWSType_PathToExtendedFieldType();
$status->PropertyTag = "0x0FF9";
$status->PropertyType = EWSType_MapiPropertyTypeType::BINARY;

$a_ExtendedProperties[] = $status;

//PidTagWlinkStoreEntryId 
$status = new EWSType_PathToExtendedFieldType();
$status->PropertyTag = "0x0FFB";
$status->PropertyType = EWSType_MapiPropertyTypeType::BINARY;

$a_ExtendedProperties[] = $status;

//PidTagWlinkStoreEntryId 
$status = new EWSType_PathToExtendedFieldType();
$status->PropertyTag = "0x3001";
$status->PropertyType = EWSType_MapiPropertyTypeType::STRING;

$a_ExtendedProperties[] = $status;

$request->FolderShape->AdditionalProperties = new EWSType_NonEmptyArrayOfPathsToElementType();
$request->FolderShape->AdditionalProperties->ExtendedFieldURI = $a_ExtendedProperties;

$request->Traversal = 'Shallow';

$request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
$request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
$request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;

$response = $ews->FindFolder($request);

$sEntryID = '';
$sRecordID = '';
$sStoreID = '';

if (!is_array($response->ResponseMessages->FindFolderResponseMessage->RootFolder->Folders->CalendarFolder)) {
    if ($response->ResponseMessages->FindFolderResponseMessage->RootFolder->Folders->CalendarFolder->FolderId->Id == $sCalendarExchangeID && $response->ResponseMessages->FindFolderResponseMessage->RootFolder->Folders->CalendarFolder->FolderId->ChangeKey == $sCalendarExchangeChangeKey) {
        foreach ($CalendarFolder->ExtendedProperty as $ExtendedProperty) {
            switch ($ExtendedProperty->ExtendedFieldURI->PropertyTag) {
                case '0xfff':
                    $sEntryID = $ExtendedProperty->Value;
                    break;

```
            case '0xff9':
                $sRecordID = $ExtendedProperty->Value;
                break;

            case '0xffb':
                $sStoreID = $ExtendedProperty->Value;
                break;  
        }
    }               
}
```

}
else {
    foreach ($response->ResponseMessages->FindFolderResponseMessage->RootFolder->Folders->CalendarFolder as $CalendarFolder) {
        if ($CalendarFolder->FolderId->Id == $sCalendarExchangeID && $CalendarFolder->FolderId->ChangeKey == $sCalendarExchangeChangeKey) {
            foreach ($CalendarFolder->ExtendedProperty as $ExtendedProperty) {
                switch ($ExtendedProperty->ExtendedFieldURI->PropertyTag) {
                    case '0xfff':
                        $sEntryID = $ExtendedProperty->Value;
                        break;

```
                case '0xff9':
                    $sRecordID = $ExtendedProperty->Value;
                    break;

                case '0xffb':
                    $sStoreID = $ExtendedProperty->Value;
                    break;  
            }
        }   
    }
}
```

}

So for the moment we are stuck there, we don't know if the CreateItem function allow us to create this object or if it's the values we set are correct or not.

We have been looking for documentations around the web but it seems like nobody ever did that before us. If any of you could help us it would be greatly appreciated.

Thanks and have a nice day.

**Comment by jamesiarmes** [comment]
This issue is over three years old. If you are still having trouble with the latest version from master, please open a new issue.
