### ISSUE TITLE
401 Not Authorised responses  CURLAUTH_BASIC / CURLAUTH_NTLM

### ISSUE THREAD

**Issue by Meh-Lindi** [jamesiarmes/php-ews#151]
Talking to an Exchange 2007 server, it would alwys return 401 not authorised, until I removed / changed the 
CURL_HTTPAUTH, CURLAUTH_BASIC | CURLAUTH_NTLM
to
CURL_HTTPAUTH, CURLAUTH_NTLM

at NTLMSoapClient ~ line 78.

perhaps a method to select the auth type for the class?

**Comment by colinodell** [comment]
I have this same issue with curl 7.22.0, but not with 7.35.0

Also see #67

**Comment by jamesiarmes** [comment]
With the latest version in master, you can override most of the existing cURL options (including `CURLOPT_HTTPAUTH`) or supply your own by calling `setCurlOptions()` on the `Client`.
