### ISSUE TITLE
401 Error cURL 7.27

### ISSUE THREAD

**Issue by VincentdeWit** [jamesiarmes/php-ews#152]
Hi everyone,

Despite all the other issues and links with information and solutions, i still cannot manage to get PHP-EWS working under Ubuntu.

My Ubuntu machine is running 12.04 (64Bit) with curl version 7.27.
Here is my curl -V output:
curl 7.27.0 (x86_64-unknown-linux-gnu) libcurl/7.27.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3

This is the output from the command line with curl -v.
- About to connect() to db3prd0710.outlook.com port 443 (#0)
-   Trying 157.56.253.86...
- connected
- Connected to db3prd0710.outlook.com (157.56.253.86) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: none
  CApath: /etc/ssl/certs
- SSLv3, TLS handshake, Client hello (1):
- SSLv3, TLS handshake, Server hello (2):
- SSLv3, TLS handshake, CERT (11):
- SSLv3, TLS handshake, Server finished (14):
- SSLv3, TLS handshake, Client key exchange (16):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSL connection using RC4-MD5
- Server certificate:
-    subject: C=US; ST=washington; L=Redmond; O=Microsoft Corp; OU=MOD; CN=Outlook.com
-    start date: 2013-04
-    expire date: 2014-04
-    subjectAltName: db3prd0710.outlook.com matched
-    issuer: C=US; O
-    SSL certificate verify ok.
- Server auth using NTLM with user 'hereismymail@mail.com'
  > GET /EWS/Exchange.asmx HTTP/1.1
  > Authorization: NTLM TlRMTVNTUAABAAAABoIIAAAAAAAAAAAAAAAAAAAAAAA=
  > User-Agent: curl/7.27.0
  > Host: db3prd0710.outlook.com
  > Accept: _/_
  > 
- additional stuff not fine transfer.c:1037: 0 0
- HTTP 1.1 or later with persistent connection, pipelining supported
  < HTTP/1.1 401 Unauthorized
  < Server: Microsoft-IIS/7.5
  < RequestId: 1d2b5665-b826-4233-9ced-ee23810473e6
  < Set-Cookie: exchangecookie=8ac7d4510a62418186419139042e23e0; expires=Sat, 16-Aug-2014 09:41:21 GMT; path=/; HttpOnly
  < X-Powered-By: ASP.NET
  < X-DiagInfo: DB3PRD0710CA007
  < WWW-Authenticate: Basic Realm=""
  < Date: Fri, 16 Aug 2013 09:41:20 GMT
  < Content-Length: 0
  < 
- Connection #0 to host db3prd0710.outlook.com left intact
  401\* Closing connection #0
- SSLv3, TLS alert, Client hello (1):

Is this a problem with PHP-EWS or with my server?

Thanks!
Vincent

**Comment by rogatec** [comment]
Hi we're currently running alos in an HTTP Request 401 unauthorized error with the Ubuntu 12.04 LTS and Curl Version 7.22.0. We're trying to connect to an Exchange Server 2010 SP2.

Luckily we have also other research options (cygwin on a Windows system with curl version 7.33 and a Debian Wheezy system with 7.40 installed) where all connections went successful.

The cookie option didn't work, but connecting precicsely with NTLM auth was successful.

Maybe some of you guys also running into those problems, have those resolved with this information.

**Comment by Coop666** [comment]
Thank you xibriz, that solved the issue for me.

**Comment by jamesiarmes** [comment]
With the latest version in master, you can override most of the existing cURL options (including `CURLOPT_HTTPAUTH`) or supply your own by calling `setCurlOptions()` on the `Client`.
