### ISSUE TITLE
Calendar: get category of the event 

### ISSUE THREAD

**Issue by maxvsi** [jamesiarmes/php-ews#153]
don't get category of the element:

$events = $response->ResponseMessages->FindItemResponseMessage->RootFolder->Items->CalendarItem;

there are 
        $id = $event->ItemId->Id;
        $change_key = $event->ItemId->ChangeKey;
        $start = $event->Start;
        $end = $event->End;
        $subject = $event->Subject;
        $location = $event->Location;

but no category...

**Comment by segpacto** [comment]
Is there any problem with the code posted above ?
I am not able to obtain the Categories either to insert new ones on Update or Create.

**Comment by keenojingco** [comment]
Hi,

I currently have a working query where it returns the calendar events for the current month. All I'm looking for is to filter that result further to return only events for a certain category or categories.

Any help on this would be appreciated.

Thanks

**Comment by jamesiarmes** [comment]
@keenojingco Your question is not related to this closed issue. If you need additional help, please open a new issue.
