### ISSUE TITLE
How to get and set categories?

### ISSUE THREAD

**Issue by martincollar** [jamesiarmes/php-ews#162]
Hi, it's possible to get list of categories?
Create new category etc..?
I want to retriive list of names and colors, create and update.

Thanks

**Comment by rogatec** [comment]
Quite late, but did you already tried this [here](https://github.com/jamesiarmes/php-ews/wiki/Calendar:-Get-Event-Colors) ?

**Comment by jamesiarmes** [comment]
Updated link http://jamesarmes.com/php-ews/doc/0.1/examples/calendar-get-event-colors.html.
