### ISSUE TITLE
[create calendar events] How to delete / edit automatic sent body message header with time and location in invitation mail to attendee?

### ISSUE THREAD

**Issue by Eric1978** [jamesiarmes/php-ews#163]
Hi everybody,

When i create a new event everything works just ok. My Timezone (W. Europe Standard Time) is good, and the event is planned just at the right time.

The problem is in the body of the event sent to the attendee is an automaticly genereted header:

When: Tuesday, October 01, 2013 6:00 AM-4:00 PM. UTC
Where: tyyj

This is with a wrong time diferent from the time planned.
How can i uncheck this header message in the script, or adjust the time for it?

Thanks and greetz Eric

**Comment by jamesiarmes** [comment]
This library now supports setting the `TimeZoneContext` header using the `setTimezone()` method on the `Client`.
