### ISSUE TITLE
how to use windows authentification

### ISSUE THREAD

**Issue by rmartin1** [jamesiarmes/php-ews#168]
Hello!

is it possible to use the integrated windows authentification? I don't want to use a login page. 
if(!$client = new NTLMSoapClient_Exchange($wsdl,array('trace'=>1,'user'=>$user, 'password'=>$pw)))...

..curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
    curl_setopt($ch, CURLOPT_USERPWD, $this->user.':'.$this->password);..
thanks ;-)

**Comment by jamesiarmes** [comment]
This issue is over three years old. If you are still having trouble with the latest version from master, please open a new issue.
