### ISSUE TITLE
1 year limit for CalendarView (timeframe)

### ISSUE THREAD

**Issue by remixmabix** [jamesiarmes/php-ews#171]
Hello, 

I post here because I can't find solutions.

Well I am retrieving all events from 2012 to 2015 with :

$request->CalendarView->StartDate = strtotime('2012-01-01');
$request->CalendarView->EndDate = strtotime('2015-12-31');

but the request don't understand after current date + 1 year

for example if i set $request->CalendarView->EndDate = strtotime('2014-10-29'); it works

I want to see events more than 1 year from current date, is there a trick in order to avoid this limit ?

All the best

**Comment by jamesiarmes** [comment]
This issue is over three years old. If you are still having trouble with the latest version from master, please open a new issue.
