### ISSUE TITLE
Exclude me from the recipients

### ISSUE THREAD

**Issue by Alist971** [jamesiarmes/php-ews#176]
Hi,

I work on a project for a company where I am in internship.
What I search to do is that from the intranet, an external user can make an appointment request to employees, and this request will be notify on the employees Outlook accounts.
I found PHP-EWS since some time. I think it is appropriate for my project, because the company use Exchange servers. I understood lot of things about PHP-EWS and Exchange since, but not all details that I research.
Reading all the forums and documentation, I could have them, but the majority is written in English and I'm not very comfortable with English, so I couldn't notice them.

So, my question is :

(I think) we have to absolutly login us with an user account ($ews = new ExchangeWebServices('server address', 'username@address', 'password') )
when I send a mail or create an appointment request, can I exclude myself of the recipients? If yes, how can I do this?

Bonjour,

Je travaille sur un projet pour une entreprise dont je suis stagiaire.
Ce que cherche à faire c'est que, depuis l'intranet de l'entreprise on puisse faire une demande de RDV et que cette demande soit notifié sur le compte Outlook de la/les personne(s) concernée(s).
Depuis quelque temps en cherchant un peu, je suis tomber sur une librairie php PHP-EWS, ce qui me semple approprié puisque les comptes Outlook de l'entreprise sont gérés pas un serveur Exchange.
Dans mes recherches, j'ai appris beaucoup de choses sur les différentes fonctionnalités de PHP-EWS et Exchange Serveur, mais pas toutes les précisions que je voudrais. Je pense que je les aurais en lisant les docs et les forums,
mais la plus-part sont en anglais et comme je ne suis pas super alaise avec l'anglais, ils n'ont pas pu me sauter aux yeux.

Donc ma question est la suivante :

Vu qu'il faut (je pense) absolument se connecter avec un compte utilisateur ($ews = new ExchangeWebServices('server address', 'username@address', 'password') )
peut-on lors de l'envoi d'un mail ou d'une demande de rendez-vous s'exclure des destinataires/invités? Si oui, comment?

**Comment by jamesiarmes** [comment]
This issue is over three years old. If you are still having trouble with the latest version from master, please open a new issue.
