### ISSUE TITLE
EwsLegacyId format

### ISSUE THREAD

**Issue by ghost** [jamesiarmes/php-ews#177]
GetItems returns me id in format:

AAMkADU0ZmZmZWViLTVhZjItNGFmNC1iZDJiLTk1ZjA3MDViZmQ5YwBGAAAAAADA3j1Lc3//SaULpEILlZClBwCqAWw+O7K+TJ+ZolV6MUYEAAAANSaFAACqAWw+O7K+TJ+ZolV6MUYEAAAANXkHAAA=

but it seems to be invalid while using it in GetItem
$_id = new \EWSType_ItemIdType();
$_id->Id = $id;
$_request->ItemIds = new \EWSType_NonEmptyArrayOfBaseItemIdsType();
$_request->ItemIds->ItemId = $_id;

object(stdClass)#414 (1) {
  ["ResponseMessages"]=>
  object(stdClass)#412 (1) {
    ["GetItemResponseMessage"]=>
    object(stdClass)#411 (5) {
      ["MessageText"]=>
      string(193) "The EWS Id is in EwsLegacyId format which is not supported by the Exchange version specified by your request. Please use the ConvertId method to convert the Id from EwsId to EwsLegacyId format."
      ["ResponseCode"]=>
      string(23) "ErrorInvalidIdMalformed"
      ["DescriptiveLinkKey"]=>
      int(0)
      ["ResponseClass"]=>
      string(5) "Error"
      ["Items"]=>
      object(stdClass)#409 (0) {
      }
    }
  }
}

**Comment by jamesiarmes** [comment]
First, make sure you're passing the correct version to the constructor. If the id being returned is still in the legacy id format, you will need to use a `ConvertId` operation to get the updated id.

**Comment by ManiMuridi** [comment]
How do I use ConvertId? I'm getting this same error 

"The EWS Id is in EwsLegacyId format which is not supported by the Exchange version specified by your request. Please use the ConvertId method to convert from EwsLegacyId to EwsId format."

**Comment by jamesiarmes** [comment]
You will need to call `ConvertId` on the client, which takes an instance of `\jamesiarmes\PhpEws\Request\ConvertIdType`. If the included documentation is not enough to guide you through creating the request, see https://msdn.microsoft.com/en-us/library/bb799665(v=exchg.150).aspx for more information.

**Comment by ManiMuridi** [comment]
I set the EWS server version to 2007 and everything seems to be working fine... the strange thing is our servers are actually 2013. How's that?

**Comment by jamesiarmes** [comment]
What you're setting is the schema version. By using 2007 when your server is really running 2013, you're limiting yourself to the operations and elements available in Exchange 2007.

**Comment by ManiMuridi** [comment]
Ok Gotcha! Thanks a lot. Great library btw keep it up 👍
