### ISSUE TITLE
SoapFault: Wrong Version

### ISSUE THREAD

**Issue by kvandenhaute** [jamesiarmes/php-ews#179]
Hi,

I'm trying to connect to a Microsoft Exchange 2010, and every time the SoapClient constructor is called I get the error: "SoapFault: Wrong Version". I tried all the possible solutions that I could find, but no result. Do you have any idea how I can find what the exact issue is?

Thanks!

**Comment by bomalley** [comment]
Help!  Still seeing this problem in 2015.  Any suggestions?

**Comment by MrDru** [comment]
Hi,

you should instantiate the `ExchangeWebServices` class with the minimum version `Exchange2007_SP1` (respectively the constant: `ExchangeWebServices::VERSION_2007_SP1`). In this version the structure of the internal Exchange IDs has changed.

Alternatively try to instantiate the class like this (focus on the fourth argument):
```php
new ExchangeWebServices($uri, $user, $pass, 'Exchange2013');
```
Or like this:
```php
new ExchangeWebServices($uri, $user, $pass, 'Exchange2013_SP1');
```

Good luck!
