### ISSUE TITLE
Problem (3) in the Chunked-Encoded data

### ISSUE THREAD

**Issue by nyulasi** [jamesiarmes/php-ews#180]
Hi, 

I'm struggling with this problem from a while. 

With CURL_HTTP_VERSION_1_1 I'm getting the error : Problem (3) in the Chunked-Encoded data.

If I modify to CURL_HTTP_VERSION_1_0 I got a response from the server but the response has a lot of added characters (I suppose these are because f the chunked response???) and for this reason it's not a valid xml file.

The code I'm trying to use :

$headers = array(
 'Method: POST',
 'Connection: Keep-Alive',
 'User-Agent: PHP-SOAP-CURL',
 'Content-Type: text/xml; charset=utf-8',
 'SOAPAction: "'.$action.'"',
 );
$this->ch = curl_init($location);
curl_setopt($this->ch, CURLOPT_SSL_VERIFYPEER, $this->validate);
curl_setopt($this->ch, CURLOPT_SSL_VERIFYHOST, $this->validate);
curl_setopt($this->ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($this->ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($this->ch, CURLOPT_POST, true );
curl_setopt($this->ch, CURLOPT_POSTFIELDS, $request);
curl_setopt($this->ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
curl_setopt($this->ch, CURLOPT_HTTPAUTH, CURLAUTH_NTLM);
curl_setopt($this->ch, CURLOPT_USERPWD, $this->user.':'.$this->password);*

$response = curl_exec($this->ch);

Thank you for help!

**Comment by jamesiarmes** [comment]
This issue is almost three years old. If you are still having trouble with the latest code from master, please open a new issue.
