### ISSUE TITLE
Have FindItem() return To/Cc address lists?

### ISSUE THREAD

**Issue by Niall-Jackson** [jamesiarmes/php-ews#182]
When displaying a filtered list of emails from the server, our client requires that the To: address field be included.

Return FindItem() includes (item)->From->Mailbox->Name, but no equivalent To structure.

Is this configurable at ews end, or will the server need configured?

(Also, would prefer email address to name, if that could be returned.)

**Comment by jamesiarmes** [comment]
These fields are not returned by the `FindItem` operation. You will need to add the ids of any messages you want these fields from to a request and perform a `GetItem` operation.

**Comment by igittigitt** [comment]
Can you give an example? I still don't get it.
I also want to have the mailadress of the organizer.
