### ISSUE TITLE
Calendar Category and Color Issue

### ISSUE THREAD

**Issue by struppinet** [jamesiarmes/php-ews#184]
I am using php-ews with an exchange 2013 server. I am getting alle calendar events of a shared calender where we plan our appointments.
My problem is that when i create an appointment with a category everything is fine, but when i delete the category then the color stays but the category is gone. I read about an issue with Outlook 2003 and older support from Exchange where category and color (aka label) where 2 attributes.
I checked the the label attribute should be Property 0x8214. So I wanted to check whats in it at my test appointment but i got hung with my query. Here is the code and the result:

```php
$ews = new ExchangeWebServices($host, $username, $password, $version);
$request = new EWSType_GetItemType();
$request->ItemShape = new EWSType_ItemResponseShapeType();
$request->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;
$request->ItemShape->AdditionalProperties = new EWSType_NonEmptyArrayOfPathsToElementType();
$request->ItemShape->AdditionalProperties->ExtendedFieldURI = new EWSType_PathToExtendedFieldType();
$request->ItemShape->AdditionalProperties->ExtendedFieldURI->PropertyTag = "0x8214";
$request->ItemShape->AdditionalProperties->ExtendedFieldURI->PropertyType = EWSType_MapiPropertyTypeType::STRING;
$request->ItemIds = new EWSType_NonEmptyArrayOfBaseItemIdsType();
$request->ItemIds->ItemId = new EWSType_ItemIdType();
$request->ItemIds->ItemId->Id = $message_id; 
$response = $ews->GetItem($request);
var_dump($response);die;
```
Results in:
```
Fatal error: Uncaught SoapFault exception: [a:ErrorSchemaValidation] Fehler bei der SchemaÃ¼berprÃ¼fung der Anforderung: Der Inhalt des Elements 'AdditionalProperties' in Namespace 'http://schemas.microsoft.com/exchange/services/2006/types' ist unvollstÃ¤ndig. Erwartet wurde die Liste der mÃ¶glichen Elemente: 'Path, FieldURI, IndexedFieldURI, ExtendedFieldURI' in Namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.
```
It says I didn't provide the ExtendedFieldURI but I did. I checked with the examples for extended fields but I always get the same result. I already faced this problem on my first try to change an appointment where there seems to be a PHP bug with the SOAP client. Maybe it's the same here.

**Comment by jamesiarmes** [comment]
This issue is over two years old. If you are still having trouble with the latest version from master, please open a new issue.
