### ISSUE TITLE
Some properties cause Error 400 - Bad Request

### ISSUE THREAD

**Issue by guerriky** [jamesiarmes/php-ews#189]
Hello, everyone,
I made a class based on this project, in wich I COPIED the code that's in the wiki to add an event.

What happens is that the properties: "ItemClass","Sensitivity" and "Importance" cause a server error 400 - Bad Request; when I take those lines out, everything works just fine.

I included the appropriate files, my debugger ensured this.

Has there been released a new EWSType version?

Thanks for the help,
Riccardo

**Comment by jamesiarmes** [comment]
This issue is over two years old. If you are still having trouble, please open a new issue.
