### ISSUE TITLE
Request: How to lookup room resources from a global address list?

### ISSUE THREAD

**Issue by u01jmg3** [jamesiarmes/php-ews#190]
Hi,

I just wondered if someone could point me in the right direction on how to lookup room resources (or any type of resource) from a connection to Exchange using this library.

Within Outlook I can see room resources in my global address list but I'm not sure how you could hook into this using `php-ews`.

Thanks

**Comment by jamesiarmes** [comment]
Exchange web services does not provide access to the GLA. For rooms, specifically, you can use a `GetRoomLists` operation.

**Comment by u01jmg3** [comment]
Can you provide an example please?

**Comment by jamesiarmes** [comment]
Although outdated, the example in #134 should be sufficient to get you going the right direction.

**Comment by u01jmg3** [comment]
The example links to a Wiki which has moved and the issue contains multiple people asking for help with the using the example from the Wiki when it was available...

**Comment by jamesiarmes** [comment]
The very last comment includes two examples, one for all rooms and one for a room with a specific email.
