### ISSUE TITLE
Meeting New Appointment Subject From Resource Meeting Box

### ISSUE THREAD

**Issue by ikopiko** [jamesiarmes/php-ews#191]
Hi guys :) I am trying to take all meeting from resource meeting box, but when i try to take subject like this  $subject = $event->Subject it displays name by whom meeting was created.  $request->ParentFolderIds->DistinguishedFolderId->Mailbox->EmailAddress = "mail@domain.com" This is code how i select resource meeting box.

I want to take meeting subject by other way and i will be glad if you will help me :)

**Comment by jamesiarmes** [comment]
This issue is over two years old. If you are still having trouble, please open a new issue.
