### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by IanCabell** [jamesiarmes/php-ews#192]
Hi!
I'm getting an EWS_Exception with message 'SOAP client returned status of 302' when trying to connect to an office365 account. I suspect I don't have the correct "server", but all my research points to it being outlook.office365.com.

Could you help point me to what might be wrong?

Thanks!
--Ian

**Comment by jamesiarmes** [comment]
"outlook.office365.com" is in fact the correct server version. This issue is over two years old, if you are still having trouble, please open a new issue.
