### ISSUE TITLE
Support for Office 365 Exchange?

### ISSUE THREAD

**Issue by thomasyung** [jamesiarmes/php-ews#196]
I've tried to use php-ews and the following code to connect to my on-premise Exchange server, and all is good. However, once I try to access the Office 365 Exchange, I get this message in Chrome: 
Unable to load the webpage because the server sent no data.
Error code: ERR_EMPTY_RESPONSE

<pre>

function __autoload($class_name) {
    // Start from the base path and determine the location from the class name,
    $base_path = '.';
    $include_file = $base_path . '/' . str_replace('_', '/', $class_name) . '.php';
    return (file_exists($include_file) ? require_once $include_file : false);
}
$username = $_GET['u'];
$password = $_GET['p'];
$server = $_GET['s'];
//$server = 'outlook.office365.com';
try {
    $ews = new ExchangeWebServices($server, $username, $password);
    $request = new EWSType_FindItemType();
    $request->ItemShape = new EWSType_ItemResponseShapeType();
    $request->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::DEFAULT_PROPERTIES;
    $request->Traversal = EWSType_ItemQueryTraversalType::SHALLOW;
    $request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
    $request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
    $request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::INBOX;
    $request->SortOrder = new EWSType_NonEmptyArrayOfFieldOrdersType();
    $request->SortOrder->FieldOrder = array();
    $order = new EWSType_FieldOrderType();
    $order->FieldURI->FieldURI = 'item:DateTimeReceived'; 
    $order->Order = 'Descending'; 
    $request->SortOrder->FieldOrder[] = $order;
    $response = $ews->FindItem($request);
    echo json_encode($response);
} catch (EWS_Exception $e) {
    echo 'Caught exception: ' . $e->getMessage();
}
</pre>

I also tried using the EWS Java API and that worked like a charm for both on-premise and Office 365. I enabled a trace and I found out that the Office 365 url actually follows a couple redirects before it gets the response back. I modified the code where it does the CURL, and added the CURLOPT_FOLLOWLOCATION to true. However, it still gives the same error. Has anyone figured out how to get this to work with Office 365 Exchange?

**Comment by robforrest-asdan** [comment]
Has anyone managed to get this working as yet? We're hitting the same problems as this.

**Comment by mikaelcom** [comment]
Have you tried with [PackageEws365](https://github.com/WsdlToPhp/PackageEws365) :smile:

**Comment by boubbin** [comment]
I had no problems using https://github.com/Garethp/php-ews which is a fork of this project and seems to be more actively maintained.

The same library was able to connect both: Office 365 Exchange and our own Exchange 2010

**Comment by SuperFred** [comment]
Hi,
for me work like this :
new ExchangeWebServices('outlook.office365.com', 'myuser@mydomain.com', 'mypassword',ExchangeWebServices::VERSION_2010);

**Comment by zwetan** [comment]
Office 365 does work use server "outlook.office365.com"
and any version from
```
EwsConnection:: VERSION_2007
EwsConnection:: VERSION_2007_SP1
EwsConnection:: VERSION_2010
EwsConnection:: VERSION_2010_SP1
EwsConnection:: VERSION_2010_SP2
```

those will fail
```
EwsConnection:: VERSION_2007_SP2
EwsConnection:: VERSION_2007_SP3
```
see #346 Invalid versions

Also, if you want to use impersonation
you will need to

1. go to https://portal.office.com
2. login with your admin account
3. then on the left select "Admin Centers" / "Exchange"
4. on Exchange admin center, select "permissions" on the left
5. double click "Discovery Management"
6. in Roles select "+" and add "ApplicationImpersonation"
7. in Members select "+" and add your admin account
8. save (it could few minutes or so for the settings to change)

my use case was to use the "Microsoft Office 365 Developer" free trial
and impersonate resources like rooms and equipment.

**Comment by jamesiarmes** [comment]
This library supports Exchange Online/Office 365 using "outlook.office365.com" for the server. You should be using `Client::VERSION_2016` as the version.
