### ISSUE TITLE
Accessing to GAL

### ISSUE THREAD

**Issue by ancafe** [jamesiarmes/php-ews#197]
I would be interested in to access the GAL and public groups. Does anyone know if it is possible with php-ews? Or at least be able to access through LDAP to our Office365 account.

Thanks

**Comment by FrodeMMeling** [comment]
I´m also looking at listing and adding GAL contacts. I can see the GAL folder listed when I do a FindFolder in CONTACTS, but I am not able to searh the list using Folder.id.

Any ideas?

**Comment by jamesiarmes** [comment]
This is not possible with Exchange Web Services.
