### ISSUE TITLE
SOAPFAULT: SOAP-ERROR: Encoding: object has no 'SearchExpression' property

### ISSUE THREAD

**Issue by zachkauffman** [jamesiarmes/php-ews#198]
This has been truly baffling for me. Two days ago I had your library working perfectly with all of my EWS files using a restriction as so:

$start = new DateTime('2014-06-05'); 

$Request->Restriction = new EWSType_RestrictionType();
$Request->Restriction->And = new EWSType_AndType();

$Request->Restriction->And->IsGreaterThan = new EWSType_IsGreaterThanType();
$Request->Restriction->And->IsGreaterThan->FieldURI = new stdClass;
$Request->Restriction->And->IsGreaterThan->FieldURI->FieldURI = 'item:DateTimeSent';
$Request->Restriction->And->IsGreaterThan->FieldURIOrConstant->Constant->Value = $start->format('c');

Now, whenever I try to run this script I get the error message in the title. I have checked and my files do contain references to SearchExpression and SearchExpressionType.

If necessary I'd be more than happy to post my wsdl and xsd files. Any clue what this error could be stemming from?

**Comment by jamesiarmes** [comment]
This has been resolved long ago. If you're still having issue with the latest code from master, please open a new issue.
