### ISSUE TITLE
Always error 401

### ISSUE THREAD

**Issue by nepstor** [jamesiarmes/php-ews#203]
Hi everyone.
Trying to connect to Exchange 2007 SP3. Always error 401.
On my machine Debian 7, php55.
curl 7.37.1 (x86_64-unknown-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

Command output curl_version(): 

``` php
array (size=9)
  'version_number' => int 465408
  'age' => int 3
  'features' => int 50813
  'ssl_version_number' => int 0
  'version' => string '7.26.0' (length=6)
  'host' => string 'x86_64-pc-linux-gnu' (length=19)
  'ssl_version' => string 'OpenSSL/1.0.1e' (length=14)
  'libz_version' => string '1.2.7' (length=5)
```

Tried solution https://github.com/jamesiarmes/php-ews/issues/152. It does not help.

Where there may be an error?
Thanks!

**Comment by jamesiarmes** [comment]
This issue is over two years old and the minimum required cURL version is now 7.30.0. If you are still having this issue with the latest code from master and an updated version of cURL, please open a new issue.
