### ISSUE TITLE
HTTP Error 400. The request verb is invalid. (+ solution)

### ISSUE THREAD

**Issue by Fluxlicious** [jamesiarmes/php-ews#209]
Hi,

I've been hitting my head against the wall with this problem, so i took the time to register on GitHub to post the solution.

Anyway, it took me a long time because i was looking in the wrong place for a solution. First thing i tried to do with php-ews was to create a calendar item with quite a large body text. PHP was throwing back a "Uncaught SoapFault exception: [Client] looks like we got no XML document in ..." error. Then it took me a while until i found out that it was actually Exchange (using office365) that was always spitting back a regular HTML page with "HTTP Error 400. The request verb is invalid." With this new error it came clear to me it was most likely a cUrl issue. After some more testing i found out that it did work with a smaller body text. The complete Soap XML content length couldn't be larger that 1024.
So pretty quick i found this page: http://stackoverflow.com/questions/463144/php-http-post-fails-when-curl-data-1024

--- quote of solution ---
You can convince PHP's curl backend to stop doing the 100-continue-thing by setting an explicit request header:

curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:'));
This way you can post a request however long you would ever want and curl will not do the dual phase post.
--- end quote ---

So i added the 'Expect:' header on line 66 in NTLMSoapClient.php and it worked like a charm!

**Comment by jamesiarmes** [comment]
This has been resolved with the latest version in master.
