### ISSUE TITLE
use convertid method

### ISSUE THREAD

**Issue by nikunjtrapasiya** [jamesiarmes/php-ews#211]
Hi Guys

trying to use convertid method to get different type of ID

what code i should use. i cant find any example. 

public function ConvertId($request)
    {
        $this->initializeSoapClient();

```
    echo __FUNCTION__;

    $response = $this->soap->{__FUNCTION__}($request);

    return $this->processResponse($response);
}
```

**Comment by anyandallart** [comment]
Hey @nikunjtrapasiya , did you ever get this figured out? I'm working on trying to figure out the same thing now. Thanks!

**Comment by anyandallart** [comment]
@nikunjtrapasiya Got this figured out, and also in case anyways helps needs it.

`

//Replace with your credentials
$ews = new ExchangeWebServices($ews_host, $ews_user, $ews_password, $ews_version);

$request = new EWSType_ConvertIdType();

/*Specify the original format of the ID (types are 'EntryId', 'EwsId', 'EwsLegacyId', 'HexEntryId', 'OwaId', 'StoreId') */
$request->SourceIds->AlternateId->Format='HexEntryId';

//Replace $TheIdYouWantToConvert with The original Id
$request->SourceIds->AlternateId->Id=$TheIdYouWantToConvert;

//Must be the primary SMTP email address
$request->SourceIds->AlternateId->Mailbox='user@domain.com';

/*Specify the new format you want (types are 'EntryId', 'EwsId', 'EwsLegacyId', 'HexEntryId', 'OwaId', 'StoreId') */
$request->DestinationFormat='EwsId';

$response = $ews->ConvertId($request);
print_r($response);
`
