### ISSUE TITLE
Cancel calendar event Exchange 2013

### ISSUE THREAD

**Issue by foaly-nr1** [jamesiarmes/php-ews#219]
Hiya,

I am using this excellent library with Office 365 which is running an Exchange 2013 CU1 server. Creation, update and deletion of calendar events works like a charm as outlined in the wiki, but I can't figure out how to mark an event as cancelled.

The EWSType_CalendarItemType::IsCancelled property seems outdated. I believe to recall I read that a cancellation needs to be created as a new item, but can't find any info on this (anymore). Does anyone have an example handy by any chance? Could that be added to the wiki as well?

Many thanks

**Comment by jamesiarmes** [comment]
I have added an [event/cancel](https://github.com/jamesiarmes/php-ews/blob/master/examples/event/cancel.php) example that should cover this.
