### ISSUE TITLE
Can Get List   function get the Body content?

### ISSUE THREAD

**Issue by 2011xiaomeng** [jamesiarmes/php-ews#227]
don't get body of the element:

$events = $response->ResponseMessages->FindItemResponseMessage->RootFolder->Items->CalendarItem;

there are
$id = $event->ItemId->Id;
$change_key = $event->ItemId->ChangeKey;
$start = $event->Start;
$end = $event->End;
$subject = $event->Subject;
$location = $event->Location;

but no body...

**Comment by jamesiarmes** [comment]
The `FindItem` operation does not include the body of items. You can perform a single `GetItem` operation to get the body and any other fields not included in the find operation. See the contact/describe example in the code.
