### ISSUE TITLE
Adding a calendar event to someone else's (shared) calendar

### ISSUE THREAD

**Issue by sergejgoldstein** [jamesiarmes/php-ews#237]
I am trying to add an event to someone else's Exchange calendar.  In this discussion, let's call me the "organizer",  and the person whose calendar I am trying to update the "attendee".   The attendee has shared their calendar (read/write) with the organizer.  Item 201 shows how to do this using meeting invitations, but for that to work well, the attendee has to set up their calendar to automatically accept meeting invitations, something most people won't want to do (there is a way to write a macro that accepts invitations only from the organizer, but it is difficult and requires certs).  The question is, why can't the organizer save the event directly into the attendee's calendar?  

Based on other posts, I tried the following, but it only puts the event in the organizer's calendar.

// Create the service object
        $ews = ExchangeWebServices($host, $organizer_email_address, $organizer_password);
// Start building the request.
        $request = new EWSType_CreateItemType();
        $request->Items = new EWSType_NonEmptyArrayOfAllItemsType();
        $request->Items->CalendarItem = new EWSType_CalendarItemType();

```
    // Point to the attendee (shared) calendar.
    $request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
    $request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
    $request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;
    $request->ParentFolderIds->DistinguishedFolderId->Mailbox = new StdClass();
    $request->ParentFolderIds->DistinguishedFolderId->Mailbox->EmailAddress = $email_of_attendee;

    // Set the subject.
    $request->Items->CalendarItem->Subject = 'WASP Appointment'
    // Set the start and end times. 

    $request->Items->CalendarItem->Start = $dates . 'T' . $tstart . '+00:00';

    $request->Items->CalendarItem->End = $datee . 'T' . $tend . '+00:00';

    // Set no reminders
    $request->SendMeetingInvitations = EWSType_CalendarItemCreateOrDeleteOperationType::SEND_TO_NONE;


    // Add the event
    $response = $ews->CreateItem($request);
```

This code works, but, as I say, the event gets added to the organizer's calendar, not the attendees.  What else is needed to get the event into the attendee's calendar (and only that calendar)?

**Comment by nikunjtrapasiya** [comment]
Your IT team needs to setup full access to organiser to attendees. only attendees gives read/write access is not sufficient.

I have set up a master account which has full access to all the staff in our company so i use it as setting up calendar meeting in anyone's calendar. however it wont auto accept but it sends an invite to attendees.

**Comment by sergejgoldstein** [comment]
nikunjtrapasiya,
Thanks for the comment, but I don't think this is a rights issue.  I can login to Outlook as the organizer, open the attendees calendar, and add appointments to it.  And I am not getting any kind of error message when I try to add an appointment using php-ews.  I think the code is just not right --- I don't I have correctly set up the objects to tell Exchange that I want to put the appointment in the attendees calendar.  Has anyone successfully done this?

**Comment by nikunjtrapasiya** [comment]
I use below code to send invite to other user and then they accept it.
```
	$subject                                                  = 'Appointment with ..';
	
$ews                                                      = new ExchangeWebServices(EWS_URL, EWS_USER, EWS_PWD, EWS_SERVER);
		// Start building the request.
		$request                                                  = new EWSType_CreateItemType();
		$request->Items                                           = new EWSType_NonEmptyArrayOfAllItemsType();
		$request->Items->CalendarItem                             = new EWSType_CalendarItemType();
		// Set the subject.
		$request->Items->CalendarItem->Subject                    = $subject;
		// Set the start and end times. For Exchange 2007, you need to include the timezone offset.
		$date1                                                    = new DateTime($data['dtp_input1']);
		$DateStart                                                = $date1->format('Y-m-d H:i:00');
		$date                                                     = new DateTime($DateStart);
		$request->Items->CalendarItem->Start                      = $date->format('c');
		$date1                                                    = new DateTime($data['dtp_input2']);
		$DateEnd                                                  = $date1->format('Y-m-d H:i:00');
		$date                                                     = new DateTime($DateEnd);
		$request->Items->CalendarItem->End                        = $date->format('c');
		// Set no reminders
		$request->Items->CalendarItem->ReminderIsSet              = false;
		// Or use this to specify when reminder is displayed (if this is not set, the default is 15 minutes)
		$request->Items->CalendarItem->ReminderMinutesBeforeStart = 15;
		// Build the body.
		$request->Items->CalendarItem->Body                       = new EWSType_BodyType();
		$request->Items->CalendarItem->Body->BodyType             = EWSType_BodyTypeType::HTML;

$request->Items->CalendarItem->Body->_                                               = <<<EOD

    <p><strong>Staff Attending</strong>:{$staff1},{$staffAttending}</p>

EOD;
		// Set the item class type (not required).
		$request->Items->CalendarItem->ItemClass                                             = new EWSType_ItemClassType();
		$request->Items->CalendarItem->ItemClass->_                                          = EWSType_ItemClassType::APPOINTMENT;
		// Set the sensativity of the event (defaults to normal).
		$request->Items->CalendarItem->Sensitivity                                           = new EWSType_SensitivityChoicesType();
		$request->Items->CalendarItem->Sensitivity->_                                        = EWSType_SensitivityChoicesType::NORMAL;
		// Add some categories to the event.
		$request->Items->CalendarItem->Categories                                            = new EWSType_ArrayOfStringsType();
		$request->Items->CalendarItem->Categories->String                                    = array(
			'Client Meeting (Scheduled)'
		);
		// Set the importance of the event.
		/*$request->Items->CalendarItem->Importance = new EWSType_ImportanceChoicesType();

		$request->Items->CalendarItem->Importance->_ = EWSType_ImportanceChoicesType::NORMAL;*/
		$request->Items->CalendarItem->Location                                              = $data['available_room'];
		// Send meeting invitations.
		$request->SendMeetingInvitations                                                     = EWSType_CalendarItemCreateOrDeleteOperationType::SEND_ONLY_TO_ALL;
		$request->Items->CalendarItem->RequiredAttendees->Attendee[0]->Mailbox->EmailAddress = $data['chair'];
		$request->Items->CalendarItem->RequiredAttendees->Attendee[0]->Mailbox->RoutingType  = 'SMTP';
		$n                                                                                   = 1;
		foreach ($attendees as $key => $val) {
			$request->Items->CalendarItem->RequiredAttendees->Attendee[$n]->Mailbox->EmailAddress = $val;
			$request->Items->CalendarItem->RequiredAttendees->Attendee[$n]->Mailbox->RoutingType  = 'SMTP';
			$n++;
		}
		//$request->setDefaultTimeZone='Australia/Melbourne';
		$response      = $ews->CreateItem($request);
```

**Comment by sergejgoldstein** [comment]
Right, I know this works.  I can send invites.  The problem for me is that I am writing an office-hours scheduling application (WASS -- it is open source), and the people involved have already committed to the meeting; they just want to see the meeting on their calendars, and have that time blocked out.  So I need to be able to put the meeting directly on their calendar, rather than just sending an invitation.

**Comment by kperry42** [comment]
To post an event directly to another user's calendar (assuming they have given you permission to do so), you need to set the SavedItemFolderId of the request.  Just create a folder-ids object as in the original post, and assign it to SavedItemFolderId (rather than ParentFolderIds):

    $folder = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
    $folder->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
    $folder->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;
    $folder->DistinguishedFolderId->Mailbox = new stdClass();
    $folder->DistinguishedFolderId->Mailbox->EmailAddress = $this->calDelegate->getCalendarMailbox();

    $request->SavedItemFolderId = $folder;

    $response = $ews->CreateItem($request);

**Comment by sergejgoldstein** [comment]
Thanks!
Serge

**Comment by jangatzke** [comment]
I am trying to add attendees to an existing event. Let's say the organizer already has an event in his or hers calendar including or not including some attendees. How can I add this already existing event to some other user's mailbox? I do not want to copy the event but to keep the link between both calendar entries.  Is this possible?
