### ISSUE TITLE
Fatal Error --> SOAP client returned status of 405

### ISSUE THREAD

**Issue by tutorialmaker555** [jamesiarmes/php-ews#242]
Hello,

i'm trying your source code to connect my exchange 2010.

Now, i get this error:
Fatal error: Uncaught exception 'EWS_Exception' with message 'SOAP client returned status of 405' 

Could you explain whats is mean?

**Comment by guerriky** [comment]
Hi,
the internet says "Method not allowed".

Could you mention the snippet that you used or (better) post your code here?

The only thing I can tell you is that I had that error when I had a too old version of the cURL extension. Try checking that out.

For me, no error from 7.31 and above.

**Comment by tutorialmaker555** [comment]
There was an Error 401, we have updated the curl.
Since updating curl it shows 405.
I have not change the source code Only add requires and the login-data

**Comment by guerriky** [comment]
Ok then,
maybe the connection string? 
What URL are you trying to call?

**Comment by jamesiarmes** [comment]
This usually occurs if you attempt to perform an operation that your version of Exchange does not support. Could you post your code that's using the library along with your Exchange version?

**Comment by tutorialmaker555** [comment]
we have tried some accounts even the admin but it returns only the same error:

Fatal error: Uncaught exception 'EWS_Exception' with message 'SOAP client returned status of 405' in /######/soap/ews/ExchangeWebServices.php:1222 Stack trace: #0 /######/soap/ews/ExchangeWebServices.php(531): ExchangeWebServices->processResponse(NULL) #1 /####t/soap/ews/ews.php(65): ExchangeWebServices->FindFolder(Object(EWSType_FindFolderType)) #2 {main} thrown in /######/Service_Test/soap/ews/ExchangeWebServices.php on line 1222

Have someone any idea what's the problem. We suspect the rights or a certifacte are not correct on our Exchange?

**Comment by jamesiarmes** [comment]
This issue is almost two years old and still does not include the code being used to make the request. If you're still having trouble with the latest code from master, please open a new issue.
