### ISSUE TITLE
Getting - Fatal error: Uncaught exception 'EWS_Exception' with message 'Curl error: Failed connect to mail.catahosting.com.au:443

### ISSUE THREAD

**Issue by mayur8188** [jamesiarmes/php-ews#243]
Fatal error: Uncaught exception 'EWS_Exception' with message 'Curl error: Failed connect to mail.catahosting.com.au:443; No error' in C:\inetpub\wwwroot\Dropbox\secure.realsoft.com.au\application\third_party\php-ews-master\NTLMSoapClient.php:89 Stack trace: #0 [internal function]: NTLMSoapClient->__doRequest('<?xml version="...', 'https://mail.ca...', 'http://schemas....', 1, 0) #1 C:\inetpub\wwwroot\Dropbox\secure.realsoft.com.au\application\third_party\php-ews-master\ExchangeWebServices.php(331): SoapClient->__call('CreateItem', Array) #2 C:\inetpub\wwwroot\Dropbox\secure.realsoft.com.au\application\third_party\php-ews-master\ExchangeWebServices.php(331): NTLMSoapClient_Exchange->CreateItem(Object(EWSType_CreateItemType)) #3 C:\inetpub\wwwroot\Dropbox\secure.realsoft.com.au\application\controllers\email.php(323): ExchangeWebServices->CreateItem(Object(EWSType_CreateItemType)) #4 C:\inetpub\wwwroot\Dropbox\secure.realsoft.com.au\application\controllers\email.php(84): Email->sendEmail() #5 [internal function]: Email->send in C:\inetpub\wwwroot\Dropbox\secure.realsoft.com.au\application\third_party\php-ews-master\NTLMSoapClient.php on line 89

**Comment by jamesiarmes** [comment]
You should not specify a port number with your server hostname.
