### ISSUE TITLE
HTTPS connection hanging indefinitely

### ISSUE THREAD

**Issue by hunterkreie** [jamesiarmes/php-ews#248]
Hi all, 

Thought I would share this for what it's worth. I was running into an issue with my Exchange server where HTTPS connections would just hang indefinitely. I suspected a possible issue with authentication, and started messing with some settings. Removing CURLAUTH_BASIC fixed my problem, but I don't know the underlying cause, if it is a PHP bug or something with my Exchange server config. Just thought I would share in case others encounter the same issue.

NTLMSoapClient.php - line 78
- curl_setopt($this->ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC | CURLAUTH_NTLM);
- curl_setopt($this->ch, CURLOPT_HTTPAUTH, CURLAUTH_NTLM);

**Comment by anvio** [comment]
We had a similar issue after upgrading libcurl from version 7.37.1 to 7.47.0. There were a lot of changes to NTLM in cURL between these versions (https://curl.haxx.se/changes.html). One of them may has caused this issue. However, we were able to solve the problem by adding:

NTLMSoapClient.php - line 80

- curl_setopt($this->ch, CURLOPT_FORBID_REUSE, true );

**Comment by jamesiarmes** [comment]
Some Exchange servers seem to have issue with `CURLAUTH_BASIC | CURLAUTH_NTLM`. With the latest version of the client, you can set your own cURL options using something like the following:

```php
$client->setCurlOptions(array(
    CURLOPT_HTTPAUTH => CURLAUTH_NTLM,
));
```

This can be used to override most options, or set your own.
