### ISSUE TITLE
Email - Mark as Read

### ISSUE THREAD

**Issue by aemerich** [jamesiarmes/php-ews#250]
How can I set a message as read?

**Comment by deancsmith** [comment]
This SO might help:

http://stackoverflow.com/questions/12354190/php-ews-2010-how-to-set-the-isread-flag

Maybe you can post here or update the wiki once you have a working example?

**Comment by aemerich** [comment]
I tried to apply, but no success.

Code:
$request2 = new EWSType_UpdateItemType();
$request2->ConflictResolution = 'AlwaysOverwrite';
$request2->ItemChanges = array();

$change = new EWSType_ItemChangeType();
$change->ItemId = new EWSType_ItemIdType();
$change->ItemId->Id = $mail->ItemId->Id;
$change->ItemId->ChangeKey = $mail->ItemId->ChangeKey;

$field = new EWSType_SetItemFieldType();
$field->FieldURI = new EWSType_PathToUnindexedFieldType();
$field->FieldURI->FieldURI = "item:IsRead";
$field->Message = new EWSType_MessageType();
$field->Message->IsRead = true;

$change->Updates->SetItemField[] = $field;

$request2->ItemChanges[] = $change;
$response = $ews->UpdateItem($request2);

--
Result:

Fatal error: Uncaught SoapFault exception: [a:ErrorSchemaValidation]
The request failed schema validation: The 'FieldURI' attribute is
invalid - The value 'item:IsRead' is invalid according to its datatype
'http://schemas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType'
- The Enumeration constraint failed. in
/var/www/html/conf/classes/php-ews/ExchangeWebServices.php:1147
Stack trace:
#0 /var/www/html/conf/classes/php-ews/ExchangeWebServices.php(1147):
SoapClient->__call('UpdateItem', Array)
#1 /var/www/html/conf/classes/php-ews/ExchangeWebServices.php(1147):
NTLMSoapClient_Exchange->UpdateItem(Object(EWSType_UpdateItemType))
#2 /var/www/html/conf/exchange.php(102):
ExchangeWebServices->UpdateItem(Object(EWSType_UpdateItemType))
#3 {main}
  thrown in /var/www/html/conf/classes/php-ews/ExchangeWebServices.php
on line 1147


André Emerich*DB Sistemas & Telecom* andre@dbsistemas.info
*(51) 9893-6997** (51) 3013-2906*www.dbsistemas.info
<http://dbsistemas.info/> <http://twitter.com/#!/dbsistemas>
<https://www.facebook.com/pages/DB-Sistemas/240021592699924>
<http://www.linkedin.com/company/db-sistemas/>

**Comment by deancsmith** [comment]
I think you're trying to use a type that doesn't exist, or doesn't exist in
the main types.xsd.

https://github.com/jamesiarmes/php-ews/blob/master/wsdl/types.xsd

I couldn't see item:isRead here but instead message:isRead.

**Comment by MiguelJohnsonny** [comment]
@deancsmith Thanks this was useful! 
I just wanted to add that you will probably need to add `$request2->MessageDisposition = 'Save Only';` in there too so you dont get a response error. Other message dispostion values can be found in types xml file [https://github.com/jamesiarmes/php-ews/blob/master/wsdl/types.xsd](url)
