### ISSUE TITLE
401 error using Curl 7.25.0 on ubuntu 12.04 server trying to connect to Exchange 2010 SP3

### ISSUE THREAD

**Issue by insuranceshop** [jamesiarmes/php-ews#252]
Hi,

First of all thank you very much for bringing this project to life, I am hoping to get some good use of it if I can manage to figure out the authentication part. 

My initial curl version was 7.22.0 and after reading issue #11, #34  and #119, I compiled curl 7.25.0 from source with php.

With curl 7.25.0 I do not have the " \* gss_init_sec_context() failed: : Credentials cache file '/tmp/krb5cc_0' not found " problem anymore, however, I do not get a 302 either; I keep getting a 401 Unauthorized.

Below is what my curl connection test results look like, I have been experimenting with this for over 2 weeks now and kinda sorta ran out of things to try. I would deeply appreciate any advice that point to a solution:

curl -v https://mail.domainname.com/ews/exchange.asmx -w %{http_code} --ntlm -u DOMAIN\user:password -k
- About to connect() to mail.domainname.com port 443 (#0)
-   Trying 172.16.6.17...
- connected
- Connected to mail.domainname.com (172.16.6.17) port 443 (#0)
- successfully set certificate verify locations:
-   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
- SSLv3, TLS handshake, Client hello (1):
- SSLv3, TLS handshake, Server hello (2):
- SSLv3, TLS handshake, CERT (11):
- SSLv3, TLS handshake, Server key exchange (12):
- SSLv3, TLS handshake, Server finished (14):
- SSLv3, TLS handshake, Client key exchange (16):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSLv3, TLS change cipher, Client hello (1):
- SSLv3, TLS handshake, Finished (20):
- SSL connection using ECDHE-RSA-AES256-SHA
- Server certificate:
-        subject: C=US; ST=STATE; L=City; O=Company Name LLC; OU=IT; CN=mail.domainname.com
-        start date: 2015-03-11 18:49:32 GMT
-        expire date: 2017-03-10 18:49:32 GMT
-        subjectAltName: mail.domainname.com matched
-        issuer: DC=local; DC=DOMAIN; CN=DOMAIN-TISDC01-CA
-        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
- Server auth using NTLM with user 'DOMAIN\user'
  > GET /ews/exchange.asmx HTTP/1.1
  > Authorization: NTLM TlRMTVNTUAABAAAABoIIAAAAAAAAAAAAAAAAAAAAAAA=
  > User-Agent: curl/7.25.0 (x86_64-unknown-linux-gnu) libcurl/7.25.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
  > Host: mail.domainname.com
  > Accept: _/_
  >
  < HTTP/1.1 401 Unauthorized
  < Server: Microsoft-IIS/8.5
  < Set-Cookie: exchangecookie=303ed70566b54d279ad0e5ebb7490e07; expires=Sun, 27-Mar-2016 22:21:00 GMT; path=/; HttpOnly
  < WWW-Authenticate: Negotiate
  < X-Powered-By: ASP.NET
  < Date: Fri, 27 Mar 2015 22:21:00 GMT
  < Content-Length: 0
  <
- Connection #0 to host mail.domainname.com left intact
  401\* Closing connection #0
- SSLv3, TLS alert, Client hello (1):

On the php-ews side I get:

Fatal error: Uncaught exception 'EWS_Exception' with message 'SOAP client returned status of 401' in /usr/local/apache2/htdocs/php-ews-master/ExchangeWebServices.php:1221 Stack trace: #0 /usr/local/apache2/htdocs/php-ews-master/ExchangeWebServices.php(547): ExchangeWebServices->processResponse(NULL) #1 /usr/local/apache2/htdocs/inbox.php(57): ExchangeWebServices->FindItem(Object(EWSType_FindItemType)) #2 {main} thrown in /usr/local/apache2/htdocs/php-ews-master/ExchangeWebServices.php on line 1221

**Comment by jamesiarmes** [comment]
This issue is over a year old and the minimum recommended version of cURL is now 7.30.0. If you are still having trouble with a newer version of cURL and the latest code from master, please open a new issue.
