### ISSUE TITLE
php-ews/php-ews on Packagist

### ISSUE THREAD

**Issue by adamelso** [jamesiarmes/php-ews#253]
Hi there, I am the developer who registered the current `php-ews/php-ews` package on [Packagist](https://packagist.org/packages/php-ews/php-ews) so I could install it with Composer. Other than that, I originally created the fork for use in my own project at the last company I worked for, to try and utilize some newer PHP concepts and libraries. The plan was then to dissect the library into other packages and add additional features and adapters for common frameworks.

However my time has become more limited recently and so has my access to an Exchange Server.

So when this project is ready to support installation via Composer, I'd be happy to transfer the `php-ews/php-ews` over to you. At the moment the package has had over 800 installs so this would have to be done carefully if this happens. :)

Many thanks,
Adam

**Comment by jamesiarmes** [comment]
Thanks, @adamelso! I'm currently implementing PSR-4 and will be ready to add composer support once that is complete. If you'd like to do the transfer now rather than waiting until I have that complete, I can create a branch from your current master and point packagist at that.

**Comment by adamelso** [comment]
Cool, I'll need to add you to the list of package maintainers, what username are you using on Packagist?

**Comment by jamesiarmes** [comment]
Same as here, jamesiarmes.

**Comment by adamelso** [comment]
Thank you, done. Now that I've added yourself, you may proceed to remove myself as a maintainer.

**Comment by jstroem** [comment]
Anything new on this issue? - will it soon be moved, im eager to install this repo using composer.

**Comment by jamesiarmes** [comment]
I took over this package on packagist long ago.
