### ISSUE TITLE
not collected Exception: Wrong Version 

### ISSUE THREAD

**Issue by Xymzz** [jamesiarmes/php-ews#254]
Hello.

Always when i try to load the basic example or anything else from the wiki i get the message:
not collected Exception: Wrong Version.
If i use at the file ExchangeWebService.php
               'user' => $this->username,
                'password' => $this->password,
                'version' => $this->version,
                'location' => 'https://'.$this->server.'/EWS/Exchange.asmx',

the browser just loads infinity and i have to close it or i cant load anything else.
If i use just http then i get the error message. Does anybody know why?
My exchange has no Certification and is just an ...no-ip.org adress. Could i be that this is the issue?

**Comment by jamesiarmes** [comment]
This issue is over a year old. If you are still having problem with the latest version from master, please open a new issue.
