### ISSUE TITLE
Get Flagged emails for last 30 days.

### ISSUE THREAD

**Issue by krafi** [jamesiarmes/php-ews#264]
I was able to retrieve all emails that were flagged but I want to get filtered flagged emails for last 30 days.
I used following code to retrieve count of flagged items:

$ews = new ExchangeWebServices($server, $username, $password,ExchangeWebServices::VERSION_2010);

$request = new EWSType_FindFolderType();

$itemProperties = new EWSType_FolderResponseShapeType();
$itemProperties->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;
$itemProperties->BodyType = EWSType_BodyTypeResponseType::BEST;
$request->FolderShape = $itemProperties;

$fieldType = new EWSType_PathToUnindexedFieldType();
$fieldType->FieldURI = 'folder:DisplayName';

$constant = new EWSType_FieldURIOrConstantType();
$constant->Constant = new EWSType_ConstantValueType();
$constant->Constant->Value = "To-Do Search";

$request->Restriction = new EWSType_RestrictionType();
$request->Restriction->IsEqualTo = new EWSType_IsEqualToType();
$request->Restriction->IsEqualTo->FieldURI = $fieldType;
$request->Restriction->IsEqualTo->FieldURIOrConstant = $constant;

$request->IndexedPageItemView = new EWSType_IndexedPageViewType();
$request->IndexedPageItemView->BasePoint = 'Beginning';
$request->IndexedPageItemView->Offset = 0;

$request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
$request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
$request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::ROOT;

$request->Traversal = EWSType_FolderQueryTraversalType::SHALLOW;

$result = new EWSType_FindFolderResponseMessageType();
$result = $ews->FindFolder($request);

Please help!

and Is there a way to apply multiple filters?

**Comment by krafi** [comment]
and Is there a way to apply multiple filters?

**Comment by jamesiarmes** [comment]
I have added a new [message/find](https://github.com/jamesiarmes/php-ews/blob/master/examples/message/find.php) example which uses a restriction to find emails within a time range.
