### ISSUE TITLE
Sort by message:IsRead, Please kindly help!

### ISSUE THREAD

**Issue by yu0307** [jamesiarmes/php-ews#265]
Hi, I tried to do a sort on is read property so that anything unread will be at the top of the list. I think this is a popular feature but why It doesn't seem to work. Please help please~~~

$order = new EWSType_FieldOrderType();
$order->FieldURI=new EWSType_PathToUnindexedFieldType();
$order->FieldURI->FieldURI = 'message:IsRead'
$order->Order = 'Descending';
$request->SortOrder->FieldOrder=$order;
$response = $this->ews->FindItem($request);

//-----------------------------------------------
this code produce no issue but always return no data.
Please help

**Comment by jamesiarmes** [comment]
Exchange web services does not allow sorting via the `IsRead` field.
