### ISSUE TITLE
[Q] Get user account details without "ResolveNames"

### ISSUE THREAD

**Issue by crash5** [jamesiarmes/php-ews#268]
Hi!

Is it possible to get the user details without the "ResolveNames" function? (like full name, email address, time zone, phone number etc.)

**Comment by dreaddy** [comment]
Also searching for an alternative option to get the user details from a search

**Comment by jamesiarmes** [comment]
Unless this information is already included in a response, there is not. The ResolveNames is the only way to get this additional information.
