### ISSUE TITLE
php-ews breaks after upgrade to Exchange 2013 CU 6

### ISSUE THREAD

**Issue by Zxurian** [jamesiarmes/php-ews#270]
so I had a working php-ews connecting to an Exchange 2013 server. Their server crashed, and in the processing of restoring it, they upgraded to Exchange 2013 CU 6 (Was using previous verison of Exchange 2013 without issue).

The first error I got was
```
Fatal error:  Uncaught SoapFault exception: [Client] looks like we got no XML document in /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php:545
Stack trace:
#0 /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php(545): SoapClient-&gt;__call('FindItem', Array)
#1 /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php(545): NTLMSoapClient_Exchange-&gt;FindItem(Object(EWSType_FindItemType))
#2 /home/enterdev/public_html/exchange_connect/get.php(106): ExchangeWebServices-&gt;FindItem(Object(EWSType_FindItemType))
#3 {main}
  thrown in /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php on line 545
```

trying to connect directly to the host, I saw that it was redirecting to `<host>/owa/` so I thought I'd update my connection with `<host>/owa/` instead of just `<host>`, then I got the following error
```
Fatal error:  Uncaught SoapFault exception: [VersionMismatch] Wrong Version in /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php:545
Stack trace:
#0 /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php(545): SoapClient-&gt;__call('FindItem', Array)
#1 /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php(545): NTLMSoapClient_Exchange-&gt;FindItem(Object(EWSType_FindItemType))
#2 /home/enterdev/public_html/exchange_connect/get.php(106): ExchangeWebServices-&gt;FindItem(Object(EWSType_FindItemType))
#3 {main}
  thrown in /home/enterdev/public_html/exchange_connect/php-ews-master/ExchangeWebServices.php on line 545
```

Unfortunately I'm now at a loss on how to proceed. Is there something on the server that missed being turned on? or anything else I can do on my end to get it to connect?

**Comment by Zxurian** [comment]
(added description)

**Comment by joadha** [comment]
In EWSAutodiscover::parseServerVersion(), try adding

       } elseif ($majorversion == 15) {
            return ExchangeWebServices::VERSION_2013;
       }

at the end of the main IF block in the method. 

Then in ExchangeWebServices.php, add the following property:

    /**
     * Microsoft Exchange 2013
     *
     * @var string
     */
    const VERSION_2013 = 'Exchange2013';

Might not be the most correct fix, but it seems to be working for me.

**Comment by Zxurian** [comment]
@jodha would that still apply if I'm specifying the version in my initial request?

**Comment by Zxurian** [comment]
@joadha tried updating code as you specified, still same error messages.

**Comment by Zxurian** [comment]
dumping `curl_getinfo()` of the request yields
```
array(26) {
  ["url"]=>
  string(47) "https://<host>/owa/Exchange.asmx"
  ["content_type"]=>
  string(24) "text/html; charset=utf-8"
  ["http_code"]=>
  int(440)
  ["header_size"]=>
  int(276)
  ["request_size"]=>
  int(1066)
  ["filetime"]=>
  int(-1)
  ["ssl_verify_result"]=>
  int(0)
  ["redirect_count"]=>
  int(0)
  ["total_time"]=>
  float(0.437901)
  ["namelookup_time"]=>
  float(0.000811)
  ["connect_time"]=>
  float(0.09782)
  ["pretransfer_time"]=>
  float(0.332738)
  ["size_upload"]=>
  float(778)
  ["size_download"]=>
  float(154)
  ["speed_download"]=>
  float(351)
  ["speed_upload"]=>
  float(1776)
  ["download_content_length"]=>
  float(154)
  ["upload_content_length"]=>
  float(778)
  ["starttransfer_time"]=>
  float(0.437844)
  ["redirect_time"]=>
  float(0)
  ["certinfo"]=>
  array(0) {
  }
  ["primary_ip"]=>
  string(14) "***"
  ["primary_port"]=>
  int(443)
  ["local_ip"]=>
  string(12) "***"
  ["local_port"]=>
  int(42880)
  ["redirect_url"]=>
  string(0) ""
}
```

Not sure why I'd be getting a 440 login timeout. I've verified that the login is correct.

**Comment by Zxurian** [comment]
I've also tried adding `'soap_version' => SOAP_1_2,` to ExchangeWebServices.php::1196 `function initializeSoapClient()` based on some googling, but it doesn't get rid of the VersionMismatch error.

**Comment by crash5** [comment]
https://support.microsoft.com/en-us/kb/2629776 ?

**Comment by Zxurian** [comment]
closing this as it ended up being an issue on the sever side. I talked with the admin, and he noticed that IIS was being hosted on port 81 instead of 80, after that, he spent a weekend with it and told me to try again, and it worked, so problem was definitely on Exchange side, unfortunately he failed to tell me what he did to fix it. If he gets back to me, I'll update this for future use.
