### ISSUE TITLE
Encoding: object has no 'SubscriptionIds'

### ISSUE THREAD

**Issue by MagnusVMI** [jamesiarmes/php-ews#278]
Hi,

I trying to set up Streaming Notifications agains our exchange 2013.
No problem to make the Subscription but when trying to run GetStreamingEvents, I got this message:

PHP Fatal error:  Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: object has no 'SubscriptionIds' property in php-ews/ExchangeWebServices.php:836

Code:

$request = new EWSType_GetStreamingEventsType();
$request->ConnectionTimeout = 30;
$request->SubscriptionId = $id;

$response = $ews->GetStreamingEvents($request);

I guess I do something wrong (first project with php-ews) :)

// Magnus

**Comment by jamesiarmes** [comment]
This issue is over a year old. If you are still having issues with the latest code from master, please open a new issue.
