### ISSUE TITLE
Use Daylight

### ISSUE THREAD

**Issue by srkv03** [jamesiarmes/php-ews#279]
Whilst I am booking an event on the calendar the time is correct, but when I try to read the same event, there is an hour difference(due to daylight savings). Any ideas on how to resolve this?(I have read about the SOAP header, which I can't figure out.)

Thanks

**Comment by srkv03** [comment]
Anyone knows how to modify the SOAP header to use DST?

**Comment by JeremyBuchmann** [comment]
If you mean adding the ability to set the [TimeZoneContext](https://msdn.microsoft.com/en-us/library/ee332397(v=exchg.80).aspx) in the SOAP header, then yes, I've done this by adding support for this header to my fork of php-ews, but ended up not using that feature in the end. I ended up just doing everything in UTC.

**Comment by jamesiarmes** [comment]
You can now do this by calling `setTimezone()` on the Client object.
