### ISSUE TITLE
Cannot get it to work, keeps giving empty webpage

### ISSUE THREAD

**Issue by fonteijne** [jamesiarmes/php-ews#283]
Not sure wether this is the right place or not, but I'm not getting any result.
There are no (visible) errors, but no results either.

I copied the entire folder (php-ews) into my root, created an index.php and copied example code from [the Wiki](https://github.com/jamesiarmes/php-ews/wiki/Contact:-Get-List).

But I got no error nor list as response. I am sure I'm doing something wrong, but I'm not sure what it is.

**Comment by Demonslay335** [comment]
Make sure to check your PHP or server logs. Make sure `display_errors` is `On`, etc. There must be a fatal parse error happening. Check your `include`s are pointing to valid files.

**Comment by jamesiarmes** [comment]
Over a year with not response, closing.
