### ISSUE TITLE
I need to get the Global Address List from my Exchange account

### ISSUE THREAD

**Issue by adnaeem** [jamesiarmes/php-ews#284]
How is this possible?

**Comment by jamesiarmes** [comment]
There is no operation in Exchange Web Services to list all mailboxes. If you have a user that has permission to search all mailboxes then you may be able to use the [GetSearchableMailboxes](https://msdn.microsoft.com/en-us/library/jj900497(v=exchg.150).aspx) operation. See http://stackoverflow.com/questions/25970571/get-complete-user-list-in-microsoft-exchange for another possible workaround.
