### ISSUE TITLE
PUBLIC_FOLDERS_ROOT undefined in EWSType/DistinguishedFolderIdNameType.php

### ISSUE THREAD

**Issue by twoeyes2** [jamesiarmes/php-ews#287]
Hi,

It seems that this line:

const PUBLIC_FOLDERS_ROOT = 'publicfoldersroot';

Got merged out by accident in EWSType/DistinguishedFolderIdNameType.php

I'm new to Git... hope this is the right place for posting this.

**Comment by jamesiarmes** [comment]
This has been resolved with 389f9a42dce056f1f84ee7285844a3c0bafccf85.
