### ISSUE TITLE
How do I connect to a shared folder/Mailbox

### ISSUE THREAD

**Issue by brandonwamboldt** [jamesiarmes/php-ews#29]
I can't for the life of me figure out how to get your library working with what I need to do, and was hoping you could help. 

How might I get all the emails in a shared folder/mailbox that I have access to? The folder/mailbox name is "Technical Support".

**Comment by uniqueginun** [comment]
how to do the same thing with shared mailbox? not a folder

**Comment by willbonde** [comment]
@uniqueginun you ever figure that out? same issue here, want a shared mailbox
