### ISSUE TITLE
Unable to Create Calendar Entry Because EWSType_KindType Cannot Load

### ISSUE THREAD

**Issue by ibscas** [jamesiarmes/php-ews#295]
I've been using your example to create a calendar event (https://github.com/jamesiarmes/php-ews/wiki/Calendar:-Create-Event) and have been running into a problem that it errors out at

`$transition->To->Kind = new EWSType_KindType();
$transition->To->Kind->_ = EWSType_KindType::PERIOD;`

I assume there should be a file called KindType.php but there isn't, and even doing a Grep on the entire contents of the source doesn't come up with any hits.  Unfortunately without that I have been unable to find a way to create the event since this is a required element.

**Comment by MrDru** [comment]
Hi ibscas,

try it this way:

```php
$transition->To->Kind = new EWSType_TransitionTargetKindType();
$transition->To->Kind->_ = EWSType_TransitionTargetKindType::PERIOD;
```

Best regards.

**Comment by ibscas** [comment]
Thank you very much, that is what I needed!  Everything worked as expected.  I did get a notice when running it, I'm wondering if it is something to be concerned about or if I need to change something in my code to avoid:

```Notice: Object of class EWSType_OccurrenceType could not be converted to int in /usr/local/www/apache24/data/UDS/sandbox/ews/ExchangeWebServices.php on line 331```

**Comment by MrDru** [comment]
Hi ibscas,

I'm glad that it works for you :smiley:
Regarding the notice, try this one:

```php
$transition->Occurrence = EWSType_OccurrenceType::FIRST_FROM_BEGINNING;
```

Instead of (as described in the example you posted):

```php
$transition->Occurrence = new EWSType_OccurrenceType();
$transition->Occurrence->_ = EWSType_OccurrenceType::FIRST_FROM_BEGINNING;
```

Best regards.

**Comment by ibscas** [comment]
Thanks for the suggestion, but that causes now a warning in addition to the notice:

Warning: Creating default object from empty value in /usr/local/www/apache24/data/UDS/sandbox/event-create.php on line 105
