### ISSUE TITLE
Calendar update working for a single field but not multiples

### ISSUE THREAD

**Issue by ibscas** [jamesiarmes/php-ews#297]
I'm using the example as given at https://github.com/jamesiarmes/php-ews/wiki/Calendar:-Update-Event without any modifications (except to make the date relevant) and what I'm seeing is that if I simply update the subject I can successfully update an appointment, but if I add a second field (in this case the Start, but I've also tried Categories and ReminderIsSet - using their proper URI's) then when you post the request it just hangs indefinitely.

I have also tried reversing things, so I try to post only the Start date with no subject and that works fine, but the two together do not.  I do have all PHP errors enabled and I get them as expected but this doesn't display any type of message, it simply hangs up.

I'm sure it works fine generally but perhaps the example is missing something?

**Comment by MrDru** [comment]
Hi ibscas,

the following example should work:

```php
$ews = new ExchangeWebServices($host, $username, $password, $version);

$request = new EWSType_UpdateItemType();
$request->ConflictResolution = EWSType_ConflictResolutionType::ALWAYS_OVERWRITE;
$request->SendMeetingInvitationsOrCancellations = EWSType_CalendarItemUpdateOperationType::SEND_ONLY_TO_ALL;

$change = new EWSType_ItemChangeType();
$change->ItemId = new EWSType_ItemIdType();
$change->ItemId->Id = $event_id;
$change->ItemId->ChangeKey = $event_change_key;

$change->Updates = new EWSType_NonEmptyArrayOfItemChangeDescriptionsType();

$field = new EWSType_SetItemFieldType();
$field->FieldURI = new EWSType_PathToUnindexedFieldType();
$field->FieldURI->FieldURI = EWSType_UnindexedFieldURIType::ITEM_SUBJECT;
$field->CalendarItem = new EWSType_CalendarItemType();
$field->CalendarItem->Subject = 'New Subject';

$change->Updates->SetItemField[] = $field;

$field = new EWSType_SetItemFieldType();
$field->FieldURI = new EWSType_PathToUnindexedFieldType();
$field->FieldURI->FieldURI = EWSType_UnindexedFieldURIType::CALENDAR_START;
$field->CalendarItem = new EWSType_CalendarItemType();
$field->CalendarItem->Start = '2013-09-12T05:00:00Z';

$change->Updates->SetItemField[] = $field;

$request->ItemChanges[] = $change;

$response = $ews->UpdateItem($request);
```

Best regards.

**Comment by ibscas** [comment]
MrDru,

Thank you for replying :).  The behavior is identical (updating a single field works, updating more than one field hangs).  I'm not sure if it's helpful, but here is a var dump of my request.

    EWSType_UpdateItemType Object
    (
        [ConflictResolution] => AlwaysOverwrite
        [ItemChanges] => Array
            (
                [0] => EWSType_ItemChangeType Object
                    (
                        [ItemId] => EWSType_ItemIdType Object
                            (
                                [ChangeKey] => DwAAABYAAABF/xn/OxZcT6oh9Robt1pEAABIzRIA
                                [Id] => AAMkAGEyOTcxNjU2LTEyMTItNDE2ZS1iOTcwLWIwNjFlYzU3MjIzMgBGAAAAAABtNcAORqRvRKo2HV8y88F1BwBF/xn/OxZcT6oh9Robt1pEAAAA4pi/AABF/xn/OxZcT6oh9Robt1pEAABIw6qFAAA=
                            )
    
                        [OccurrenceItemId] => 
                        [RecurringMasterItemId] => 
                        [Updates] => EWSType_NonEmptyArrayOfItemChangeDescriptionsType Object
                            (
                                [AppendToItemField] => 
                                [DeleteItemField] => 
                                [SetItemField] => Array
                                    (
                                        [0] => EWSType_SetItemFieldType Object
                                            (
                                                [CalendarItem] => EWSType_CalendarItemType Object
                                                    (
                                                        [AdjacentMeetingCount] => 
                                                        [AdjacentMeetings] => 
                                                        [AllowNewTimeProposal] => 
                                                        [AppointmentReplyTime] => 
                                                        [AppointmentSequenceNumber] => 
                                                        [AppointmentState] => 
                                                        [Attachments] => 
                                                        [Body] => 
                                                        [CalendarItemType] => 
                                                        [Categories] => 
                                                        [ConferenceType] => 
                                                        [ConflictingMeetingCount] => 
                                                        [ConflictingMeetings] => 
                                                        [ConversationId] => 
                                                        [Culture] => 
                                                        [DateTimeCreated] => 
                                                        [DateTimeReceived] => 
                                                        [DateTimeSent] => 
                                                        [DateTimeStamp] => 
                                                        [DeletedOccurrences] => 
                                                        [DisplayCc] => 
                                                        [DisplayTo] => 
                                                        [Duration] => 
                                                        [EffectiveRights] => 
                                                        [End] => 
                                                        [EndTimeZone] => 
                                                        [ExtendedProperty] => 
                                                        [FirstOccurrence] => 
                                                        [HasAttachments] => 
                                                        [Importance] => 
                                                        [InReplyTo] => 
                                                        [InternetMessageHeaders] => 
                                                        [IsAllDayEvent] => 
                                                        [IsAssociated] => 
                                                        [IsCancelled] => 
                                                        [IsDraft] => 
                                                        [IsFromMe] => 
                                                        [IsMeeting] => 
                                                        [IsOnlineMeeting] => 
                                                        [IsRecurring] => 
                                                        [IsResend] => 
                                                        [IsResponseRequested] => 
                                                        [IsSubmitted] => 
                                                        [IsUnmodified] => 
                                                        [ItemClass] => 
                                                        [ItemId] => 
                                                        [LastModifiedName] => 
                                                        [LastModifiedTime] => 
                                                        [LastOccurrence] => 
                                                        [LegacyFreeBusyStatus] => 
                                                        [Location] => 
                                                        [MeetingRequestWasSent] => 
                                                        [MeetingTimeZone] => 
                                                        [MeetingWorkspaceUrl] => 
                                                        [MimeContent] => 
                                                        [ModifiedOccurrences] => 
                                                        [MyResponseType] => 
                                                        [NetShowUrl] => 
                                                        [OptionalAttendees] => 
                                                        [Organizer] => 
                                                        [OriginalStart] => 
                                                        [ParentFolderId] => 
                                                        [Recurrence] => 
                                                        [RecurrenceId] => 
                                                        [ReminderDueBy] => 
                                                        [ReminderIsSet] => 
                                                        [ReminderMinutesBeforeStart] => 
                                                        [RequiredAttendees] => 
                                                        [ResponseObjects] => 
                                                        [Resources] => 
                                                        [Sensitivity] => 
                                                        [Size] => 
                                                        [Start] => 
                                                        [StartTimeZone] => 
                                                        [Subject] => New Subject
                                                        [TimeZone] => 
                                                        [UID] => 
                                                        [UniqueBody] => 
                                                        [WebClientEditFormQueryString] => 
                                                        [WebClientReadFormQueryString] => 
                                                        [When] => 
                                                        [ReceivedBy] => 
                                                        [ReceivedRepresenting] => 
                                                    )
    
                                                [Contact] => 
                                                [DistributionList] => 
                                                [ExtendedFieldURI] => 
                                                [FieldURI] => EWSType_PathToUnindexedFieldType Object
                                                    (
                                                        [FieldURI] => item:Subject
                                                    )
    
                                                [IndexedFieldURI] => 
                                                [Item] => 
                                                [MeetingCancellation] => 
                                                [MeetingMessage] => 
                                                [MeetingRequest] => 
                                                [MeetingResponse] => 
                                                [Message] => 
                                                [Task] => 
                                            )
    
                                        [1] => EWSType_SetItemFieldType Object
                                            (
                                                [CalendarItem] => EWSType_CalendarItemType Object
                                                    (
                                                        [AdjacentMeetingCount] => 
                                                        [AdjacentMeetings] => 
                                                        [AllowNewTimeProposal] => 
                                                        [AppointmentReplyTime] => 
                                                        [AppointmentSequenceNumber] => 
                                                        [AppointmentState] => 
                                                        [Attachments] => 
                                                        [Body] => 
                                                        [CalendarItemType] => 
                                                        [Categories] => 
                                                        [ConferenceType] => 
                                                        [ConflictingMeetingCount] => 
                                                        [ConflictingMeetings] => 
                                                        [ConversationId] => 
                                                        [Culture] => 
                                                        [DateTimeCreated] => 
                                                        [DateTimeReceived] => 
                                                        [DateTimeSent] => 
                                                        [DateTimeStamp] => 
                                                        [DeletedOccurrences] => 
                                                        [DisplayCc] => 
                                                        [DisplayTo] => 
                                                        [Duration] => 
                                                        [EffectiveRights] => 
                                                        [End] => 
                                                        [EndTimeZone] => 
                                                        [ExtendedProperty] => 
                                                        [FirstOccurrence] => 
                                                        [HasAttachments] => 
                                                        [Importance] => 
                                                        [InReplyTo] => 
                                                        [InternetMessageHeaders] => 
                                                        [IsAllDayEvent] => 
                                                        [IsAssociated] => 
                                                        [IsCancelled] => 
                                                        [IsDraft] => 
                                                        [IsFromMe] => 
                                                        [IsMeeting] => 
                                                        [IsOnlineMeeting] => 
                                                        [IsRecurring] => 
                                                        [IsResend] => 
                                                        [IsResponseRequested] => 
                                                        [IsSubmitted] => 
                                                        [IsUnmodified] => 
                                                        [ItemClass] => 
                                                        [ItemId] => 
                                                        [LastModifiedName] => 
                                                        [LastModifiedTime] => 
                                                        [LastOccurrence] => 
                                                        [LegacyFreeBusyStatus] => 
                                                        [Location] => 
                                                        [MeetingRequestWasSent] => 
                                                        [MeetingTimeZone] => 
                                                        [MeetingWorkspaceUrl] => 
                                                        [MimeContent] => 
                                                        [ModifiedOccurrences] => 
                                                        [MyResponseType] => 
                                                        [NetShowUrl] => 
                                                        [OptionalAttendees] => 
                                                        [Organizer] => 
                                                        [OriginalStart] => 
                                                        [ParentFolderId] => 
                                                        [Recurrence] => 
                                                        [RecurrenceId] => 
                                                        [ReminderDueBy] => 
                                                        [ReminderIsSet] => 
                                                        [ReminderMinutesBeforeStart] => 
                                                        [RequiredAttendees] => 
                                                        [ResponseObjects] => 
                                                        [Resources] => 
                                                        [Sensitivity] => 
                                                        [Size] => 
                                                        [Start] => 2015-10-06T05:00:00Z
                                                        [StartTimeZone] => 
                                                        [Subject] => 
                                                        [TimeZone] => 
                                                        [UID] => 
                                                        [UniqueBody] => 
                                                        [WebClientEditFormQueryString] => 
                                                        [WebClientReadFormQueryString] => 
                                                        [When] => 
                                                        [ReceivedBy] => 
                                                        [ReceivedRepresenting] => 
                                                    )
    
                                                [Contact] => 
                                                [DistributionList] => 
                                                [ExtendedFieldURI] => 
                                                [FieldURI] => EWSType_PathToUnindexedFieldType Object
                                                    (
                                                        [FieldURI] => calendar:Start
                                                    )
    
                                                [IndexedFieldURI] => 
                                                [Item] => 
                                                [MeetingCancellation] => 
                                                [MeetingMessage] => 
                                                [MeetingRequest] => 
                                                [MeetingResponse] => 
                                                [Message] => 
                                                [Task] => 
                                            )
    
                                    )
    
                            )
    
                    )
    
            )
    
        [MessageDisposition] => 
        [SavedItemFolderId] => 
        [SendMeetingInvitationsOrCancellations] => SendOnlyToAll
        [SuppressReadReceipts] => 
    )

**Comment by ibscas** [comment]
I have actually found an interesting pattern in this.  This "hanging" issue seems to pop up frequently in my testing.  Another example I have of this is getting a list of events (https://github.com/jamesiarmes/php-ews/wiki/Calendar:-Get-List-(Retrieving-Id-and-ChangeKey)).  I found that if I request additional properties that it always fails when I put a 4th property in.  I discovered this when I tried to add Categories to the list and it hung up, but Categories by itself worked just fine.  I played around with this and found that no matter what, if I put a 4th element into the array then I get the hang up, but if I keep it to 3 then everything works fine.

**Comment by MrDru** [comment]
Hi ibscas,

it's really good to know the problem with 4 (or more) `AdditionalProperties`. Thank you for sharing your experience! :thumbsup:

The properties you ask for you can also get this way (without `AdditionalProperties`):

```php
$request->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;
```

Alternatively you can request only the *default* properties, if those information satisfy your needs:

```php
$request->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::DEFAULT_PROPERTIES;
```

**Hint:** Since recent past I observed that not all *empty* elements are available in the response (at least for Office365). Example: If I request the properties of an contact and `LastName` is *not* set, the `$response` does *not* contain the element `LastName`.

Hope this helps.

**Comment by ibscas** [comment]
MrDru, actually the reason I had added the additional properties is that ALL_PROPERTIES and DEFAULT_PROPERTIES both omit the fields I was adding with additional fields.  Or at least on my Exchange 2010 they do.

I too have noticed that empty elements will not populate.  For instance, when I pull categories in the above example, the server will not return a blank Categories element, it will simply omit it from the results entirely.  I use

    if (property_exists($event->CalendarItem, 'Categories'))

To resolve that issue.

On the 'hang' issue, I'm still not sure why the sample code as well as your amended sample in your reply to me both hang on a 2nd issue.  Like I mentioned about the 4 field issue, it seems identical but for 2+ fields instead of 4+.
