### ISSUE TITLE
Missing EmailAddress.php in autoload

### ISSUE THREAD

**Issue by mikemcmurray** [jamesiarmes/php-ews#299]
Just trying the "Calendar: Retrieve FreeBusyResponse" example from the wiki and the autoload looks to try and run "require_once" for a file "EmailAddress.php" - problem is the letter doesn't exist in the EWSType folder.

**Comment by timvandesteeg** [comment]
I'm pretty sure it should be EWSType_EmailAddressType

Also, 'Address' is now 'EmailAddress'.

**Comment by jamesiarmes** [comment]
This has been resolved on master.
