### ISSUE TITLE
php-ews

### ISSUE THREAD

**Issue by Nirzol** [jamesiarmes/php-ews#301]
Hi ! 

I wonder if I have to use php-ews from packagist or from here ?

I saw that : https://github.com/jamesiarmes/php-ews/issues/253

What news  now ?

**Comment by Garethp** [comment]
@Nirzol this project isn't PSR-4 compliant, and it doesn't look like it will be any time soon. There are forks that exist that are, maybe they have packagist registrations.

On that note, I have my own fork located at https://github.com/Garethp/php-ews and registered under `garethp/php-ews` if you want to take a look

**Comment by Nirzol** [comment]
Ok thanks. And what about that ? https://packagist.org/packages/php-ews/php-ews

**Comment by Garethp** [comment]
That package is for this github project, which won't be autoloaded. I'd suggest not using that one.

**Comment by Nirzol** [comment]
Thanks Garethp ! Does your fork support Ex 2013 or more ?

**Comment by Garethp** [comment]
It'll work with Exchange 2013, but I haven't added any features specific to Exchange 2013. I'm also working on support for Exchange Online, but that's going slowly

**Comment by mikaelcom** [comment]
@Garethp maybe you can take a look to [PackageEws365](https://github.com/WsdlToPhp/PackageEws365)

**Comment by Garethp** [comment]
@mikaelcom The main thing that's impeding me is that I built in support for Token based OAuth. Unfortunately, as far as I know the EWS permissions only exist in a paid subscription of Office 365, which I don't have an for some reason I can't sign up for the free trial. Theoretically it works, but I haven't done any serious testing against it. Once I have an account in the next coming months I'll be able to test more. Thanks for the link though
