### ISSUE TITLE
long loading time

### ISSUE THREAD

**Issue by Geoffry304** [jamesiarmes/php-ews#303]
Hey, 

Is it normal when I want to load +-30 calendar items in 1 month that it takes +-30 seconds too load this? This is really long in a web appilication.

Regards,

Geoffry

**Comment by Garethp** [comment]
I wouldn't say that's normal, though it would depend on the speed and reliability of the connection between the application and the mail server

**Comment by Geoffry304** [comment]
well the server's are connected to eachother so I don't know how I can speed up things. Do you have an idea, I can give you my code, but I preffer not giving it in public

**Comment by Garethp** [comment]
I can take a look, but to be honest I don't know much about this repository of code any more. I forked it a while back in to [`garethp/php-ews`](https://github.com/Garethp/php-ews) for usability. That being said, I can take a look at tell you if I can spot anything

**Comment by Geoffry304** [comment]
Well could you give me an email adres where i can talk with you? I already looked at your code but have some questions about it. 

Mvg
Geoffry Van den Eede

**Comment by Garethp** [comment]
Sure, email me at blackfireweb@gmail.com

**Comment by jamesiarmes** [comment]
This issue is over a year old. If you are still having this issue on the latest code in master please open a new issue.
