### ISSUE TITLE
How I accept meeting

### ISSUE THREAD

**Issue by sjscosta1981** [jamesiarmes/php-ews#304]
Someone invite me for a meeting and I want to accept the meeting.
How I send that information for the exchange server?

Thanks

**Comment by Garethp** [comment]
The documentation you want to look for is located [here](https://msdn.microsoft.com/en-us/library/office/dd633648(v=exchg.80).aspx). About half way down the page it shows the XML payload that needs to be sent to the Exchange Server, so you want to create that XML Payload through the library. Essentially, the XML you need to send looks something like

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" 
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" 
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Header>
      <t:RequestServerVersion Version="Exchange2010" />
   </soap:Header>
   <soap:Body>
      <m:CreateItem MessageDisposition="SendOnly">
         <m:Items>
            <t:AcceptItem>
               <t:Sensitivity>Private</t:Sensitivity>
               <t:Body BodyType="Text">I have another meeting immediately preceding this one, so I may arrive a few minutes late.</t:Body>
               <t:ReferenceItemId Id="AQMkA" ChangeKey="DwAAA" />
            </t:AcceptItem>
         </m:Items>
      </m:CreateItem>
   </soap:Body>
</soap:Envelope>
```

I'm not 100% sure how you'd achieve this using the current ews library here, but I can give you an example using my fork [`garethp/php-ews`](https://github.com/Garethp/php-ews). It would look something like this

```php
use jamesiarmes\PEWS\API;

$api = new API();
$api->buildClient($server, $username, $password);
$api->createItems(array(
   'AcceptItem' => array(
       'Sensitivity' => 'Private',
       'Body' => 'I have another meeting immediately preceding this one, so I may arrive a few minutes late.',
       'ReferenceItemId' => array(
           'Id' => $itemId,
           'ChangeKey' => $changeKey
       )
   )
));
```

That code might not work exactly even with my fork, but it's an example of how you'd create the XML in mine

**Comment by sjscosta1981** [comment]
Thank you very much...
That works  :+1:

**Comment by monkeyphysics** [comment]
@Garethp, that's helping me a great deal in the right direction.

I'm on your fork, and trying to accept a meeting with:
```php
$api->createItems(array(
	'AcceptItem' => array(
		'Sensitivity' => 'Private',
		'ReferenceItemId' => array(
			'Id' => $item->getItemId()->getId(),
			'ChangeKey' => $item->getItemId()->getChangeKey(),
			)
		)
));
```
However, this is throwing me the following exception:
`MessageDisposition attribute is required.`

Any idea how to fix this?

**Comment by Garethp** [comment]
Hi @monkeyphysics 

Looks like my code was a little bit off as I forgot to put in the MessageDisposition. If you take a look at the XML required to be sent, we do need the `MessageDisposition="SendOnly"` as part of it. The first parameter of createItems() is the item to be created, but there's a second option parameter that will let you pass in an array to be merged with the request. It's used for things like this. Try the following

```php
$api->createItems(array(
    'AcceptItem' => array(
        'Sensitivity' => 'Private',
        'ReferenceItemId' => array(
            'Id' => $item->getItemId()->getId(),
            'ChangeKey' => $item->getItemId()->getChangeKey(),
            )
        )
), array('MessageDisposition' => 'SendOnly'));
```

**Comment by monkeyphysics** [comment]
You're a hero. Thanks a lot for your response! Works like a charm, and you've just saved me a lot of time digging through the library figuring out how to set the attribute.

**Comment by Garethp** [comment]
No problem. For most of my methods, there should be a parameter called `$options` that's optional. It should be available on all methods, but if it's not let me know. When it's there it's merged directly in to the request like so `$request = array_replace_recursive($request, $options);`, so it's a good way to modify the request as needed, or to override any defaults I have in place. For example, the `createItems()` function looks like this

```php
    /**
     * Create items through the API client
     *
     * @param $items
     * @param array $options
     * @return API\CreateItemResponseType
     */
    public function createItems($items, $options = array())
    {
        if (!is_array($items)) {
            $items = array($items);
        }

        $request = array(
            'Items' => $items
        );

        $request = array_replace_recursive($request, $options);
        $request = Type::buildFromArray($request);

        $response = $this->getClient()->CreateItem($request);

        return $response;
    }
```

If you *do* have need to do things that my library doesn't make easy, you can manually build your requests in much the same way. `$api->getClient()->YourSoapFunctionHere($request);` will automatically resolve to the soap function you need, and Type::buildFromArray() will try to, well, build an object that the SOAP client can convert to XML from any array you pass in to it.

Just in case you want to do things with my library that I haven't implemented

**Comment by monkeyphysics** [comment]
Awesome! Thanks for the great library/fork.

**Comment by Garethp** [comment]
If you come across anything that confuses you or have any questions, feel free to leave an issue on my repo. I try to check my notifications at least a couple times a week, if not once a day

**Comment by scrivna** [comment]
Hi @jamesiarmes - I know you've just closed this but I'm trying to achieve this without resorting to using a separate library, can php-ews send custom requests and can it bundle multiple requests in to one SOAP call? I have say 10 attendees and ideally I don't want to send 11 requests to exchange.

**Comment by jamesiarmes** [comment]
I don't know what you mean by custom requests, but you can create multiple items in a singe request. However, each item will be created as the current user, as such, I don't know that you can respond to meeting requests sent to multiple people. It may be possible if the current user has delegate permissions over those users, but I don't have access to an Exchange server with that setup. This would be a limitation of Microsoft Exchange and SOAP, not this library.

**Comment by scrivna** [comment]
Thanks for getting back, you're right that because we aren't able to specify who we're responding on behalf of, even though we have impersonation rights we aren't able to group these together. Thanks for your input, and thanks for the library, it's a great resource.
