### ISSUE TITLE
Retrieving attachments from forwarded message with embedded attachment

### ISSUE THREAD

**Issue by mtfi-lorenzo** [jamesiarmes/php-ews#305]
I truly appreciate this library and it has helped tremendously.  The only issue I cannot resolve is extracting attachments from an e-mail message containing the attachments.  

This occurs when a user creates a new e-mail message and drags the original message (containing the attachment I need) into it.  I can see the properties of the e-mail is not "FileAttachment", but instead "ItemAttachment".  I have tried modifying the example code from the Wiki article "Retrieve-All-Email-Attachments", but only get an error about a missing Id.

Any suggestions on how to access the attachments from the attached Item?

Partial var dump from an example message:

object(stdClass)#149 (43) {
  ["ItemId"]=>
  object(stdClass)#150 (2) {
    ["Id"]=>
    string(152) "AAMkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NABGAAAAAABp+AqPUrsDS5mJYBbgT8cMBwDr14N485PESKioLJfn3CaYAAAARQJbAAA5L/2MVrY6T4ykUiXThzPwAACzGsQ/AAA="
    ["ChangeKey"]=>
    string(40) "CQAAABQAAAA/GBXkNTwXSpbEb55G2IRYAATPRA=="
  }
  ["ParentFolderId"]=>
  object(stdClass)#151 (2) {
    ["Id"]=>
    string(120) "AAMkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NAAuAAAAAABp+AqPUrsDS5mJYBbgT8cMAQDr14N485PESKioLJfn3CaYAAAARQJbAAA="
    ["ChangeKey"]=>
    string(8) "AQAAAA=="
  }
  ["ItemClass"]=>
  string(8) "IPM.Note"
  ["Subject"]=>
  string(76) "Original E-mail with message attached"
  ["Sensitivity"]=>
  string(6) "Normal"
  ["Body"]=>
  object(stdClass)#152 (2) {
    ["_"]=>
    string(0) ""
    ["BodyType"]=>
    string(4) "Text"
  }
  ["Attachments"]=>
  object(stdClass)#153 (1) {
    ["ItemAttachment"]=>
    object(stdClass)#154 (5) {
      ["AttachmentId"]=>
      object(stdClass)#155 (1) {
        ["Id"]=>
        string(180) "AAMkADNmMTFkZWMzLWZmZTItNGYzZC1hMzY0LTM1ZmVlOTgyMGY3NABGAAAAAABp+AqPUrsDS5mJYBbgT8cMBwDr14N485PESKioLJfn3CaYAAAARQJbAAA5L/2MVrY6T4ykUiXThzPwAACzGsQ/AAABEgAQAPejnEoDj9NPjr66WJDpifc="
      }
      ["Name"]=>
      string(14) "TestEMail with Attachment"
      ["Size"]=>
      int(131514)
      ["LastModifiedTime"]=>
      string(19) "2015-11-13T13:59:17"
      ["IsInline"]=>
      bool(false)
    }
  }
  ["DateTimeReceived"]=>
  string(20) "2015-11-13T13:59:19Z"
  ["Size"]=>
  int(139250)
  ["Importance"]=>
  string(6) "Normal"
  ["IsSubmitted"]=>
  bool(false)
  ["IsDraft"]=>
  bool(false)
  ["IsFromMe"]=>
  bool(false)
  ["IsResend"]=>
  bool(false)

**Comment by Garethp** [comment]
Can you show us the modified code that you're trying to use that gives you the error about missing ids? Also, if you have the resources and aren't too deep in, I'd suggest seeing if you can use my fork of php-ews, [`garethp/php-ews`](https://github.com/Garethp/php-ews), you should find it easier to use and actually maintained. I can also give you more assistance if you use that one as opposed to this one

**Comment by mtfi-lorenzo** [comment]
Garethp, I cloned your fork this morning.  I will post the results on your Issues.  Thanks for your time to look at it.
