### ISSUE TITLE
php-ews and Ex2016

### ISSUE THREAD

**Issue by wgreipl** [jamesiarmes/php-ews#306]
If an Exchange 2016 supported?

**Comment by mikaelcom** [comment]
Could you try with [PackageEws365](https://github.com/WsdlToPhp/PackageEws365)?
Thanks

**Comment by Garethp** [comment]
This library *should* still work with Exchange 2016, but it's not being actively maintained so you won't get any new features or support. But I've got a fork of this project at [`garethp/php-ews`](https://github.com/Garethp/php-ews) that is supported. While I don't have a 2016 server, I'd be happy to help build in extra support for it once I can get a test account for Ex2016

**Comment by doit-itservice** [comment]
jamesiarmes/php-ews works with Ex2013 and Ex2016 RTM. 
But with Ex2016 CU2 (or CU1 - not tested...) SyncFolderItems will returned nothing :-(
Any patch for this? Won't switch to another library.

```
$ews = new ExchangeWebServices($ews_server, $ews_username, $ews_password, $ews_version);
$request = new EWSType_SyncFolderItemsType;
$request->SyncState = null;
$request->MaxChangesReturned = 512;  
$request->ItemShape = new EWSType_ItemResponseShapeType;
$request->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;

$request->SyncFolderId = new EWSType_NonEmptyArrayOfBaseFolderIdsType;
$request->SyncFolderId->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType;
$request->SyncFolderId->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;
  
$request->SyncFolderId->DistinguishedFolderId->Mailbox = new StdClass;
$request->SyncFolderId->DistinguishedFolderId->Mailbox->EmailAddress = "user01@dex2016.local"; 

$response = $ews->SyncFolderItems($request);
var_dump($response);
```

**Comment by doit-itservice** [comment]
Use Exchange2013 instead of Exchange2016 for `$ews_version`

**Comment by talalong** [comment]
Can Exchange 2016 be supported jet?

**Comment by doit-itservice** [comment]
In my case (create/update/delete CalendarItems) yes! But I have to set $ews_version to "Exchange2013", when I use a Ex2016 with CU2 or newer

**Comment by talalong** [comment]
Great! Thanks for your answer. I might need them too.

**Comment by jamesiarmes** [comment]
The latest version on master includes a version constant for Exchange 2016. The documentation is limited compared to 2007-2013, so I can't guarantee that all new properties defined in 2016 have been introduced are present.

**Comment by talalong** [comment]
Okay, Thank you. I just want to get access to exchage in order to get, set and update events from calendar like @doit-itservice did.

**Comment by joadha** [comment]
For what it's worth, I'm able to use php-ews against Exchange 2016 for all of my needs: Autodiscover, calendar reads, and create/update/delete on events. Since I use Autodiscover, I would assume the new constant is being employed.

**Comment by jamesiarmes** [comment]
@joadha If you're using an updated version of this library (i.e. since November 15), that would be correct!
