### ISSUE TITLE
 Uncaught exception 'EWS_Exception' with message 'SOAP client returned status of 401

### ISSUE THREAD

**Issue by daveryaaziem** [jamesiarmes/php-ews#309]
for some reason, if I manually set the password (ie $password = "myPassword") everything works fine.
However if the password is set from a post (ie $password = $_POST['password']) I get this error:

 Uncaught exception 'EWS_Exception' with message 'SOAP client returned status of 401

I cannot for the life of me figure out why this is. The funny thing is that I have the username set the same way (ie $username = $_POST['username']) and it works with no problem. It just doesnt work for password. I bet is a simple mistake on my end, but I just cant figure it out. Any ideas?

**Comment by fullmetaljacket** [comment]
Make sure there's not extra space getting sent from $_POST by using trim(). Have you echoed out the POST password variable to make sure it looks correct?
