### ISSUE TITLE
Update OptionalAttendees

### ISSUE THREAD

**Issue by ipurum** [jamesiarmes/php-ews#311]
Hello!
I have a problem with update calendar item.I need to sent invintations and cancellations only to new users or only to users who deleted event.
I set parameters:
        $request->ConflictResolution = 'AlwaysOverwrite';
        $request->SendMeetingInvitationsOrCancellations = 'SendOnlyToChanged';
But Exchange send messages to all attendees if one new attende was added. 

How I can fix this? Why Exchange send this messages? Is it depends on the order of attendees?

**Comment by Garethp** [comment]
"SendOnlyToChanged" means send to all people who are effected by the change. Anyone who's currently attending will be affected by a new person attending. There's no option to send only to the new attendee

**Comment by ipurum** [comment]
Is there posibility to sent invintation or cancelletion to specific user? May by defined by users email.

**Comment by Flameur** [comment]
+1

**Comment by Garethp** [comment]
Not that I'm aware of, no
