### ISSUE TITLE
long subject + body results in an error (mail)

### ISSUE THREAD

**Issue by M-K-ay** [jamesiarmes/php-ews#312]
Greetings!

I encouter a weird problem. 
When my subject + body reach a certain length, the program breaks with following error: Uncaught SoapFault exception: [Client] looks like we got no XML document

This wouldn't be a big problem but it occurs already at 168 characters.

What I've tested so far:
Subject 6 chars + body 161 chars -> Mail is correct
Subject 6 chars + body 162 chars -> Error
Subject 5 chars + body 162 chars -> Mail is correct

Mails and events are working fine but just as said, errors occur when there are too many characters.

Here is my code:

```
$ews = new ExchangeWebServices($server, $username, $password, ExchangeWebServices::VERSION_2010_SP2);
$msg = new EWSType_MessageType();

$fromAddress = new EWSType_EmailAddressType();
$fromAddress->EmailAddress = 'some@mail.domain';
$fromAddress->Name = 'some name';
$msg->From = new EWSType_SingleRecipientType();
$msg->From->Mailbox = $fromAddress;

$msg->Subject = "123456";

$msg->Body = new EWSType_BodyType();
$msg->Body->BodyType = 'HTML';
$msg->Body->_ = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At ve";

$msgRequest = new EWSType_CreateItemType();
$msgRequest->Items = new EWSType_NonEmptyArrayOfAllItemsType();
$msgRequest->MessageDisposition = 'SendAndSaveCopy';
$msgRequest->MessageDispositionSpecified = true;

$msg->ToRecipients = new EWSType_ArrayOfRecipientsType();
$toAddress = new EWSType_EmailAddressType();
$toAddress->Name = "some name";
$toAddress->EmailAddress = 'someone-else@mail.domain';
$msg->ToRecipients->Mailbox = $toAddress;
$msgRequest->Items->Message = $msg;
$response = $ews->CreateItem($msgRequest);
```

Server is Exchange 2013, tried VERSION_2010_SP1 also, but didn't help.
Setting the type to Text

```
$msg->Body->BodyType = 'Text';
```

did no change either.

Tried with these Environments:
Apache 2.2.25 + PHP 5.2.17
and
Apache 2.4.12 + PHP 5.5.25
Both fail identical.

Any suggestions?

Edit:::I did further investigations
Sending the long body as an event is successful.
I tried the PHP mail() function via SMTP and received the mail as given.

So I assume sending a message with a long body via this API is the problem - maybe programming mistake?
Does anyone have experience with long message bodies via this API?

**Comment by caglaror** [comment]
I have experienced the same problem, looking for any suggestion.

**Comment by jamesiarmes** [comment]
I've added a new [message/create](https://github.com/jamesiarmes/php-ews/blob/master/examples/message/create.php) example that uses a much longer body and subject and the message is created just fine. There have been a number of changes to this library since this was reported, so it's possible that updating to the latest commit may resolve your issue.
