### ISSUE TITLE
How to get $UID from CalendarItemType?

### ISSUE THREAD

**Issue by piotrevic** [jamesiarmes/php-ews#314]
Hi.
I'm not really sure if UID is the thing I'm looking for, but I want to get it to figure it out. GetItem() nor FindItem() doesn't return it. 
I need to recognize an event in different users' calendars, but regular ID is different for the same event for different users, and furthermore event changes id when it's moved to trash.

**Comment by Garethp** [comment]
It seems the CalendarItemType class does have a uID attribute, would that be it?

**Comment by guerriky** [comment]
Hi,
sorry, but I didn't quite get what your situation is.
I you need to get the UID, you can find the documentation here:
[UID](https://msdn.microsoft.com/EN-US/library/office/bb891878%28v=exchg.150%29.aspx)

Your php-ews code would look something like this:

    $request = new EWSType_GetItemType();
    $itemProperties = new EWSType_ItemResponseShapeType();
    $itemProperties->BodyType = 'Text';
    // Tells the server to return only ids plus the following properties
    $itemProperties->BaseShape = EWSType_DefaultShapeNamesType::ID_ONLY;
    $props = array();
    $p = new EWSType_PathToUnindexedFieldType();
    $p->FieldURI = 'item:Subject';
    $props[] = $p;
    $p = new EWSType_PathToUnindexedFieldType();
    $p->FieldURI = 'calendar:Start';
    $props[] = $p;
    $p = new EWSType_PathToUnindexedFieldType();
    $p->FieldURI = 'calendar:End';
    $props[] = $p;
    $p = new EWSType_PathToUnindexedFieldType();
    $p->FieldURI = 'calendar:Location';
    // Yep. This is what you're looking for
    // If this doesn't work, try changinc calendar for item, like in the subject field
    $p = new EWSType_PathToUnindexedFieldType();
    $p->FieldURI = 'calendar:UID';
    $props[] = $p;

    $itemProperties->AdditionalProperties->FieldURI = $props;
    $request->ItemShape = $itemProperties;

    $item_id = new EWSType_ItemIdType();
    $item_id->Id = $id;
    $request->ItemIds->ItemId = $item_id;
    // That sould do it
    $response = $this->ews->GetItem($request);

If that doesn't work (I wrote it quick), try EWSType_PathToIndexedFieldType(), or try changing the calendar: prefix to item: .

Hope this helps.
Bye,
Riccardo

**Comment by piotrevic** [comment]
Your code looks fine, I added two "`... = new...`" lines when getting empty value error, but then I get "wrong Exchange version" and I realized I didn't pass anything as version in ExchangeWebServices() because version is optional. I just added "'Exchange2010_SP2" as the forth argument and now `FindItem()` returns UID without additional work. Your code helps me realize that, thank guerriky!
