### ISSUE TITLE
create calendar event with one or more attendees

### ISSUE THREAD

**Issue by erickengelke** [jamesiarmes/php-ews#316]
I found many examples that create calendar events for oneself, and they all work immediately.  But if
I try to add even one attendee, the request fails to return.  Here is the code I tried to use to add recipients... where am I going wrong?
`  $request->Items->CalendarItem->RequiredAttendees =
            new EWSType_NonEmptyArrayOfAttendeesType();
  $request->Items->CalendarItem->RequiredAttendees->Attendee = array();

  $n = 0;
  $request->Items->CalendarItem->RequiredAttendees->Attendee[$n] 
           = new  EWSType_SingleRecipientType();

  $request->Items->CalendarItem->RequiredAttendees->Attendee[$n]->Mailbox 
            = new EWSType_EmailAddressType();

  $request->Items->CalendarItem->RequiredAttendees->Attendee[$n]->Mailbox->EmailAddress 
            = $foruser;

  $request->Items->CalendarItem->RequiredAttendees->Attendee[$n]->Mailbox->RoutingType  
            = 'SMTP';
  $request->Items->CalendarItem->RequiredAttendees->Attendee[$n]->Name = $foruser;
 `
The accounts I am trying to invite, I have full power over their Exchange calendars, so I should have privileges,... I think.

**Comment by jamesiarmes** [comment]
Updating to the latest version of this library may resolve your issue. I was able to create an event with multiple attendees using the following:

```php
use \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Request\CreateItemType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfAllItemsType;
use \jamesiarmes\PhpEws\Type\CalendarItemType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfAttendeesType;
use \jamesiarmes\PhpEws\Type\AttendeeType;
use \jamesiarmes\PhpEws\Type\EmailAddressType;
use \jamesiarmes\PhpEws\Enumeration\RoutingType;
use \jamesiarmes\PhpEws\Enumeration\CalendarItemCreateOrDeleteOperationType;

$client = new Client($host, $username, $password, $version);

$request = new CreateItemType();
$request->SendMeetingInvitations = new CalendarItemCreateOrDeleteOperationType();
$request->SendMeetingInvitations->_ = CalendarItemCreateOrDeleteOperationType::SEND_ONLY_TO_ALL;
$request->Items = new NonEmptyArrayOfAllItemsType();
$request->Items->CalendarItem = array();

$event = new CalendarItemType();
$event->RequiredAttendees = new NonEmptyArrayOfAttendeesType();
$event->RequiredAttendees->Attendee = array();

$attendee = new AttendeeType();
$attendee->Mailbox = new EmailAddressType();
$attendee->Mailbox->EmailAddress = 'hsimpson@example.com';
$attendee->Mailbox->Name = 'Homer Simpson';
$attendee->Mailbox->RoutingType = new RoutingType();
$attendee->Mailbox->RoutingType->_ = RoutingType::SMTP;
$event->RequiredAttendees->Attendee[] = $attendee;

$attendee = new AttendeeType();
$attendee->Mailbox = new EmailAddressType();
$attendee->Mailbox->EmailAddress = 'msimpson@example.com';
$attendee->Mailbox->Name = 'Marge Simpson';
$attendee->Mailbox->RoutingType = new RoutingType();
$attendee->Mailbox->RoutingType->_ = RoutingType::SMTP;
$event->RequiredAttendees->Attendee[] = $attendee;

$request->Items->CalendarItem[] = $event;

$response = $client->CreateItem($request);
```

**Comment by jamesiarmes** [comment]
Four weeks with no response. Closing.
