### ISSUE TITLE
GetUserConfiguration

### ISSUE THREAD

**Issue by sachindsysmind** [jamesiarmes/php-ews#318]
no any option for GetUserConfiguration in PHP EWS

**Comment by Garethp** [comment]
Can you expand on what you mean by that? What are you expecting? What do you find lacking? What would you like to see?

**Comment by sachindsysmind** [comment]
How to find ResolveNames

On Wed, Mar 23, 2016 at 4:13 PM, Garethp <notifications@github.com> wrote:

> Can you expand on what you mean by that? What are you expecting? What do
> you find lacking? What would you like to see?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesiarmes/php-ews/issues/318#issuecomment-200291801>
>



-- 

*Sachin Dubey* | SYSMIND, LLC

[image:
https://newoldstamp.com/editor/profilePictures/profile-b15c8fc3ea4630e2ca604f11e3e951c7-41898.png]

Phone: 609-897-9670 x 2174

Mobile: 783-900-1271

Email:  sachindsysmind@gmail.com <yrajsysmind@gmail.com>

Website: sysmind.com

Address: 38 Washington Road, Princeton Junction, NJ 08550

**Comment by Garethp** [comment]
That still doesn't explain what it is you want. What are you trying to do that you can't do?

**Comment by sachindsysmind** [comment]
I want to user personal information like FirstName LastName Phone etc.

**Comment by Garethp** [comment]
Mate, you're going to have to explain your goal, your problems, your desired inputs and outputs, what you've tried and why you can't do what you want to do in more than one sentence things if you want some help

**Comment by jamesiarmes** [comment]
I assume your issue is that the GetUserConfiguration opertaion was missing. This has been added in 86a3a95c72f914c87a367272b928a6e186abc97b.
