### ISSUE TITLE
Setting a Contact Photo

### ISSUE THREAD

**Issue by baaskoen** [jamesiarmes/php-ews#322]
I'm using the following code to set a contact photo: 

```
        $attachment = new EWSType_FileAttachmentType();
        $path = public_path() . '/assets/img/avatars_resized/'.$this->relation->avatar;
        $attachment->Content = file_get_contents($path);
        $attachment->Name = $this->relation->avatar;
        $attachment->ContentType = 'image/'.pathinfo($path)['extension'];
        $attachment->IsContactPhoto = true;

        $contact->Attachments = new EWSType_NonEmptyArrayOfAttachmentsType();
        $contact->Attachments->FileAttachment[] = $attachment;

        $req = new EWSType_CreateAttachmentType();

        $req->ParentItemId = $this->rContact->ItemId;
        $req->Attachments = new EWSType_NonEmptyArrayOfAttachmentsType();
        $req->Attachments->FileAttachment[] = $attachment;

        $ews->CreateAttachment($req);
```

This is identical to the code here: https://github.com/jamesiarmes/php-ews/wiki/Contact:-Set-and-Update-Photo

Although, this is not working. I'm getting the following error: 

> The request failed schema validation: The element 'FileAttachment' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'IsContactPhoto' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'. List of possible elements expected: 'ContentId, ContentLocation, Content' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.

**Comment by Leenzur** [comment]
Hi @baaskoen .
Have you already try : 
``` php
$attachment->IsContactPhoto = 'true';
```
Otherwise it seems Exchange 2010 doesn't got IsContactPhoto property from a comment here : http://gsexdev.blogspot.fr/2009/12/using-contact-photo-in-ews-in-exchange.html 
Maybe you should found properties on your Exchange version in the microsoft documentation.
Hope it helps.

**Comment by baaskoen** [comment]
Hey @Leenzur ,

$attachment->IsContactPhoto = 'true'; doesn't work but thanks for your reply. I will search some more.

**Comment by jamesiarmes** [comment]
@baaskoen Are you still having this issue?

**Comment by jamesiarmes** [comment]
I have added a [contact/set-photo](https://github.com/jamesiarmes/php-ews/blob/master/examples/contact/set-photo.php) example that should help others that may encounter this issue.
