### ISSUE TITLE
Creating default object from empty value (Updating Contact)

### ISSUE THREAD

**Issue by baaskoen** [jamesiarmes/php-ews#324]
When using the example code for updating a contact:

        // Update Firstname (simple property)
        $field = new EWSType_SetItemFieldType();
        $field->FieldURI->FieldURI = 'contacts:GivenName';
        $field->Contact = new EWSType_ContactItemType();
        $field->Contact->GivenName = 'Gomer';

Im getting the following error:

> Creating default object from empty value

It fails on this line: $field->FieldURI->FieldURI = 'contacts:GivenName';

**Comment by Leenzur** [comment]
Hi @baaskoen ,
yes a row is missing in the example : 
```php
$field = new SetItemFieldType();
$field->FieldURI = new PathToUnindexedFieldType(); // Here ! Because FieldURI object must be instancied to got FieldURI property above
$field->FieldURI->FieldURI = 'contacts:GivenName';
$field->Contact = new ContactItemType();
$field->Contact->GivenName = $name;
$change->Updates->SetItemField[] = $field;
```

**Comment by baaskoen** [comment]
Thanks! Works as a charm.

However, this doesnt:

```
// Update Email1 (indexed property).
$field = new EWSType_SetItemFieldType();
$field->IndexedFieldURI->FieldURI = 'contacts:EmailAddress';
$field->IndexedFieldURI->FieldIndex = EWSType_EmailAddressKeyType::EMAIL_ADDRESS_1;

$field->Contact = new EWSType_ContactItemType();
$field->Contact->EmailAddresses = new EWSType_EmailAddressDictionaryType();

$entry = new EWSType_EmailAddressDictionaryEntryType();
$entry->_ = 'homer.simpson@springfield.net';
$entry->Key = EWSType_EmailAddressKeyType::EMAIL_ADDRESS_1;

$field->Contact->EmailAddresses->Entry = $entry;

$change->Updates->SetItemField[] = $field;
```

Getting this again:

> Creating default object from empty value

**Comment by Leenzur** [comment]
For indexed properties : 
```php
$field->IndexedFieldURI = new PathToIndexedFieldType();
```

**Comment by baaskoen** [comment]
Then I'm getting the following error:

`The request failed schema validation: The required attribute 'FieldURI' is missing.`

**Comment by Leenzur** [comment]
Please can you show your new code ?

**Comment by baaskoen** [comment]
$field->IndexedFieldURI = new PathToIndexedFieldType();
        $field->IndexedFieldURI->FieldURI = 'contacts:EmailAddress';
        $field->IndexedFieldURI->FieldIndex = EWSType_EmailAddressKeyType::EMAIL_ADDRESS_1;

        $field->Contact = new EWSType_ContactItemType();
        $field->Contact->EmailAddresses = new EWSType_EmailAddressDictionaryType();

**Comment by Leenzur** [comment]
ah sorry I use symfony which integrate php-ews as a bundle.
Add "EWSType_" before "PathToIndexedFieldType()".

**Comment by baaskoen** [comment]
Yeah I do too (well, Laravel). But that isn't the issue, the code breaks on the FieldUri line.

**Comment by Leenzur** [comment]
Here is the code which works for me :
```php
$field = new SetItemFieldType();
			$field->IndexedFieldURI = new PathToIndexedFieldType();
			$field->IndexedFieldURI->FieldURI = 'contacts:EmailAddress';
			$field->IndexedFieldURI->FieldIndex = EmailAddressKeyType::EMAIL_ADDRESS_1;
			$field->Contact = new ContactItemType();
			$ews_email = new EmailAddressDictionaryEntryType();
			$ews_email->Key = new EmailAddressKeyType();
			$ews_email->Key->_ = EmailAddressKeyType::EMAIL_ADDRESS_1;
			$ews_email->_ = $email;
			$field->Contact->EmailAddresses->Entry[] = $ews_email;
```
Try to compare and adapt. Indexed field aren't very intuitive.

**Comment by baaskoen** [comment]
It breaks on this line:

          $field->IndexedFieldURI->FieldURI = 'contacts:EmailAddress';

**Comment by Leenzur** [comment]
Same error ? (`The request failed schema validation: The required attribute 'FieldURI' is missing.`)

**Comment by baaskoen** [comment]
No, `Creating default object from empty value`.
