### ISSUE TITLE
Add contact for Impersonation Account

### ISSUE THREAD

**Issue by baaskoen** [jamesiarmes/php-ews#325]
When I login using my impersonation details:

> $ews = new ExchangeWebServices($this->server_address, $this->server_username, $this->server_password);

I want to create a new contact, e.g.:

> ```
> $request = new EWSType_CreateItemType();
> $contact = new EWSType_ContactItemType();
> $contact->Initials = $this->relation->initials;
> $contact->GivenName = $this->relation->first_name;
> $contact->MiddleName = $this->relation->insertion;
> $contact->Surname = $this->relation->last_name;
> $request->Items->Contact[] = $contact;
> $result = $ews->CreateItem($request);
> ```

I want to add this contact to a account that exists in my impersonation account list.

I want to avoid directly login in as an exchange user like:

```
$ews = new ExchangeWebServices($this->server_address, 'some@outlook.account', 'somepassword');
```

Is this possible? How would I achieve such a thing? Thanks for reading!

**Comment by jamesiarmes** [comment]
When using impersonation, you need to call `setImpersonation()` on your instance of `\jamesiarmes\PhpEws\Client`. This will allow you to set the user you are impersonating as.
