### ISSUE TITLE
401 error with curl 7.48 connecting to Exchange 2013

### ISSUE THREAD

**Issue by ebrassel** [jamesiarmes/php-ews#328]
Thanks so much for this great library; it's been really helpful.

I know that there has been a lot of discussion about getting a 401 authorization error, and with Exchange 2013, it generally seems to be solved by upgrading curl to 7.30+.

With Exchange 2013 and curl 7.48, I'm getting a 401. I was wondering if anyone has had this problem with curl 7.4x? Or if anyone can pinpoint the specific NTLM issues that cause the 401? I'm reading through the curl changelog but know very little about NTLM and so far don't see a likely culprit. 

I tried changing line 77 of NTLMSoapClient.php, as recommended in #151, but this made no difference.

We're upgrading from Exchange 2010 to Exchange 2013; things had been working fine with Exchange 2010 and curl 7.27.

Thanks for your help!

cURL support => enabled
cURL Information => 7.48.0
Age => 3
Features
AsynchDNS => Yes
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
Largefile => Yes
NTLM => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
krb4 => No
libz => Yes
CharConv => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-redhat-linux-gnu
SSL Version => OpenSSL/1.0.1e
ZLib Version => 1.2.3
libSSH Version => libssh2/1.4.

**Comment by Garethp** [comment]
Can you try doing the following settings for your HTTPAuth?

`CURLAUTH_BASIC`
`CURLAUTH_BASIC | CURLAUTH_NTLM`
`CURLAUTH_NTLM`

Unfortunately that's the only suggestions I can give. This library is unmaintained and mostly dead. I maintain my own library at [`garethp/php-ews`](http://github.com/garethp/php-ews) which might fix your issues, if your code base isn't too big to move over.

**Comment by ebrassel** [comment]
Thank you for your suggestion, Garethp! It turned out that there was a permissions issue with the account I was using, and once that was resolved the 401 error disappeared.

Is garethp/php-ews compatible with Office 365? We'll be updating soon.

**Comment by Garethp** [comment]
Hi there

Yes, it is. It's as easy as just changing the server location to `outlook.office365.com`, but we also have support for authentication over OAuth instead of by plain username and password. OAuth does require redirecting the user to Microsoft (Obviously), but once you have the token you're good to go. [Here's an example on how to do so](https://github.com/Garethp/php-ews/blob/master/examples/basic/authenticatingWithOAuth.php). With that being said, I personally have a `test.php` which I don't check in, that I just use for executing quick and dirty code for testing purposes. Here's what mine looks like at the moment

```php
<?php

require_once "vendor/autoload.php";

use garethp\ews\API\Type;
use garethp\ews\API\Enumeration;
use garethp\ews\Contacts\ContactsAPI as API;

//$api2010 = API::withUsernameAndPassword('mail.sistercompany.com', 'gareth@compnay.com', 'password', [
//    'timezone' => 'Central European Standard Time'
//]);
//
//
//$api = API::withUsernameAndPassword('mail.sistercompany.com', 'gareth@company.com', 'password', [
//    'timezone' => 'Central European Standard Time',
//    'version' => 'Exchange2010'
//]);

$api = API::withUsernameAndPassword(
    'https://outlook.office365.com',
    'myOfficeEmail',
    'password',
    ['version' => \garethp\ews\API\ExchangeWebServices::VERSION_2013_SP1]
);

$contacts = $api->getContacts();
foreach ($contacts as $contact) {
    $api->deleteItems($contact->getItemId());
}

$contact = $api->createContacts(array(
    'GivenName' => 'John',
    'Surname' => 'Smith',
    'EmailAddresses' => array(
        'Entry' => array('Key' => Enumeration\EmailAddressKeyType::EMAIL_ADDRESS_1, '_value' => 'john.smith@gmail.com')
    ),
    //Creating multiple entries
    'PhoneNumbers' => array(
        'Entry' => array(
            array('Key' => Enumeration\PhoneNumberKeyType::HOME_PHONE, '_value' => '000'),
            array('Key' => Enumeration\PhoneNumberKeyType::BUSINESS_PHONE, '_value' => '111'),
        )
    ),
    'PhysicalAddresses' => array(
        'Entry' => array(
            array(
                'Key' => Enumeration\PhysicalAddressKeyType::BUSINESS,
                'street' => '123 Street',
                'city' => '123 City',
                'state' => '123 State'
            ),
            array(
                'Key' => Enumeration\PhysicalAddressKeyType::HOME,
                'street' => '321 Street',
                'city' => '321 City',
                'state' => '321 State'
            )
        )
    )
))[0];

$api->updateContactItem($contact, array(
    'Surname' => 'NotSmith',
    'deleteFields' => array(
        'GivenName',
        'PhysicalAddress:Home',
        'PhysicalAddress:City:Business'
    )
));

$contact = $api->getContact($contact);

//$api->deleteItems($contact->getItemId());

exit();
```

Just as an example
