### ISSUE TITLE
Message Body length seems limited to 110 charachters

### ISSUE THREAD

**Issue by caglaror** [jamesiarmes/php-ews#329]
Is there a known issue about this error. There is no error message but it seems some thing limits the body length.
Under 100 chars it sends with any problem, after 101 char length it doesn't send.

**Comment by awrussel2002** [comment]
Im having same problem as well

**Comment by jamesiarmes** [comment]
Could you please provide an example of a request and response that produces the issue you're having?

**Comment by caglaror** [comment]
Sorry but i bypassed the problem. Now i don't remember exact conditions which cause that error. Thank you.

**Comment by jamesiarmes** [comment]
Okay, thank you for your response.

**Comment by caglaror** [comment]
:( @jamesiarmes unfortunately the problem wakeup again.  Here is my function for emailing.

`function ePostaGonder($emailserver, $emailusername, $emailpassword, $aliciADSOYAD, $aliciEPOSTA, $mesajKONU, $mesajGOVDE)
{
   $ews = new ExchangeWebServices($emailserver, $emailusername, $emailpassword);
    $msg = new EWSType_MessageType();
    $toAddresses = array();
    $toAddresses[0] = new EWSType_EmailAddressType();
    $toAddresses[0]->EmailAddress = $aliciEPOSTA;
    $toAddresses[0]->Name = $aliciADSOYAD;
    $msg->ToRecipients = $toAddresses;
    $fromAddress = new EWSType_EmailAddressType();
    $fromAddress->EmailAddress = 'yebesis@titck.gov.tr';
    $fromAddress->Name = 'YeBeSis';
    $msg->From = new EWSType_SingleRecipientType();
    $msg->From->Mailbox = $fromAddress;
    $msg->Subject = $mesajKONU;
    $msg->Body = new EWSType_BodyType();
    $msg->Body->BodyType = 'HTML';
    $msg->Body->_ = $mesajGOVDE;
    $msgRequest = new EWSType_CreateItemType();
    $msgRequest->Items = new EWSType_NonEmptyArrayOfAllItemsType();
    $msgRequest->Items->Message = $msg;
    $msgRequest->MessageDisposition = 'SendAndSaveCopy';
    $msgRequest->MessageDispositionSpecified = true;

    try {
        $response = $ews->CreateItem($msgRequest);

        if($response->ResponseMessages->CreateItemResponseMessage->ResponseCode=='NoError'){
            $gidenVeri=[];
            $gidenVeri['durum']='OK';
            return $gidenVeri;
        }
    } catch (Exception $e) {
        $gidenVeri=[];
        $gidenVeri['durum']='NOK';
        return $gidenVeri;
    }


    var_dump($response->ResponseMessages->CreateItemResponseMessage->ResponseCode);
}
`

and i am using it with 

`ePostaGonder($emailserver, $emailusername, $emailpassword, 'Çağlar ORHAN','caglar.orhan@titck.gov.tr','HATIRLATICI KONU: asdasd', 'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqX'); 

`

----
 The last char is X which is 101th char. When i remove the 101th char "X" it works. Is it about my codes or ews api ?

**Comment by jamesiarmes** [comment]
I believe this has been resolved, but I see that you are using an old version of the library. I recommend updating to the latest release candidate to see if that resolves your issue.
