### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by samhealey29** [jamesiarmes/php-ews#331]
Hi,

I am trying to test this but I am getting the following error:

Fatal error: Class 'ExchangeWebServices' not found in X:\wamp64\www\php-ews-composer\phpewstest.php on line 4

Code as follows:

```
<?php
require __DIR__ . '/vendor/autoload.php';

$ews = new ExchangeWebServices($host, $username, $password);

// start building the find folder request
$request = new EWSType_FindFolderType();
$request->Traversal = EWSType_FolderQueryTraversalType::SHALLOW;
$request->FolderShape = new EWSType_FolderResponseShapeType();
$request->FolderShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;

// configure the view
$request->IndexedPageFolderView = new EWSType_IndexedPageViewType();
$request->IndexedPageFolderView->BasePoint = 'Beginning';
$request->IndexedPageFolderView->Offset = 0;

// set the starting folder as the inbox
$request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
$request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
$request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::INBOX;

// make the actual call
$response = $ews->FindFolder($request);
echo '<pre>'.print_r($response, true).'</pre>';
```

Any ideas?? Sorry, I'm a buit of a newbie.

Many Thanks,

**Comment by Garethp** [comment]
Did you install it with composer?

**Comment by osomanden** [comment]
Poke.
I have the same issue -  and I just downloaded the files and tried to require/include them in my project.
I havent (currently) access to composer on the server.

**Comment by samhealey29** [comment]
Hi,

Yes I installed with composer. I uninstalled and reinstalled again thinking it may have been something I was doing. I am also using the latest version of WAMP.

**Comment by osomanden** [comment]
http://stackoverflow.com/questions/37373516/getting-php-ews-to-work

Gareth was so kind to assist me.. and it works. But you need to install php-ews with composer and then include the ./vendor/autoload.php file.

**Comment by Garethp** [comment]
I would try to give more help no this library, but I don't know how well it's autoloaded. If you're using my fork ([`garethp/php-ews`](https://github.com/Garethp/php-ews)) That I can help with.

**Comment by mikado330** [comment]
Hi , i have the same issue : 

Fatal error: Class 'ExchangeWebServices' not found in C:\Program Files\EasyPHP-12.1\home\ExchangeProject\ExchangeProject.php on line 15

I think that the problem is with my composer.json : 

 "require": {
		"php-ews/php-ews": "dev-composer"

    }

With this line composer update works, but when i change to : 

 "require": {
		"php-ews/php-ews": "dev-master"

    }

i got this error : 

Problem 1 
    - The requested package php-ews/php-ews dev-master exists as php-ews/php-ews[dev-composer] but these are rejected by your constraint.

Any ideas ? Thanks

**Comment by alexmgillis** [comment]
**Subscribe**
> Problem 1 
> - The requested package php-ews/php-ews dev-master exists as php-ews/php-ews[dev-composer] but these are rejected by your constraint.

**Comment by jamesiarmes** [comment]
You should be using "dev-master" in your composer now and the `ExchangeWebServices` is now `\jamesiarmes\PhpEws\Client`. If you're still having trouble, please open a new issue.
