### ISSUE TITLE
Probleme Composer update

### ISSUE THREAD

**Issue by mikado330** [jamesiarmes/php-ews#333]
Hi, i have a problem with composer update : 

my composer.json : 

"require": {
        "php-ews/php-ews": "dev-master",
    }

and when i do composer update i get this : 

Problem 1 
- The requested package php-ews/php-ews dev-master exists as php-ews/php-ews[dev-composer] but these are rejected by your constraint.

It works when i modify my composer.json to "dev_composer" but i don't have all the EWSType files.

Any ideas ? Thanks you

**Comment by icaroce** [comment]
Use php-ews/php-ews: dev-composer

**Comment by daveismyname** [comment]
try 

````
"php-ews/php-ews": "dev-composer",
````

**Comment by mrnnn** [comment]
@mikado330, try adding 

   `"minimum-stability": "dev",`

to your composer file.

https://getcomposer.org/doc/04-schema.md#minimum-stability

Basically, since this is a development branch and not a release, your composer refuses it.

**Comment by jamesiarmes** [comment]
@mikado330  You should be using "dev-master" at this point. Has your issue been resolved?

**Comment by fpiccinali** [comment]
@jamesiarmes : the issue is still there. 

````
    "require": {
        "php-ews/php-ews": "dev-master"
    }
````
Result with composer 1.2.4
````
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fazae/crmbundle dev-master requires php-ews/php-ews dev-composer -> satisfiable by php-ews/php-ews[dev-composer] but these conflict with your requirements or minimum-stability.
    - fazae/crmbundle dev-master requires php-ews/php-ews dev-composer -> satisfiable by php-ews/php-ews[dev-composer] but these conflict with your requirements or minimum-stability.
    - Installation request for fazae/crmbundle dev-master -> satisfiable by fazae/crmbundle[dev-master].

````

**Comment by jamesiarmes** [comment]
@fpiccinali You need to set your minimum-stability to "dev".

**Comment by fpiccinali** [comment]
Consider also using prefer-stable: 
````
minimum-stability: dev,
prefer-stable: true
````

**Comment by caglaror** [comment]
That doesn't not solve my problem:

{
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "smalot/pdfparser": "*",
    "php-ews/php-ews": "dev-master"
    }


}

**Comment by caglaror** [comment]
Ok did it! Problem solved when i reload composer.

**Comment by Nessworthy** [comment]
This might seem like a non-issue at this point, but is it not possible to have a definite release for this package? I'd rather not have to switch composer to allow dev branches through lowering minimum stability for all packages.
