### ISSUE TITLE
Allow curl options to be provided to the client

### ISSUE THREAD

**Issue by jamesiarmes** [jamesiarmes/php-ews#337]
A number of users have suggested making changes to the curl options used in the NTLMSoapClient. A common set of options should be defined (perhaps the current options are fine for the majority of cases) and a facility to add/remove/update options should be provided for the use cases where the defaults will not suffice.

**Comment by Garethp** [comment]
Personally I've been using `array_replace_recursive` all over my code base and propogating options down, so any options passed in when creating my `API` class gets passed down to the `NTLMSoapClient` class. See [here](https://github.com/Garethp/php-ews/blob/master/src/API/NTLMSoapClient.php#L139).

I've also moved to Guzzle, as you can see in my `__doRequest` method

**Comment by mrnnn** [comment]
Hey @jamesiarmes. Are you still considering this? Or switching to Guzzle, like @Garethp did? 

But just the ability to pass curl options & request headers would be NICE!

**Comment by jamesiarmes** [comment]
Yes, this is still slated for the 1.0 release.

**Comment by jamesiarmes** [comment]
This has been completed with vsf3tu2ziy8og4skos4k. You can supply curl options by calling `setCurlOptions()` on the client before making the request. For example, to prevent SSL certificates from being validated:

```php
use \jamesiarmes\PhpEws\Client;

$client = new Client($host, $username, $password);
$ews->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));
```

Please note that the NTLM soap client has been moved to a separate project (https://github.com/jamesiarmes/php-ntlm) and is required using composer.

**Comment by abdosaeedelhassan** [comment]
Hi, when i tried

$client = new Client($this->host, $this->username, $this->password, $this->version);
$client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));

i received that 

SoapFault
looks like we got no XML document

need help please, thank you

**Comment by Garethp** [comment]
This should be fixed in the latest version of master. Can you check it out and let me know if it's fixed?

**Comment by abdosaeedelhassan** [comment]
i am already on last one ( "php-ews/php-ews": "^1.0"), but not worked for me

**Comment by Garethp** [comment]
Try `"php-ews/php-ews": "master"`

**Comment by abdosaeedelhassan** [comment]
i did it, but also the same error
![abc](https://user-images.githubusercontent.com/15355610/92970057-578aeb00-f47e-11ea-8c70-e2707c0edbee.png)

**Comment by Garethp** [comment]
Sorry, I got confused, I'm not the maintainer of this library, @jamesiarmes is. I just maintain a fork of this library. Hopefully you'll be able to get some help from @jamesiarmes

**Comment by abdosaeedelhassan** [comment]
thank you
