### ISSUE TITLE
Converting exchange email addresses

### ISSUE THREAD

**Issue by baaskoen** [jamesiarmes/php-ews#338]
When I dump emails where the `Sender` `RoutingType` is `EX` (I'm using impersonation), the `EmailAddress` is being shown like this:

> ```
> +"Sender": {#1197
>   +"Mailbox": {#1264
>     +"Name": "His/Her Name | His/Her Company"
>     +"EmailAddress": "/O=HOSTING-ORGANIZATION/OU=EXCHANGE ADMINISTRATIVE GROUP (XXXXXXXXXXX)/CN=RECIPIENTS/CN=XXXXXXXXXXXXXXXXXXXXX-INITIALS"
>     +"RoutingType": "EX"
>   }
> }
> ```

Is there some way to convert this to a valid SMTP email address? Or can I retrieve it in any way?

**Comment by happyoniens** [comment]
@baaskoen I hope it works for you:
```php
$request = new EWSType_ResolveNamesType();

$request->UnresolvedEntry = "/O=HOSTING-ORGANIZATION/OU=EXCHANGE ADMINISTRATIVE GROUP (XXXXXXXXXXX)/CN=RECIPIENTS/CN=XXXXXXXXXXXXXXXXXXXXX-INITIALS";
$request->ReturnFullContactData = true;
$return = $ews->ResolveNames($request);

if ($return->ResponseMessages->ResolveNamesResponseMessage->ResponseCode == "NoError") {
    return $return->ResponseMessages->ResolveNamesResponseMessage->ResolutionSet->Resolution->Mailbox->EmailAddress;
}
```

**Comment by jamesiarmes** [comment]
@baaskoen Can you confirm whether or not this resolved your issue?

**Comment by jamesiarmes** [comment]
Four weeks with no response. Closing.

**Comment by happyoniens** [comment]
@sumit79 which version of PHP-EWS are you using?

**Comment by sumit79** [comment]
I was able to resolve it thanks.

**Comment by trevone** [comment]
> @baaskoen I hope it works for you:
> 
> ```
> $request = new EWSType_ResolveNamesType();
> 
> $request->UnresolvedEntry = "/O=HOSTING-ORGANIZATION/OU=EXCHANGE ADMINISTRATIVE GROUP (XXXXXXXXXXX)/CN=RECIPIENTS/CN=XXXXXXXXXXXXXXXXXXXXX-INITIALS";
> $request->ReturnFullContactData = true;
> $return = $ews->ResolveNames($request);
> 
> if ($return->ResponseMessages->ResolveNamesResponseMessage->ResponseCode == "NoError") {
>     return $return->ResponseMessages->ResolveNamesResponseMessage->ResolutionSet->Resolution->Mailbox->EmailAddress;
> }
> ```

I have tried updating phpews and still getting:
PHP Fatal error:  Uncaught Error: Class 'EWSType_ResolveNamesType' not found

Where can I find this class

**Comment by sumit79** [comment]
I used following code. 


require_once '../../vendor/autoload.php';

use garethp\ews\API\Type\ConnectingSIDType;
use garethp\ews\API\Type\ExchangeImpersonation;


//Impersonate an email address
$api = \garethp\ews\API::withUsernameAndPassword(
    'outlook.office365.com',
    'username',
    'password',
    ['impersonation' => 'calendar email id']
);


$request = [
    'UnresolvedEntry' => '/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=7C43AD72EAAE4350AB55AFB5439F1A32-ABC',
    'ReturnFullContactData' => false
];

$response = $api->getClient()->ResolveNames($request);
print_r($response);


$calendar = $api->getCalendar();
$items = $calendar->getCalendarItems('2018-12-21', '2018-12-22');
echo "<pre>";

print_r($items);

**Comment by trevone** [comment]
i got it working just with
use \jamesiarmes\PhpEws\Request\ResolveNamesType;

**Comment by pfleu** [comment]
Using @happyoniens 's answer (I guess I had to make changes because of newer version of php-ews):

`$item` would be a message retrieved with FindItem(), as shown in the doc examples.

```
        $sender = $item->From->Mailbox->EmailAddress;
                if ($item->From->Mailbox->RoutingType == 'EX') {
                    $request = new ResolveNamesType();
                    $request->UnresolvedEntry = $sender;
                    $request->ReturnFullContactData = true;
                    $return = $client->ResolveNames($request);
                    if ($return->ResponseMessages->ResolveNamesResponseMessage[0]->ResponseCode == "NoError") {
                        $sender =  $return->ResponseMessages->ResolveNamesResponseMessage[0]->ResolutionSet->Resolution[0]->Mailbox->EmailAddress;
                    }
                }
```
