### ISSUE TITLE
CreateItem() for sending emails doesn't return ID.

### ISSUE THREAD

**Issue by piotrevic** [jamesiarmes/php-ews#340]
I'm using code from [example](https://github.com/jamesiarmes/php-ews/wiki/Email:-Send-Email). 
When I'm creating event the function returns ID, but for emails it doesn't. There is `items` array in response, but it's empty even if sending was successful. It is some issue or I should do something more to retrieve the ID?

**Comment by jamesiarmes** [comment]
Could you please provide an example of a request that produces the issue you're having?

**Comment by jamesiarmes** [comment]
Four weeks with no response. Closing.
