### ISSUE TITLE
How to retrieve images embedded in an email body?

### ISSUE THREAD

**Issue by midgard** [jamesiarmes/php-ews#345]
How to retrieve images embedded in an email body?

Like [cid:image28a7f8.JPG@c3efa540.498cea9f]

Thanks

**Comment by Garethp** [comment]
Have you checked if they exist as Attachments to the email?

**Comment by jamesiarmes** [comment]
@midgard Are you still having this issue?

**Comment by jamesiarmes** [comment]
Four weeks with no response. Closing.
