### ISSUE TITLE
Invalid versions

### ISSUE THREAD

**Issue by zwetan** [jamesiarmes/php-ews#346]
```
const VERSION_2007_SP2 = 'Exchange2007_SP2';
```

and

```
const VERSION_2007_SP3 = 'Exchange2007_SP3';
```

will return an error **ErrorInvalidServerVersion**
"The specified server version is invalid."

If you check
[EWS functionality in Exchange product versions](https://msdn.microsoft.com/en-us/library/office/dn781473%28v=exchg.150%29.aspx)

you can see that SP2 and SP3 are not mentioned
(eg. the SOAP protocole was not updated/changed for those versions)

I tested all the versions connecting to "outlook.office365.com"
all the versions work except the two above

**Comment by Garethp** [comment]
Yup, those two are *server* versions, not Schema versions. There's a slight difference, which is probably why James got confused when adding these in. Exchange SP2 and SP3 may be released server versions, but the SOAP schema didn't get changed for them, so there's no SOAP version for them. [Here's another article on it](https://msdn.microsoft.com/en-us/library/office/dn741586(v=exchg.150).aspx)

**Comment by jamesiarmes** [comment]
This issue has been resolved, thanks for the report!.
