### ISSUE TITLE
Documentation page not found

### ISSUE THREAD

**Issue by jlcfly** [jamesiarmes/php-ews#348]
I understand the documentation page has been moved to here: http://jamesarmes.com/php-ews/doc/0.1/ but that link results in a 404 page not found. 

Thanks for your work on this, BTW.

**Comment by Garethp** [comment]
Clicking around the website, the doc entry point is http://jamesarmes.com/php-ews/0.1/, not http://jamesarmes.com/php-ews/doc/0.1/

That being said, I'd recommend using my own fork of this project, [`garethp/php-ews`](http://github.com/garethp/php-ews). Jame's project is a bit out of date and the issues page isn't maintained often

**Comment by jamesiarmes** [comment]
Fixed the link on the post that had the incorrect URL with 5ea499b8159ca1ba87d1412859b786fa6b84b70f. The site should be updated now.
