### ISSUE TITLE
Event request and get events keys.

### ISSUE THREAD

**Issue by Sajgoniarz** [jamesiarmes/php-ews#349]
Hi guys!

I want to sync my db events with that one in outlook, so i made update script, but it duplicate events, because that one created from backend don't have ItemId. So i decided to send MeetingInvitation, but this idea failed too, because ItemId returned from CreateItem function is different than ItemId that im getting through FindItem. Any idea how can i deal with it?

**Comment by jamesiarmes** [comment]
I'm not sure I understand your issue. The id of an item does not change. The change key of an item will change whenever the item is updated, but this value is not necessary to update or view the item. You should be storing the id returned by `CreateItem` so that you can reference that value when syncing any updates between systems.

**Comment by Sajgoniarz** [comment]
@jamesiarmes ItemId->Id returned with CreateItem are not equal to ItemId->Id of event returned from FindItem

**Comment by jamesiarmes** [comment]
I have not been able to reproduce your issue, could you please provide examples of your requests and their associated responses.

**Comment by Sajgoniarz** [comment]
Ok, i updated library, and problem still occurs, but now i need that keys from response ;c
CreateItem(CalendarItem) request and response : http://pastebin.com/sLnK1fxX
FindItem(CalendarView) : http://pastebin.com/k48rbV7z

**Comment by jamesiarmes** [comment]
I haven't experienced this issue, but http://stackoverflow.com/questions/4164069/exchange-web-services-why-is-itemid-not-constant may provide some insight. Also, if you're trying to sync items, I would look into the `SyncFolderItems` operation.

I'll leave this issue open in case somebody else can help you with your issue, but I'm afraid I won't be of much help in this scenario.

**Comment by Sajgoniarz** [comment]
It's not your fault James ;) Microsoft informs that EventID can not be constant. It my case its... changing whole time :|. EventID in CreateItem Response != EventID of not accepted item in FindItem !=  EventID of accepted item in FindItem. It's quite ridiculous, because if organizer change every detail in event then i can't  be sure thats same event  ;/ Microsoft isn't very helpful in that case, so i think you can close that issue without solution.
