### ISSUE TITLE
calendar list example

### ISSUE THREAD

**Issue by erickengelke** [jamesiarmes/php-ews#350]
Hi,

I'm needing to switch my calendar retrieving code from an old PHP-EWS which stopped working
with the latest Exchange.  

I get a structure returned when I call 
  $calendar->getCalendarItems( $start, $end );

but all the data is protected so I can't read it.  How do I get a list of items I can call 
$calendar->getItem( $x )....
like, what is $x????  

I would have used foreach ( $calendar->items as $z ) but I can't because it's protected.

The calendar source examples do not show how to read the messages, just how to read the structure, but we are not perrmitted to read the contents.

Could you make an example which acceses the data inside?

Thanks
Erick

**Comment by jamesiarmes** [comment]
I don't understand the issue you've described, as no response or type implementations utilize private or protected methods. I was able to get a list of emails using the following request:

```php
use \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Enumeration\DistinguishedFolderIdNameType;
use \jamesiarmes\PhpEws\Request\FindItemType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfBaseFolderIdsType;
use \jamesiarmes\PhpEws\Type\DistinguishedFolderIdType;
use \jamesiarmes\PhpEws\Type\CalendarViewType;

$client = new Client($host, $username, $password, $version);

$request = new FindItemType();
$request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();

$folder_id = new DistinguishedFolderIdType();
$folder_id->Id = new DistinguishedFolderIdNameType();
$folder_id->Id->_ = DistinguishedFolderIdNameType::CALENDAR;
$request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;

$request->CalendarView = new CalendarViewType();
$request->CalendarView->StartDate = '2016-11-28T12:00:00Z';
//$request->CalendarView->StartDate = '2016-01-28T12:00:00Z';
$request->CalendarView->EndDate = '2016-11-30T23:59:59Z';

$result = $client->FindItem($request);
$items = $result->ResponseMessages->FindItemResponseMessage->RootFolder->Items->CalendarItem;

// If there is only one item, no array is created.
$items = (is_array($items) ? $items : array($items));

$item_ids = array();
foreach ($items as $item) {
    $item_ids[] = $item->ItemId->Id;
}

// Use a Client::GetItem operation here to get the full items.
```

**Comment by jamesiarmes** [comment]
Four weeks with not response. Closing.
