### ISSUE TITLE
Adding Calendar Item in PHP7

### ISSUE THREAD

**Issue by gohtar** [jamesiarmes/php-ews#355]
I cannot add a calendar item in PHP7 because of the 'jamesiarmes\PhpEws\Type\String' class.  It needs to be renamed to a non-reserved name.

Error: Cannot use 'String' as class name as it is reserved

**Comment by jamesiarmes** [comment]
This has been resolved with ce85d5b8831e62cd7781b20652ec27d0a9af399b.
