### ISSUE TITLE
Bug with curl version 7.47 causing hanging

### ISSUE THREAD

**Issue by brianpoole** [jamesiarmes/php-ews#356]
Being that the bug is with curl, this is more of an FYI for anyone who's using this library and runs into this issue.  There is a [known bug](https://github.com/curl/curl/issues/741) with curl version 7.47.0 which causes certain NTLM requests to hang when the Expect header is sent.

I ran into this issue when I was doing a **SyncFolderItems** request with a **SyncState** defined.  When it wasn't defined, I didn't have any issues.  I think the bug only occurs when the posted request is a certain length.

I'm currently unable to update curl to see if that fixes the issue, so I solved it by passing an empty value for **Expect:** into the curl `$headers` variable at the top of the `__doRequest( )` function located in **PhpEwq\Ntlm\SoapClient.php**.  See below:

``` php
        $headers = array(
            'Method: POST',
            'Connection: Keep-Alive',
            'User-Agent: PHP-SOAP-CURL',
            'Content-Type: text/xml; charset=utf-8',
            'SOAPAction: "'.$action.'"',
            'Expect:',
        );
```

I hope this helps someone (and that this is the right place to post this)!

**Comment by Garethp** [comment]
Hi Brian

I'm maintaining my own fork of this library that you might be interested in checking out, [`garethp/php-ews`](http://github.com/garethp/php-ews) and this looks like something I might be interested in looking in to. Can you specify the usage behind the the `Expect` header with Exchange Web Services?

Thanks,
Gareth

**Comment by brianpoole** [comment]
Hi Gareth, 

I did take a look at your fork briefly as I was having trouble with this project's outdated documentation, but I powered through it as I was already halfway done by then. Thanks for the suggestion. 

My understanding of the `Expect` header is that it's a standard header sent to the server when a post request is larger than 1024 bytes as a way to confirm that the receiving server can handle it. The server is then supposed to respond with a yes or no, essentially, which triggers the full request to be sent. For whatever reason curl 7.47.0 is getting hung up on this handshake of sorts. By sending an empty `Expect` header, it's forcing the curl request to send the full request right away.

I hope that helps.

Best Regards, 
Brian

**Comment by Garethp** [comment]
Thanks for that information. I'll look in to combating this issue or documenting it before it pops up in my issue list

**Comment by jamesiarmes** [comment]
@brianpoole I have not been able to verify this issue, I am using 7.47.0, but it's possible that either Ubuntu has patched this issue or that I simply haven't been able to craft a request that produces the issue. Could you verify that setting the `Expect` header to "Expect: 100-continue" resolves the issue?

**Comment by brianpoole** [comment]
@jamesiarmes Confirmed that if I set the `Expect` header to "Expect: 100-continue", doesn't hang, but if I don't define it at all, it hangs.

Based on what I've read, it has to do with the request length.  So, if you're not running into it and you're running 7.47.0 that might be why.  I ran into this on a server running Ubuntu 16.04.1 LTS.

**Comment by jamesiarmes** [comment]
@brianpoole Excellent, I have added the header to [jamesiarmes/php-ntlm](https://github.com/jamesiarmes/php-ntlm), which this library now depends on. Updating this library (if you haven't recently) and running composer update should resolve the issue. Thank your for your help.

**Comment by brianpoole** [comment]
@jamesiarmes Happy to help! Thanks!
