### ISSUE TITLE
Synchonization Issue

### ISSUE THREAD

**Issue by segpacto** [jamesiarmes/php-ews#359]
I am doing the synchronization for Events on the calendars, however the attributes related to filter using the dates fail to Filter and dont cause any effects.
Setting the startDate and endDate : 
 
$request->CalendarView = new EWSType_CalendarViewType();
$request->CalendarView->StartDate = $startDate;
$request->CalendarView->EndDate = $endDate;

What are the proper parameters to set a time Scope for the Synchronization.

**Comment by jamesiarmes** [comment]
What format are you using for your start and end date? Also, have you tried using an updated version of the php-ews library?

**Comment by segpacto** [comment]
the format used is the one provided by your team in the first documentation that was on github "2016-11-16T04:54:32-08:00", that is the format.

**Comment by jamesiarmes** [comment]
Using the latest [event/find](https://github.com/jamesiarmes/php-ews/blob/master/examples/event/find.php) example, I have been able to successfully filter events based on time. Could you give this a try and see if it resolves your issue?

**Comment by segpacto** [comment]
yes, the problem is that on the example '$request = new FindItemType()' is been used FindItem, however, I am using the old '$request = new EWSType_SyncFolderItemsType()' but I guess should not fail also, so, I am using it with synchronization. So, ist it possible to use the date filter while synchronizing ?

**Comment by jamesiarmes** [comment]
The `SyncFolderItems` operation does not support any filtering. You need to supply the latest `SycnState` in your request (assuming it is not the first synchronization) to get all items updated since then. See https://msdn.microsoft.com/en-us/library/aa563967(v=exchg.150).aspx for more information on how this operation works.

**Comment by hd74** [comment]
Maybe this issue can be closed? Sync doesn't support filters, as James said.

**Comment by segpacto** [comment]
Thanks a lot for the service, yes, I am closing this issue.
