### ISSUE TITLE
Update contact email with blank value or null value doesnt work  

### ISSUE THREAD

**Issue by nagesh314** [jamesiarmes/php-ews#362]
Update contact email with blank value or null value doesn't work. Old value remains as it is only ol value gets updates with new value but not with NULL value. 

here is the code 

$email = null;

if($email)
{
	$field = new EWSType_SetItemFieldType();
	$field->IndexedFieldURI->FieldURI = 'contacts:EmailAddress';
	$field->IndexedFieldURI->FieldIndex = EWSType_EmailAddressKeyType::EMAIL_ADDRESS_1;

	$field->Contact = new EWSType_ContactItemType();
	$field->Contact->EmailAddresses = new EWSType_EmailAddressDictionaryType();

	$entry = new EWSType_EmailAddressDictionaryEntryType();
	$entry->_ = $email;
	$entry->Key = EWSType_EmailAddressKeyType::EMAIL_ADDRESS_1;

	$field->Contact->EmailAddresses->Entry = $entry;

	$change->Updates->SetItemField[] = $field;
}
else
{
	$field = new stdClass();
	$field->IndexedFieldURI = new EWSType_PathToUnindexedFieldType();
	$field->IndexedFieldURI->FieldURI = 'contacts:EmailAddress';
	$field->IndexedFieldURI->FieldIndex = EWSType_EmailAddressKeyType::EMAIL_ADDRESS_1;
	
	$change->Updates->DeleteItemField[] = $field;
}

$request->ItemChanges[] = $change;

$response = $ews->UpdateItem($request);
var_dump($response);

**Comment by jamesiarmes** [comment]
In your `else` statement, $field should be an instance of `DeleteItemFieldType`. You should also update to the latest development version of this library, as the code in your example is outdated and there are likely various issues that have been resolved in the latest version.

**Comment by nagesh314** [comment]
ok thanks James. yes I updated to new liabrary.

Is there shortcut instead of using use statement for classes.

Regards,
Nagesh

**Comment by jamesiarmes** [comment]
The only alternative is to use the fully qualified name each time you reference the class. This would make your code harder to read in the long run and is not recommended. Can you verify whether or not your issue has been resolved?

**Comment by jamesiarmes** [comment]
@nagesh314 Has your issue been resolved?

**Comment by nagesh314** [comment]
Hi,

I am trying to get contact notes. i am getting them but the method which I
am using is taking long time and I am getting server time out error. max
fetch is 512. I reduce that value to 100 and i works. Do i have to use
additional properties method for fetching contact notes?

Regards,
Nagesh

**Comment by jamesiarmes** [comment]
Please open a new issue for follow-up questions that do not pertain to the original issue.

**Comment by nagesh314** [comment]
Hi James,

is there a way to get contacts sync in descending order last in first.

$request = new EWSType_SyncFolderItemsType;

Regards,
Nagesh
