### ISSUE TITLE
Distribution group/list

### ISSUE THREAD

**Issue by RafalJaworski** [jamesiarmes/php-ews#372]
Version (e.g. 1.0, dev-master):

Description of problem:
How to add new group and later on add contacts to those groups?

Example request:

```php

```

Example response:

```

```

Additional details:

**Comment by jamesiarmes** [comment]
According to the Exchange Web Services documentation, you can not create or update distribution list members: https://msdn.microsoft.com/en-us/library/office/dn629393%28v=exchg.150%29.aspx.
