### ISSUE TITLE
PHP Fatal error:  Uncaught SoapFault exception: [Client] SoapClient::__doRequest() returned non string value

### ISSUE THREAD

**Issue by winds1983** [jamesiarmes/php-ews#373]
Version (e.g. 1.0, dev-master): dev-master

Description of problem:
Still get below errors:
```
PHP Fatal error:  Uncaught SoapFault exception: [Client] SoapClient::__doRequest() returned non string value in /var/www/html/screen-snapshot/vendor/php-ews/php-ews/src/Client.php:1631
```

Use this code:
https://github.com/jamesiarmes/php-ews/blob/master/examples/message/create.php

**Comment by jamesiarmes** [comment]
Could you provide the response code, headers and body? You can get this data by catching the exception like so:

```php
try {
    $response = $client->CreateItem($request);
} catch (\SoapFault $e) {
    $soap = $client->getClient();
    $response_code = $soap->getResponseCode();
    $response_headers = $soap->__getLastResponseHeaders();
    $response_body = $soap->__getLastResponse();
}
```

**Comment by jumpkickweb** [comment]
For me, this error was because I needed to add the following curl options to Client.php.
(I'm assuming it's Client.php, because I'm using an older version of PHP-EWS and the filename for that version is NLTMSoapClient.php)

```
/*  not sure if this is relevant   */
curl_setopt($this->ch, CURLOPT_SSLVERSION, 3);

/*   you must download the cacert file and save it to your server, and then change the variable name below to point to the path where you put the file. You can download the cacert file here: https://curl.haxx.se/docs/caextract.html     */
$fileLocationForCaCert="certs/cacert-2018-01-17.pem";
curl_setopt($this->ch, CURLOPT_CAINFO, $fileLocationForCaCert);
```

**Comment by jamesiarmes** [comment]
There's been no update on the original issue in over a year, so I'm closing this. 

@jumpkickweb If you update to 1.0, you can set curl options on the client rather than having to hack the library. You'll also be on a supported version :wink:
