### ISSUE TITLE
How to create folders?

### ISSUE THREAD

**Issue by staypot** [jamesiarmes/php-ews#374]
I want to create folder for calendar to save my event on the created calendar. the problem is i get this error, what am i missing?

"The request failed schema validation: The required attribute 'Id' is missing."

```php   
$request = new CreateFolderType();
$request->Folders = new NonEmptyArrayOfBaseFolderIdsType();
$request->Folders->Folder = new FolderType();
$request->Folders->Folder->DisplayName = "My New Calendar";
$request->Folders->Folder->FolderClass = "Calendar";
$request->ParentFolderId = new NonEmptyArrayOfBaseFolderIdsType();

$folder_id = new DistinguishedFolderIdType();
$folder_id->Id = DistinguishedFolderIdNameType::CALENDAR;

$request->ParentFolderId->DistinguishedFolderId = $folder_id;

$response = $client->CreateFolder($request);
```

and Please give me some example of deleting a created folder / saving in created folder

**Comment by jamesiarmes** [comment]
I have added examples for creating, deleting and finding folders in f3ac3bfb3ef040cd755e215e51478886a583a991. To save an item to a new folder, you need to specify the id of the folder in the appropriate request.
