### ISSUE TITLE
Old documentation wiki

### ISSUE THREAD

**Issue by laoneo** [jamesiarmes/php-ews#375]
Would it be possible to activate the old wiki pages with the examples till the final release 1.0 is out. I think many are using the old api and do still need some documentation. Thanks for considering it.

**Comment by jamesiarmes** [comment]
The old documentation has been moved to http://jamesarmes.com/php-ews/0.1/. However, I would highly recommend updating to the latest beta as many issues have been resolved.

**Comment by laoneo** [comment]
Saw that link already, but missed the select box on the side.
