### ISSUE TITLE
The request failed schema validation: The required attribute 'Traversal' is missing.

### ISSUE THREAD

**Issue by wilbertsky** [jamesiarmes/php-ews#376]
Version (e.g. 1.0, dev-master): 
versions :  dev-master, 1.0.x-dev
Microsoft Exchange version: 2010

Description of problem: 

New to EWS and using php-ews. I have a problem where when trying to connect find items by date, I get an error back stating: "The request failed schema validation: The required attribute 'Traversal' is missing." 

Example request:
This is inside a class where I have already included the appropriate files, and made the connection to the client:
```php
		$this->client->setTimezone('America/Los_Angeles');
		$start_date = new \DateTime('3 AM');
		$end_date = new \DateTime('7 PM');		
		$request = new FindItemType();
		$request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();

		$folder_id = new DistinguishedFolderIdType();
		$folder_id->Id = new DistinguishedFolderIdNameType();
		$folder_id->Id->_ = DistinguishedFolderIdNameType::CALENDAR;
		$request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;

		$request->CalendarView = new CalendarViewType();
		$request->CalendarView->StartDate = $start_date;
		$request->CalendarView->EndDate = $end_date;

		$result = $this->client->FindItem($request);
```

It is here, above, on the last line where $this->client->FindItem($request); produces the error.

Example response:

```
The request failed schema validation: The required attribute 'Traversal' is missing.
```

Additional details:
The full error shows as:

```
"faultstring":"The request failed schema validation: The required attribute 'Traversal' is missing.","faultcode":"a:ErrorSchemaValidation","detail":{"ResponseCode":"ErrorSchemaValidation","Message":"The request failed schema validation.","MessageXml":{"LineNumber":"2","LinePosition":"420","Violation":"The required attribute 'Traversal' is missing."
```

**Comment by itcrowdmmgroup** [comment]
You need to put in a traversal type eg;:

$request->Traversal = ItemQueryTraversalType::SHALLOW;

**Comment by wilbertsky** [comment]
This worked well. Thank you for that.
