### ISSUE TITLE
Cannot json_encode() FindItem response with DefaultShapeNamesType::ALL_PROPERTIES

### ISSUE THREAD

**Issue by ManiMuridi** [jamesiarmes/php-ews#383]
Version (e.g. 1.0, dev-master): 1.0

Microsoft Exchange version: All

Description of problem:
PHP cannot json_encode() the email `FindeItem` response even after looping and adding the results to an array due to bad utf8 encoding of `ConversationIndex`

I just used the find.php file included in the examples/ folder. I changed Default shape to ALL_Properties 

`$request->ItemShape->BaseShape = DefaultShapeNamesType::ALL_PROPERTIES; `

json_encode is returning 
Example request:

```php
foreach ($response_messages as $response_message) {
    // Make sure the request succeeded.
    if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
        $message = $response_message->ResponseCode;
        fwrite(STDERR, "Failed to search for messages with \"$message\"\n");
        continue;
    }

    // Iterate over the messages that were found, printing the subject for each.
    $items = $response_message->RootFolder->Items->Message;
    foreach ($items as $item) {
    	$mails[] = $item;
        // $subject = $item->Subject;
        // $id = $item->ItemId->Id;
        // fwrite(STDOUT, "$subject: $id\n");
    }
}
```

Example response:

```

```

Additional details:

**Comment by ManiMuridi** [comment]
I solved it by using `utf8_encode` on the strings that had bad utf8 format:

	```
public $encodable = ['ConversationIndex','InstanceKey'];

	function __construct(Array $attributes = [])
    {
    	$this->collection = 'user_id_account_emails';

    	foreach ($attributes as $key => $value) {
    		if(in_array($key, $this->encodable))
    			$this->$key = utf8_encode($value);
    		else
    			$this->$key = $value;
    	}
    }
```

but isnt' there an easier way to do this? like only getting properties you need instead of ALL_PROPERTIES, DEFAULT_PROPERTIES etc...

**Comment by jamesiarmes** [comment]
You can use `$request->ItemShape->AdditionalProperties` to define individual properties to be included in the result. Please note that you can not use this to include properties that are not normally available in the response to a `FindItem` request, such as the item body.
