### ISSUE TITLE
cURL fails with self signed certificate

### ISSUE THREAD

**Issue by engiadina** [jamesiarmes/php-ews#384]
My exchange server uses a self signed certificate. I found no real way to make curl access this server, every request fails with 

PHP Fatal error:  Uncaught RuntimeException: Curl error: SSL certificate problem: unable to get local issuer certificate in /var/lib/asterisk/agi-bin/php-ews-master/vendor/jamesiarmes/php-ntlm/src/SoapClient.php:91

Using and setting the -k option seems to have no effect.  Could someone point me into the right direction?

Thanks

engiadina

**Comment by jamesiarmes** [comment]
You need to tell cURL to not validate the certificate. You can find an example of doing so here: https://github.com/jamesiarmes/php-ews/issues/337#issuecomment-263478785.

**Comment by engiadina** [comment]
Your example likely needs to be rewritten as:

$client = new Client($host, $username, $password);
$**client**->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));

Actually didn't solve that completely. Now I get the error 

Uncaught RuntimeException: Curl error: SSL: certificate subject name 'server03' does not match target host name '192.168.xxx.xxx

How to tell cURL to not to care completely about the certificate ?

**Comment by jamesiarmes** [comment]
Ahh, yes, I've update that example, thanks. My best guess would be that you need to set the hostname in your cert to match what you're using to connect. You can also try telling cURL not to verify the host by setting `CURLOPT_SSL_VERIFYHOST` to `false`. See http://php.net/manual/en/function.curl-setopt.php for a list of all cURL options.

**Comment by engiadina** [comment]
Oh well, that link does not list that option. But still a good hint.

Here you are:
https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html

**Comment by jamesiarmes** [comment]
That option is definitely listed in the documentation I linked to, just below `CURLOPT_SSL_OPTIONS` (the list of options appears to be in alphabetical order).

**Comment by engiadina** [comment]
Yes sorry, just edited my comment. I found it ...

**Comment by engiadina** [comment]
OK, got it working, somehow ...

I tried to simple read my contacts folder and had to modify the example a bit to make it work (changed code is italic:

require_once 'php-ews-master/vendor/autoload.php';
# include ('./vendor/autoload.php');

use \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Request\FindItemType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfBaseFolderIdsType;
use \jamesiarmes\PhpEws\Enumeration\DistinguishedFolderIdNameType;
use \jamesiarmes\PhpEws\Enumeration\ResponseClassType;
use \jamesiarmes\PhpEws\Type\ContactsViewType;
use \jamesiarmes\PhpEws\Type\DistinguishedFolderIdType;
_use \jamesiarmes\PhpEws\Enumeration\ItemQueryTraversalType;
use \jamesiarmes\PhpEws\Enumeration\PreviewItemBaseShapeType;_


$host = '192.168.xxx.xxx';
$username = 'user';
$password = 'password';
$version = Client::VERSION_2010_SP2;
$client = new Client($host, $username, $password, $version);
$client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false, CURLOPT_SSL_VERIFYHOST => false));


// Build the request.
$request = new FindItemType();
$request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();
$request->ContactsView = new ContactsViewType();
// Find contacts in the contacts folder.
$folder_id = new DistinguishedFolderIdType();
$folder_id->Id = DistinguishedFolderIdNameType::CONTACTS;
$request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;
_$request->Traversal = ItemQueryTraversalType::ASSOCIATED;
$request->ItemShape->BaseShape = PreviewItemBaseShapeType::DEFAULT_SHAPE;_

$response = $client->FindItem($request);


// Iterate over the results, printing any error messages or contact ids.
$response_messages = $response->ResponseMessages->FindItemResponseMessage;
foreach ($response_messages as $response_message) {
    // Make sure the request succeeded.
    if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
        $message = $response_message->ResponseCode;
        fwrite(STDERR, "Failed to search for contacts with \"$message\"\n");
        continue;
    }
    // Iterate over the contacts that were found, printing the id of each.
    $items = $response_message->RootFolder->Items->Contact;
    foreach ($items as $item) {
        $id = $item->ItemId->Id;
        fwrite(STDOUT, "Found contact $id\n");
    }
}


This actually genereates a SOAP request but still fails:

PHP Warning:  Creating default object from empty value in /var/lib/asterisk/agi-bin/test.php on line 116
Failed to search for contacts with "ErrorInvalidOperation"


Thanks for your help already ...

**Comment by jamesiarmes** [comment]
The PHP Warning is due to `$request->ItemShape` not being set to an instantiated object before using it. You need this line prior to it:

```php
$request->ItemShape = new ItemResponseShapeType();
```

The error you are getting back from Exchange is due to your traversal type. If you check the `$response_message->MessageText`, you will see "ContactsView isn't supported for associated items."

In the future, pleas format your code using Markdown like so:

    ```php
    CODE
    ```

This makes reading your code snippets easier and will aid in resolving your issue.

**Comment by jamesiarmes** [comment]
@engiadina Has your issue been resolved?

**Comment by haakym** [comment]
Encountered similar issue and to get it working, for now, I used the following code:

```php
$curlOptions = [
	CURLOPT_SSLVERSION => 3,
	CURLOPT_SSL_VERIFYPEER => false,
	CURLOPT_SSL_VERIFYHOST => false
];

//....

$client = new Client($host, $username, $password, $version);

$client->setCurlOptions($curlOptions);
```
