### ISSUE TITLE
Creating appointments without attendees (with impersonation)

### ISSUE THREAD

**Issue by cjmozart** [jamesiarmes/php-ews#389]
Version (e.g. 1.0, dev-master): _1.0.0-beta.1_

Microsoft Exchange version: _2010_

Description of problem:
I am trying to sync our private secure calendar with the university's main exchange-server, and need to create appointments with no attendees (ie private appointments) for all of our users. 

Ive figured out how to use impersonation, but I'm not sure how to build the calendarItemType as a private appointment and not a meeting. 

I'm guessing the 
_$event = new CalendarItemType();
$event->RequiredAttendees = new NonEmptyArrayOfAttendeesType();_
from the example should be changed, but Im strugling to get my head around what to choose.

I know this isn't a bug, but cannot find anywhere else to ask.

mvh

Kim

**Comment by jamesiarmes** [comment]
`RequiredAttendees` is not a required property. If you want a simple appointment, just don't set that property to anything. If you want to set the item as private, you can do so using the `Sensitivity` property.  See https://msdn.microsoft.com/en-us/library/office/dn495611(v=exchg.150).aspx#Anchor_1 for more information on creating appointments via Exchange Web Services.

**Comment by cjmozart** [comment]
@jamesiarmes I can verify that it did yes. I needed to set the Traversal-property though. I didn't think it was mandatory, but I couldn't get the schema to accept it without.

Thanks for the help.

**Comment by jeffreyvg** [comment]
@jamesiarmes I'm having a similar problem.
My code looks like this:
$request = new CreateItemType();
$request->SendMeetingInvitations = CalendarItemCreateOrDeleteOperationType::SEND_TO_NONE;
$request->Items = new NonEmptyArrayOfAllItemsType();

$event = new CalendarItemType();
$event->Start = $appointment->start_at;
$event->End = $appointment->end_at;
$event->Subject = $appointment->name;
$event->Body = new BodyType();
$event->Body->_ = $appointment->description;
$event->Body->BodyType = BodyTypeType::HTML;
$event->Location = $location;

$request->Items->CalendarItem[] = $event;
$response = $client->CreateItem($request);

The appointment is not entered into the calendar. If I add required attendees it is put into the calendar, but only as a meeting request that needs to be confirmed, which is not what we want.
@cjmozart you say you set the Traversal-property, but I doesn't seem to exist on the CreateItemType. Could you tell me how you solved this?

**Comment by Matlepirate2b** [comment]
Hi,
I have the same problem, the event is entered when i put SEND_ONLY_TO_ALL but when i put SEND_TO_NONE : no event created.
Can you help us ?

This is my code : 
use \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Request\CreateItemType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfAllItemsType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfAttendeesType;
use \jamesiarmes\PhpEws\Enumeration\BodyTypeType;
use \jamesiarmes\PhpEws\Enumeration\CalendarItemCreateOrDeleteOperationType;
use \jamesiarmes\PhpEws\Enumeration\ResponseClassType;
use \jamesiarmes\PhpEws\Enumeration\RoutingType;
use \jamesiarmes\PhpEws\Type\AttendeeType;
use \jamesiarmes\PhpEws\Type\BodyType;
use \jamesiarmes\PhpEws\Type\CalendarItemType;
use \jamesiarmes\PhpEws\Type\EmailAddressType;


$host = 'outlook.office365.com';
$username = 'xxxxxxxxxxx';
$password = 'xxxxxxxxxx';
$version = Client::VERSION_2016;
$client = new Client($host, $username, $password, $version);
$request = new CreateItemType();
$request->SendMeetingInvitations = CalendarItemCreateOrDeleteOperationType::SEND_TO_NONE;
$request->Items = new NonEmptyArrayOfAllItemsType();
$event = new CalendarItemType();
$event->RequiredAttendees = new NonEmptyArrayOfAttendeesType();
$event->Start = $start->format('c');
$event->End = $end->format('c');
$event->Subject = 'EWS Test Event 2';
$event->Body = new BodyType();
$event->Body->_ = 'This is the event body';
$event->Body->BodyType = BodyTypeType::TEXT;
$event->RequiredAttendees->Attendee[0]->Mailbox->EmailAddress = 'xxxxxxxxx';
$request->Items->CalendarItem[] = $event;
$response = $client->CreateItem($request);
