### ISSUE TITLE
Calendar Item Title not saved

### ISSUE THREAD

**Issue by manttih** [jamesiarmes/php-ews#392]
Hello!
I have been looking into this great code, as I am building a booking system. 
However, I noticed that when creating a calendar event, The title isn't saved (I used the example code event/create). I looked into ItemType.php and CalendarItemType.php and didnt find property title... Am I doing something wrong or is this a bug?

Relevant Code:

// Build the event to be added.
$event = new CalendarItemType();
$event->RequiredAttendees = new NonEmptyArrayOfAttendeesType();
$event->Start = $start->format('c');
$event->End = $end->format('c');
$event->title = 'EWS Test Event'; //THIS ISN'T SAVED ON EXCHANGE CALENDAR.

Starttime and Endtime and Description all work like charm!

**Comment by jamesiarmes** [comment]
In the future, please fill out the issue template that is provided in full.

This is an issue in the example, the title line should actually be:

```php
$event->Subject = 'EWS Test Event';
```

I have fixed the example in d9cfd4b85bd2cd138e218ec1796ed30ce9ceccc7 and it will be included in the next beta release. Thank you for your report.
