### ISSUE TITLE
HTTP vs Command Line | Uncaught SoapFault exception

### ISSUE THREAD

**Issue by ChuckTSI** [jamesiarmes/php-ews#395]
Version (e.g. 1.0, dev-master): 1.0 dev-master

Microsoft Exchange version: 2007

Description of problem:

When running the following script through browser (Apache/Linux) it runs fine and retrieves the information.  When I try to run it via command line 

`/usr/bin/php /path/to/script.php`

I get an Uncaught SoapFault exception (see below)

**Example request:**

```
require_once('autoload.php');

use \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Request\FindItemType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfBaseFolderIdsType;
use \jamesiarmes\PhpEws\Enumeration\DefaultShapeNamesType;
use \jamesiarmes\PhpEws\Enumeration\DistinguishedFolderIdNameType;
use \jamesiarmes\PhpEws\Enumeration\ResponseClassType;
use \jamesiarmes\PhpEws\Type\CalendarViewType;
use \jamesiarmes\PhpEws\Type\DistinguishedFolderIdType;
use \jamesiarmes\PhpEws\Type\ItemResponseShapeType;

$start_date = new DateTime("January 19 00:00:00");
$end_date = new DateTime("January 19 23:59:59");
$timezone = 'Eastern Standard Time';

// Set connection information.
$host = 'domain.com';
$username = 'user@domain.com';
$password = 'supersecretpassword!';
$version = Client::VERSION_2007;

$client = new Client($host, $username, $password, $version);
$client->setTimezone($timezone);

$request = new FindItemType();
$request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();
$request->Traversal = "Shallow";

// Return all event properties.
$request->ItemShape = new ItemResponseShapeType();
$request->ItemShape->BaseShape = DefaultShapeNamesType::ALL_PROPERTIES;

// Create list of all rooms for PHP-EWS (ARRAY)
$rooms[] = 'roomname@domain.xx';

foreach($rooms AS $value){

	$request = new FindItemType();
	$request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();
	$request->Traversal = "Shallow";

	// Return all event properties.
	$request->ItemShape = new ItemResponseShapeType();
	$request->ItemShape->BaseShape = DefaultShapeNamesType::ALL_PROPERTIES;

	$folder_id = new DistinguishedFolderIdType();
	$folder_id->Id = DistinguishedFolderIdNameType::CALENDAR;	

	$folder_id->Mailbox->EmailAddress = $value;
	$request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;
	
	$request->CalendarView = new CalendarViewType();
	$request->CalendarView->StartDate = $start_date->format('c');
	
	$request->CalendarView->EndDate = $end_date->format('c');

	$response = $client->FindItem($request);

	// Iterate over the results, printing any error messages or event ids.
	$response_messages = $response->ResponseMessages->FindItemResponseMessage;
	foreach ($response_messages as $response_message) {
		// Make sure the request succeeded.
		if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
			$message = $response_message->ResponseCode;
			echo "Failed to search for events with \"$message\"\n";
			continue;
		}
		
		// Iterate over the events that were found, printing some data for each.
		$items = $response_message->RootFolder->Items->CalendarItem;
		foreach ($items as $item) {				
			print "<pre>";
			print_r($item);
			print "</pre>";	
		}		
	}
}
```

Example response:

Apache/Linux HTTP access: 
No errors. Retrieves all room bookings

Linux Command Line:  
Fatal error: Uncaught SoapFault exception: [a:ErrorSchemaValidation] The request failed schema validation: The 'StartDate' attribute is invalid - The value '2017' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:dateTime' - The string '2017' is not a valid DateTime value. in /home/intellek/_custom/ews/php-ews/php-ews/src/Client.php:1631
Stack trace:
#0 /home/intellek/_custom/ews/php-ews/php-ews/src/Client.php(1631): SoapClient->__call('FindItem', Array)
#1 /home/intellek/_custom/ews/php-ews/php-ews/src/Client.php(1631): jamesiarmes\PhpNtlm\SoapClient->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType))
#2 /home/intellek/_custom/ews/php-ews/php-ews/src/Client.php(670): jamesiarmes\PhpEws\Client->makeRequest('FindItem', Object(jamesiarmes\PhpEws\Request\FindItemType))
#3 /home/intellek/_custom/ews/sicotte.cron.php(75): jamesiarmes\PhpEws\Client->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType))
#4 {main}
  thrown in /home/intellek/_custom/ews/php-ews/php-ews/src/Client.php on line 1631

Additional details:

**Comment by jamesiarmes** [comment]
I've run your code via cli and had no issues. The exception indicates that the `StartDate` value is "2017", which is an invalid value. In the code you provided, the value seems to be formatted properly and, as I said, worked without issue for me. I would suggest first wrapping the actual operation call in a try/catch block to get the actual XML from the request. For example:

```php
try {
    $response = $client->FindItem($request);
} catch (\SoapFault $e) {
    $soap = $client->getClient();
    $request_xml = $soap->__getLastRequest();
}
```

This will allow you to determine if the `StartDate` is actually being set to "2017" and from there you can attempt to determine why.

**Comment by ChuckTSI** [comment]
Thanks for the tip.  

**Via HTTP:** 

This is the $request object before being processed 
```
[CalendarView] => jamesiarmes\PhpEws\Type\CalendarViewType Object
        (
            [EndDate] => 2017-01-19T23:59:59-08:00
            [StartDate] => 2017-01-19T00:00:00-08:00
            [MaxEntriesReturned] => 
        )

```
Once run though: $response = $client->FindItem($request), this is the response:
[__last_response] => NoErrorIPM.Appointment[ALL ROOM DATA HERE]


**Via command line**

This is the $request object before being processed 
```
[CalendarView] => jamesiarmes\PhpEws\Type\CalendarViewType Object
        (
            [EndDate] => 2017-01-19T23:59:59-08:00
            [StartDate] => 2017-01-19T00:00:00-08:00
            [MaxEntriesReturned] =>
        )
```

Once run though: $response = $client->FindItem($request);
```
[__last_response] => <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:ns2="http://schemas.microsoft.com/exchange/services/2006/messages">
   <SOAP-ENV:Header>
      <ns1:RequestServerVersion Version="Exchange2007" />
      <ns1:TimeZoneContext>
         <ns1:TimeZoneDefinition Id="Eastern Standard Time" />
      </ns1:TimeZoneContext>
   </SOAP-ENV:Header>
   <SOAP-ENV:Body>
      <ns2:FindItem Traversal="Shallow">
         <ns2:ItemShape>
            <ns1:BaseShape>AllProperties</ns1:BaseShape>
         </ns2:ItemShape>
         <ns2:CalendarView StartDate="2017" EndDate="2017" />
         <ns2:ParentFolderIds>
            <ns1:DistinguishedFolderId Id="calendar">
               <ns1:Mailbox>
                  <ns1:EmailAddress>room@domain.xx</ns1:EmailAddress>
               </ns1:Mailbox>
            </ns1:DistinguishedFolderId>
         </ns2:ParentFolderIds>
      </ns2:FindItem>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Any ideas on why it would change the StartDate? Maybe something to do with the soapClass?

**Comment by jamesiarmes** [comment]
This sounds like a configuration issue. I'm not sure what would cause the date's to be formatted differently between CLI and CGI modes, but I would start by comparing the different PHP configurations.

**Comment by ChuckTSI** [comment]
Thanks James. If I ever find the issue, will let you know.  Cheers!

**Comment by jamesiarmes** [comment]
I appreciate that. In the meantime, I am closing this issue as problem does not appear to be related to this library.
