### ISSUE TITLE
Inline images not showing up in other mail clients

### ISSUE THREAD

**Issue by erikegon** [jamesiarmes/php-ews#396]
Version (e.g. 1.0, dev-master):
0.1

Microsoft Exchange version:
Exchange Server 2016

Description of problem:
We send email messages with status reports (in email body): a table with red crosses and green checkmarks. The mail shows up perfectly in our Outlook clients, but when sent to customers, they see empty placeholders.

The files are 16x16 pixel png's with the names ok.png and nok.png. They do show up as attachments in Gmail (my test mailbox) and on double-click they do show up correctly. Gmail complains the it cannot find the file.

Images are inserted like this: `<img src="cid:nok">`. The CID is set to "nok" like this:

`...`
`$attachments[$i] = new EWSType_FileAttachmentType();`
`$attachments[$i]->Name = pathinfo($aMailData['attach'][$i],PATHINFO_FILENAME);`
`$attachments[$i]->IsInline = true;`
`$attachments[$i]->Content = file_get_contents($aMailData['attach'][$i]);`
`$attachments[$i]->ContentType = finfo_file(finfo_open(FILEINFO_MIME_TYPE),$aMailData['attach'][$i]);`
`...`

I also tried `PATHINFO_BASENAME` and `<img src="cid:nok.png">` but that didn't work either.

Question: how do I refer inline to the attachments in a way that external mailservers do understand my message and display the images correctly?

Example request:
n/a

Example response:
n/a

Additional details:
When the message is sent to both the organization (Cc) and to the customer (To), our organization see a perfect message, but the customer doesn't. 

Any help or ideas would be appreciated.

**Comment by jamesiarmes** [comment]
When creating your attachment, you need to set the `ContentId` property. You then want to reference that as the cid in your image tag. I've added a [message/create-inline-attachment](https://github.com/jamesiarmes/php-ews/blob/master/examples/message/create-inline-attachment.php) example to demonstrate this.

**Comment by erikegon** [comment]
Hi,

Thanks for looking into my issue.

Can’t believe I’ve overlooked this. Yes, I do know I need to set the ContentId, but somehow it’s not in my code. Thanks for opening my eyes to my own code!

Just tested this and this now also works on my Gmail account.


Met vriendelijke groet,
Erik.

**Comment by jamesiarmes** [comment]
Excellent, glad to be of help!
