### ISSUE TITLE
Constant 401 error resolution

### ISSUE THREAD

**Issue by richardlampitt** [jamesiarmes/php-ews#397]
Version (e.g. 1.0, dev-master):
PHP version: 7
Microsoft Exchange version: 2007

Description of problem:

Constant 401 errors

Example request:

```
object(jamesiarmes\PhpEws\Client)#27 (9) { ["curl_options":protected]=> array(8) { [81]=> bool(false) [64]=> bool(false) [19913]=> bool(true) [84]=> int(2) [107]=> int(1) [10005]=> string(38) "UserName:SuperSecurePassword" [10082]=> string(36) "tmp/username.txt" [10031]=> string(36) "tmp/username.txt" } ["headers":protected]=> array(0) { } ["password":protected]=> string(9) "SuperSecurePassword" ["server":protected]=> string(26) "ServerLocation" ["soap":protected]=> NULL ["timezone":protected]=> NULL ["username":protected]=> string(28) "UserName" ["impersonation":protected]=> NULL ["version":protected]=> string(12) "Exchange2007" } 
```

Example response:

``` 
401 error, not authorized
```

Additional details:

I have resolved this error with the help of one of my colleagues, but I'm creating an issue here so that if someone is searching in the future, they might be able to try this fix: **The username that gets sent to Exchange® might need to include the domain of that user**. e.g. Domain\UserName.

We had been scouring the issues here for hours trying to find a fix for the constant issues we were having, and this advice wasn't present. If you've tried all of the other fixes present in the issues here, it might be fixed by this.

**Comment by dannyweeks** [comment]
I was having this issue too but the resolution was different. The users password contained `£` which it didn't like. After updating to a new password without the £ it worked. Not sure what other symbols wont be accepted but something to consider if you are having this issue.

**Comment by richardlampitt** [comment]
@dannyweeks :: It could be that it's a character encoding issue somewhere along the line, using iso-8859-1 instead of UTF-8. It might well be sending Â£ instead of £, which is common in character encoding issues for that character. Worth checking your database if user details are stored there, exchange and your code to see if that's an issue.

**Comment by TZK-** [comment]
I have the same issue as @dannyweeks. 

When passing a password which contains special characters such as **ù** or **€** ... the librairy always returns a 401 error.

Changing the password could be a solution but for my use case I cannot. 

Still waiting for any real solutions du solve this.
