### ISSUE TITLE
Check connection

### ISSUE THREAD

**Issue by erikegon** [jamesiarmes/php-ews#402]
Version (e.g. 1.0, dev-master): 0.1
PHP version: 5.3.3
Microsoft Exchange version: 2016

Description of problem:
This not a bug-report, I just need an answer.

Currently, our Exchange mailbox is temporarily unavailable. I just don't know how to detect this using php-ews. There isn't a connection-object, is there? The 

`$ews = new ExchangeWebServices(?,?,?,?);`

is just the instatiation of a class. The first attempt to connect to Exchange server to check if new mail has arrived is

`$ews->FindItem(?)`

But that doesn't show an error. It just tells me it retrieved 0 items from the inbox. Doing the (sort of) same in Powershell, an error message is thrown:

`Exception calling FindItems with 3 argument(s): "The mailbox database is temporarily unavailable.`
`Cannot open mailbox /o=Hotitem/ou=First Administrative Group/cn=Recipients/cn=servicedesk.`
`At line:9 char:3`
`+   $exchangeService.FindItems($folder, $null, $view)  | ft DisplayTo,D ...`
`+`
 `~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException`
`    + FullyQualifiedErrorId : ServiceResponseException`

Q: How do I check if a connection can be established succesfully?

Thanks for taking the time.
Erik.

**Comment by DuyguC** [comment]
How did you manage to connect to Exchange Server 2016 with php-ews 0.1 What version number did you use? Could you share your connection code ?

**Comment by erikegon** [comment]
The point is that I do not exactly know what you mean. Or perhaps you mean the variables set in the connection object:

   `$oEws = new ExchangeWebServices($aMailConn['mailserver'], $aMailConn['username'], $aMailConn['password'], ExchangeWebServices::VERSION_2010_SP2);`

But this code doesn't actually connect to the server, it's just a bunch of variables and methods. Corrrect me if I'm wrong.

**Comment by jamesiarmes** [comment]
0.1 is not supported. I recommend updating to the latest beta, which includes support for Exchange 2016.

EWS does not implement a connection check or status operation. It sounds like you were able to establish a connection, as you received a response rather than a `SoapFault`, so any improvised connection check would have succeeded in this case. Does the `ResponseClass` indicate success or error?

**Comment by erikegon** [comment]
Yes, you are right. I just count the number of items retrieved, instead of checking the responseClass. This is the object returned (I compressed it a bit):

`[ResponseMessages] => stdClass Object (`
`  [FindItemResponseMessage] => stdClass Object (`
`    [MessageText] => The mailbox database is temporarily unavailable., Cannot open mailbox /o=<companyname>/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=<accountname>.`
`    [ResponseCode] => ErrorMailboxStoreUnavailable`
`    [DescriptiveLinkKey] => 0`
`    [ResponseClass] => Error`
`  )`
`)`

ErrorHandling ...
