### ISSUE TITLE
Problem with ClassMap::getMap() and SoapClient

### ISSUE THREAD

**Issue by talalong** [jamesiarmes/php-ews#403]
Version (e.g. 1.0, dev-master):
PHP version:
Microsoft Exchange version:
First I have to thank you for this amazing project.
Description of problem:
My first problem is that the class _SoapClient_ does not exist within project. So I am not able to use your class _SoapClient_, which is in jamesiarmes\PhpNtlm. And then I have got an idea: Using _NTLMSoapClient_ and _NTLMSoapClient/Exchange.php_ in your old version of _php-ews_, which is __not__ _php-ews-master_. I have not tested it, because i am facing to an other problem, which is my second problem. Could you please guide me how to define the class _ClassMap_? I really appreciate your help. Thank you

Example request:
Im using this:

`include 'NTLMSoapClient/Exchange.php';`

```
 $this->soap = new NTLMSoapClient_Exchange(
            dirname(__FILE__) . '/assets/services.wsdl',
            array(
                'user' => $this->username,
                'password' => $this->password,
                'location' => 'https://' . $this->server . '/EWS/Exchange.asmx',
                'classmap' => ClassMap::getMap(),
                'curlopts' => $this->curl_options,
                'features' => SOAP_SINGLE_ELEMENT_ARRAYS,
            )
        );
```

instead of this:
```
$this->soap = new SoapClient(
            dirname(__FILE__) . '/assets/services.wsdl',
            array(
                'user' => $this->username,
                'password' => $this->password,
                'location' => 'https://' . $this->server . '/EWS/Exchange.asmx',
                'classmap' => ClassMap::getMap(),
                'curlopts' => $this->curl_options,
                'features' => SOAP_SINGLE_ELEMENT_ARRAYS,
            )
        );
```

Example response:

> Fatal error: Class 'ClassMap' not found in C:\xampp\htdocs\php-ews-master\src\Client.php on line 1620

Additional details:

**Comment by jamesiarmes** [comment]
The `ClassMap` class is defined within the library. If you are using composer to install the package, as per the installation instructions, it's autoloader should find it for you as well as those of installed dependencies (such as php-ntlm). If you are not using composer, you will need to implement your own autoloader and install dependencies in the same manner.

**Comment by talalong** [comment]
Thanks for your answer. I have never used composer before, but I will try to install all these packages with composer.
Please just don't close this issue for now.
