### ISSUE TITLE
problem with timezone - setTimeZone() - calendar

### ISSUE THREAD

**Issue by talalong** [jamesiarmes/php-ews#409]
Version (e.g. 1.0, dev-master):
PHP version:
Microsoft Exchange version:
Exchange 2016
Description of problem:
How can I change timezone to "Central European Time". I actually supposed to use `setTimeZone()`, but 
this opration wont work. The error seems to be that the timezone could not be identified. 
That code below will work if I escape `$client->setTimezone($timezone);`, but i am going to get other times (like an hour earlier) from standard timezone.
Please help!
Example request:

```php
$client = new Client($host, $username, $password, $version);
$client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));

$start_date = new DateTime('l j 00:00:00');
$end_date = new DateTime('December 31 23:59:59');

$timezone = 'Central European Time';
$client->setTimezone($timezone);

$request = new FindItemType();
$request->ParentFolderIds = new NonEmptyArrayOfBaseFolderIdsType();

// Return all event properties.
$request->ItemShape = new ItemResponseShapeType();
$request->ItemShape->BaseShape = DefaultShapeNamesType::ALL_PROPERTIES;

$folder_id = new DistinguishedFolderIdType();
$folder_id->Id = DistinguishedFolderIdNameType::CALENDAR;
$request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;

$request->CalendarView = new CalendarViewType();
$request->CalendarView->StartDate = $start_date->format('c');
$request->CalendarView->EndDate = $end_date->format('c');

$response = $client->FindItem($request);
$response_messages = $response->ResponseMessages->FindItemResponseMessage;
foreach ($response_messages as $response_message) {
    if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
        $code = $response_message->ResponseCode;
        $message = $response_message->MessageText;
        fwrite(
                STDERR, "Failed to search for events with \"$code: $message\"\n"
        );
        continue;
    }
    $items = $response_message->RootFolder->Items->CalendarItem;
    foreach ($items as $item) {
        $id = $item->ItemId->Id;
        $change_key = $item->ItemId->ChangeKey;
        $title = $item->Subject;
        $start = new DateTime($item->Start);
        $end = new DateTime($item->End);
        $guest = $item->DisplayTo;
        var_dump($item);
    }
```
Example response:

```
Fatal error: Uncaught SoapFault exception: [a:ErrorTimeZone] Timezone with the specified ID not found. in C:\xampp\htdocs\bbs\vendor\php-ews\php-ews\src\Client.php:1524 Stack trace: #0 C:\xampp\htdocs\bbs\vendor\php-ews\php-ews\src\Client.php(1524): SoapClient->__call('FindItem', Array) #1 C:\xampp\htdocs\bbs\vendor\php-ews\php-ews\src\Client.php(1524): jamesiarmes\PhpNtlm\SoapClient->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType)) #2 C:\xampp\htdocs\bbs\vendor\php-ews\php-ews\src\Client.php(631): jamesiarmes\PhpEws\Client->makeRequest('FindItem', Object(jamesiarmes\PhpEws\Request\FindItemType)) #3 C:\xampp\htdocs\bbs\app\getMyEvent.php(54): jamesiarmes\PhpEws\Client->FindItem(Object(jamesiarmes\PhpEws\Request\FindItemType)) #4 {main} thrown in C:\xampp\htdocs\bbs\vendor\php-ews\php-ews\src\Client.php on line 1524
```

Additional details:

**Comment by jamesiarmes** [comment]
Are you certain that's the proper id for the timezone? Have you used the `GetServerTimeZonesType` operation to confirm that your Exchange server includes the definition for the timezone?

**Comment by jlardinois** [comment]
Here is ID code for timezone  (examples/system/timezone-definitions.php)
(UTC-01:00) Azores - Id: Azores Standard Time
(UTC-01:00) Cape Verde Is. - Id: Cape Verde Standard Time
(UTC) Coordinated Universal Time - Id: UTC
(UTC+00:00) Casablanca - Id: Morocco Standard Time
(UTC+00:00) Dublin, Edinburgh, Lisbon, London - Id: GMT Standard Time
(UTC+00:00) Monrovia, Reykjavik - Id: Greenwich Standard Time
(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna - Id: W. Europe Standard Time
(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague - Id: **Central Europe Standard Time**
(UTC+01:00) Brussels, Copenhagen, Madrid, Paris - Id: Romance Standard Time
(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb - Id: Central European Standard Time
(UTC+01:00) West Central Africa - Id: W. Central Africa Standard Time
(UTC+01:00) Windhoek - Id: Namibia Standard Time

**Comment by talalong** [comment]
OMG! you guys just save my life ;) sorry for my stupid question. I spent 2 days to look for these Ids.
many thanks.
