### ISSUE TITLE
How to get available times of meeting room?

### ISSUE THREAD

**Issue by talalong** [jamesiarmes/php-ews#410]
Version (e.g. 1.0, dev-master):
PHP version: 5.6.28
Microsoft Exchange version: Exchange 2016

Description of problem:
I am trying to get all free times of a conference room and have found a operation calls `FindAvailableMeetingTimes`. But this feature has not been added to php-ews. So I have tried to find all events that take place in a same room and played with `start` and `end` times in order to figure out, where free times are. Is there better way to do this?

**Comment by jamesiarmes** [comment]
Where did you find the `FindAvailableMeetingTimes` operation? I don't see it in the documentation. Have you tried using the `GetUserAvailability` operation with the room set as the mailbox rather than a user? I'm not sure if that will work and I don't have a place I can test that but that's where I would start.

**Comment by talalong** [comment]
@jamesiarmes a list of operations that are supposed to be implemented in ews, located in php-ews/src/assets/services.wsdl file. And yes, I have also tried using `GetUserAvailability`, but basically this operation works like `FindItemRequest` operation, which was used in #406. `GetUserAvailability` returns only busy times, not available times. Here is my code (actually your sample code ;))
```
$email = 'conference.room@mail.com';
$start = new DateTime('today 00:00:00');
$end = new DateTime('today 23:59:59');
$timezone = 'Central Europe Standard Time';
$client = new Client($host, $username, $password, $version);
$client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));
$client->setTimezone($timezone);
// Build the request.
$request = new GetUserAvailabilityRequestType();
$request->FreeBusyViewOptions = new FreeBusyViewOptionsType();
$request->MailboxDataArray = new ArrayOfMailboxData();

// Define the time window and details to return.
$request->FreeBusyViewOptions->TimeWindow = new Duration();
$request->FreeBusyViewOptions->TimeWindow->StartTime = $start->format('c');
$request->FreeBusyViewOptions->TimeWindow->EndTime = $end->format('c');
$request->FreeBusyViewOptions->MergedFreeBusyIntervalInMinutes = '30';
$request->FreeBusyViewOptions->RequestedView = FreeBusyViewType::DETAILED;

// Add the user to get availability for.
$mailbox = new MailboxData();
$mailbox->Email = new EmailAddressType();
$mailbox->Email->Address = $email;
$mailbox->Email->RoutingType = 'SMTP';
$mailbox->AttendeeType = 'Required';
$mailbox->ExcludeConflicts = false;
$request->MailboxDataArray->MailboxData[] = $mailbox;

$response = $client->GetUserAvailability($request);
print'<pre>';
print_r($response);
print'</pre>';
```

**Comment by jamesiarmes** [comment]
I see it now, it must have been added in Exchange 2016 which is lacking in documentation. I'll add an issue to add it, but I probably won't be able to get to it until after 1.0.0 stable is released.

`GetUserAvailability` can can show free times by using `SuggestionsViewOptions` rather than `FreeBusyViewOptions`. See the [user/meeting-suggestions](https://github.com/jamesiarmes/php-ews/blob/master/examples/user/meeting-suggestions.php) example.

**Comment by talalong** [comment]
Okay. By using `SuggestionsViewOptions` I am not able to adjust meeting duration, which is set by default `$meeting_duration= 60`. But the result does not change, when I change it to 100 or 120.
meeting duration is neither 60 min nor 100 min. Is 30 min
Here is what I have got:

> 00:00

00:30

01:00

01:30

. . .

**Comment by jamesiarmes** [comment]
That's correct, Exchange will return you suggested meeting start times, in 30 minute increments, in which the user (or room) is available that fit within your duration. So you could schedule your meeting for any of those times, with the duration you specified, and it should be free for the duration of your meeting.

For example, say your working hours are configured for 08:00 to 17:00 and you have a meeting scheduled from 13:30 to 14:30, you should receive the following suggested meeting times:

> 08:00
> 08:30
> 09:00
> 09:30
> 10:00
> 10:30
> 11:00
> 11:30
> 12:00
> 12:30
> 14:30
> 15:00
> 15:30
> 16:00

Notice that 13:00 is missing because there is a meeting scheduled at 13:30 and you specified 60 minutes for your meeting duration. Similarly, 16:30 is missing because that leaves only 30 minutes until the end of the work day.

**Comment by talalong** [comment]
Thanks for your nice explaination. But I just realize that Its showing me the results only from 0:00 to 11:30, although my working time was set up from 7:00 to 17:00. 
```
$email = 'conference.room@mail.com';
$start = new DateTime('next tuesday 00:00:00');
$end = new DateTime('next wednesday 00:00:00');
$meeting_duration = 60;
$timezone = 'Central Europe Standard Time';
$client = new Client($host, $username, $password, $version);
$client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));
$client->setTimezone($timezone);
$request = new GetUserAvailabilityRequestType();
$request->MailboxDataArray = new ArrayOfMailboxData();

$request->SuggestionsViewOptions = new SuggestionsViewOptionsType();
$request->SuggestionsViewOptions->MaximumNonWorkHourResultsByDay = 0;
$request->SuggestionsViewOptions->MeetingDurationInMinutes = $meeting_duration;
$request->SuggestionsViewOptions->MinimumSuggestionQuality = SuggestionQuality::EXCELLENT;

$duration = new Duration();
$duration->StartTime = $start->format('Y-m-d');
$duration->EndTime = $end->format('Y-m-d');
$request->SuggestionsViewOptions->DetailedSuggestionsWindow = $duration;
$mailbox = new MailboxData();
$mailbox->Email = new EmailAddressType();
$mailbox->Email->Address = $email;
$mailbox->Email->RoutingType = 'SMTP';
$mailbox->AttendeeType = 'Required';
$mailbox->ExcludeConflicts = false;
$request->MailboxDataArray->MailboxData[] = $mailbox;
$response = $client->GetUserAvailability($request);
$response_message = $response->SuggestionsResponse->ResponseMessage;
//var_dump($response_message);
if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
    $code = $response_message->ResponseCode;
    $message = $response_message->MessageText;
    fwrite(
        STDERR,
        "Failed to get user availability with \"$code: $message\"\n"
    );
    exit;
}
$suggestion_days = $response->SuggestionsResponse->SuggestionDayResultArray;
foreach ($suggestion_days->SuggestionDayResult as $day) {
    $date = new DateTime($day->Date);
    $output = 'Available meeting times for ' . $date->format('Y-m-d:') . "\n";
   fwrite(STDOUT, $output);
    foreach ($day->SuggestionArray->Suggestion as $suggestion) {
        $time = new DateTime($suggestion->MeetingTime); 
        fwrite(STDOUT, '- ' . $time->format('H:i') . "\n");    
    }
}
```

Here is what I got:

> Available meeting times for 2017-02-21:
> 00:00
> 00:30
> 01:00
> 01:30
> 02:00
> 02:30
> 03:00
> 03:30
> 04:00
> 04:30
> 05:00
> 05:30
> 06:00
> 06:30
> 07:00
> 07:30
> 08:00
> 08:30
> 09:00
> 09:30
> 10:00 
> 10:30
> 11:00
> 11:30

**Comment by talalong** [comment]
Hi @jamesiarmes do you have any idea, where the problem could be?

**Comment by robp2175** [comment]
@talalong I am trying to do the exact same thing as you. Did you ever get a working example going? If you would be so kind as to share what you have, I would really appreciate it.

**Comment by talalong** [comment]
@robp2175 it seems to be bug. But I have found another way to work around this using `FindItem`. There will be an array of meeting times. Using these given times I am able to calculate the suggested meetings (free times). If you want, I can post my own calculation here.

**Comment by robp2175** [comment]
I would really appreciate that @talalong

**Comment by talalong** [comment]
Here is my code. But in my opinion It looks very ugly and unprofessional. And I have to say that I have no idea, what I have written. :(
`   $username = USER_EXCHANGE;
    $password = PASS_EXCHANGE;
    $host = EXCHANGE_SERVER;
    $version = Client::VERSION_2016;
    $isAllDayEvent = false;
    $client = new Client($host, $username, $password, $version);
    $client->setCurlOptions(array(CURLOPT_SSL_VERIFYPEER => false));

    $email_room = "conference.room@maill.com";
    $date = "20.05.2017";
    $start_date = new DateTime($date . '00:00:00'); //working time start
    $end_date = new DateTime($date . '23:59:00'); //working time end

    $timezone = 'Central Europe Standard Time';
    $client->setTimezone($timezone);
    $request = new FindItemType();
    $request->Traversal = ItemQueryTraversalType::SHALLOW;
    $request->ItemShape = new ItemResponseShapeType();
    $request->ItemShape->BaseShape = DefaultShapeNamesType::ALL_PROPERTIES;

    $request->CalendarView = new CalendarViewType();
    $request->CalendarView->StartDate = $start_date->format('c');
    $request->CalendarView->EndDate = $end_date->format('c');
    $folder_id = new DistinguishedFolderIdType();
    $folder_id->Id = DistinguishedFolderIdNameType::CALENDAR;
    $folder_id->Mailbox = new EmailAddressType();
    $folder_id->Mailbox->EmailAddress = $email_room;
    $request->ParentFolderIds->DistinguishedFolderId[] = $folder_id;
    $response = $client->FindItem($request);
    $response_messages = $response->ResponseMessages->FindItemResponseMessage;
          //var_dump($response_messages);
    foreach ($response_messages as $response_message) {
// Make sure the request succeeded.
        if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
            $code = $response_message->ResponseCode;
            $message = $response_message->MessageText;
//        fwrite(
//                STDERR, "Failed to search for events with \"$code: $message\"\n"
//        );
            echo $message;
            continue;
        }
// Iterate over the events that were found, printing some data for each.
        $busy_stuff = $response_message->RootFolder->Items->CalendarItem;

        $open_time = $start_date->format("H:i");
        $close_time = $end_date->format("H:i");
        if (count($busy_stuff) === 0) {
//here is my own code
            $events_result = build_free_array(get_minutes(roundTime($open_time), $close_time), $end_date->format('d.m.Y'));
        } else {
            for ($i = 0; $i < count($busy_stuff); $i++) {
                $start = new DateTime($busy_stuff[$i]->Start);
                $end = new DateTime($busy_stuff[$i]->End);
                $id = $busy_stuff[$i]->ItemId->Id;
                $change_key = $busy_stuff[$i]->ItemId->ChangeKey;
                $title = $busy_stuff[$i]->Subject;
                $guest = $busy_stuff[$i]->DisplayTo;
                $event_date = $end->format("d.m.Y");
                if ($i > 0) {
                    $end_past = new DateTime($busy_stuff[$i - 1]->End);
                }
                if ($i === 0) {
                    if ($open_time < $start->format("H:i")) {
                        $events_result = build_free_array(get_minutes(roundTime($open_time), $start->format("H:i")), $end_date->format('d.m.Y'));
                    }
                    $events_result[] = [
                        "id" => $id,
                        "change_key" => $change_key,
                        "title" => $title,
                        "start" => $start->format("H:i"),
                        "end" => $end->format("H:i"),
                        "date" => $event_date
                    ];
                    if ($busy_stuff[$i]->IsAllDayEvent&& $end->format('d.m.Y') !== $date) {
                        $isAllDayEvent = true;
                        break;
                    }
                } elseif ($end_past->format("H:i") !== $start->format("H:i")) {
                    $events_result = array_merge($events_result, build_free_array(get_minutes(roundTime($end_past->format("H:i")), $start->format("H:i")), $end_date->format('d.m.Y')));
                    $events_result[] = [
                        "id" => $id,
                        "change_key" => $change_key,
                        "title" => $title,
                        // "guest" => $guest,
                        "start" => $start->format("H:i"),
                        "end" => $end->format("H:i"),
                        "date" => $event_date
                    ];
                } else {
                    $events_result[] = [
                        "id" => $id,
                        "change_key" => $change_key,
                        "title" => $title,
                        // "guest" => $guest,
                        "start" => $start->format("H:i"),
                        "end" => $end->format("H:i"),
                        "date" => $event_date
                    ];
                }
            }
            if (!$isAllDayEvent) {
                $events_result = array_merge($events_result, build_free_array(get_minutes(roundTime($events_result[count($events_result) - 1]["end"]), $close_time), $end_date->format('d.m.Y')));
            }
        }
    }

  $today_stamp = strtotime(date('d.m.Y'));
foreach ($events_result as $value) {
    if ((strtotime($value["date"]) === $today_stamp && date('H:i') < $value["end"] && isset($value["change_key"])) || (!isset($value["change_key"]) && date("H:i") < $value["start"]) || strtotime($value["date"]) > $today_stamp) {

        $final_result[] = $value;
    }
}
    if (isset($final_result) && count($final_result) > 0) {
        echo json_encode($final_result, JSON_FORCE_OBJECT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    } else {
        $final_result[] = "null";
        echo json_encode($final_result, JSON_FORCE_OBJECT);
    }
}

function build_free_array($array_free, $dateParam) {
    $result = [];
    $date = new DateTime($dateParam);
    for ($i = 0; $i < count($array_free) - 1; $i++) {
        $result [] = [
            "title" => "frei",
            "start" => $array_free[$i],
            "end" => $array_free[$i + 1],
            "date" => $date->format('d.m.Y')
        ];
    }
    return $result;
}

function get_minutes($start, $end) {
    while (strtotime($start) <= strtotime($end)) {
        $minutes[] = date("H:i", strtotime("$start"));

        $start = date("H:i", strtotime("$start + 30 mins"));
        if ($start === "23:30") {
            $minutes[] = $start;
            break;
        }
    }
    return $minutes;
}

function roundTime($timeString) {
    $time = strtotime($timeString);
    $round = 30 * 60;
    $rounded = ceil($time / $round) * $round;
    return date("H:i", $rounded);
}`
