### ISSUE TITLE
Cancelations emails not sending after deleting event

### ISSUE THREAD

**Issue by Sajgoniarz** [jamesiarmes/php-ews#413]
Version (e.g. 1.0, dev-master):
PHP version: 5.6
Microsoft Exchange version:  Microsoft hosting, so i think its 2016, i cant access version through PowerShell

Description of problem:
Participants don't receive cancelation emails. Meeting is deleted, but none of users is informed about.

Example request:

```php

use jamesiarmes\PhpEws\Request;
use jamesiarmes\PhpEws\Enumeration;
use jamesiarmes\PhpEws\Type;
use jamesiarmes\PhpEws\ArrayType;

public function deleteEvent($eventId, $changeKey, $serviceRoomIdList){

    if($eventId === null) return false;

    $request = new Request\DeleteItemType();
    $request->ItemIds = new ArrayType\NonEmptyArrayOfBaseItemIdsType();
    $request->ItemIds->ItemId = new Type\ItemIdType();
    $request->ItemIds->ItemId->Id = $eventId;
    $request->ItemIds->ItemId->ChangeKey = $changeKey; 

    $request->DeleteType = Enumeration\DisposalType::MOVE_TO_DELETED_ITEMS;

    $request->SendMeetingCancellations = Enumeration\CalendarItemCreateOrDeleteOperationType::SEND_ONLY_TO_ALL;

    $response = $this->ews->DeleteItem($request);

    return $response->ResponseMessages->DeleteItemResponseMessage->ResponseClass == 'Success';
}

```

Request object :

```
object(jamesiarmes\PhpEws\Request\DeleteItemType)[42]
  public 'AffectedTaskOccurrences' => null
  public 'DeleteType' => string 'MoveToDeletedItems' (length=18)
  public 'ItemIds' => 
    object(jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfBaseItemIdsType)[43]
      public 'ItemId' => 
        object(jamesiarmes\PhpEws\Type\ItemIdType)[40]
          public 'ChangeKey' => string 'DwA(...)Ll' (length=40)
          public 'Id' => string 'AAA(...)BAAA=' (length=160)
      public 'OccurrenceItemId' => null
      public 'RecurringMasterItemId' => null
  public 'SendMeetingCancellations' => string 'SendOnlyToAll' (length=13)
  public 'SuppressReadReceipts' => null
```

Example response:

```
object(stdClass)[45]
  public 'ResponseMessages' => 
    object(stdClass)[46]
      public 'DeleteItemResponseMessage' => 
        object(stdClass)[47]
          public 'ResponseCode' => string 'NoError' (length=7)
          public 'ResponseClass' => string 'Success' (length=7)
```

Additional details:

Service is set do default settings, events are added from Outlook

**Comment by Sajgoniarz** [comment]
Unfortunately that's not a library issue, its something in Exchange ;/ If i'll find solution I'll post it here for other :D

**Comment by talalong** [comment]
@Sajgoniarz I use the same code and it works for me. Pls dont forget to close this issue, if you dont need it anymore. :)

**Comment by Sajgoniarz** [comment]
@talalong Haha, maybe you will give me your MS settings :D? Don't worry, I'll close it as soon as i get any satisfying response from MS staff. :) Also I visit GH more frequently than MS forum, so it is my reminder :D

**Comment by talalong** [comment]
@Sajgoniarz I wish I could. But I have no right to do this, because I have no account administrator. I am really disappointed, because MS is like turning their back to php developer. So many thanks to James.

**Comment by Sajgoniarz** [comment]
Ok i got update from MS. As room administrator you CAN'T DELETE room reservation with notifying organizer, but instead of it you CAN CANCEL it. If you cancel it organizer will receive email, but still you can't delete that appointment from organizer calendar.
