### ISSUE TITLE
Broken link in RSS feed

### ISSUE THREAD

**Issue by happyoniens** [jamesiarmes/php-ews#419]
In my RSS feeder I get redirected to: 

http://jamesarmes.com/php-ews/php-ews/update/2017/03/02/update.html

This gets me an 404 error. When I select the post through the website I get the link:

http://jamesarmes.com/php-ews/update/2017/03/02/update.html

So there is one `php-ews/` too much in the URL from the RSS feed.

**Comment by jamesiarmes** [comment]
This has been resolved, thanks!
