### ISSUE TITLE
Update contact emails and get the last contact updated

### ISSUE THREAD

**Issue by Cracs22** [jamesiarmes/php-ews#420]
Version (e.g. 1.0, dev-master):
PHP version: PHP 5.5

Description of problem:

I'm trying to update a contact. The contact already have 3 emails, so I have an array of new emails ($array_of_mails) and I want to replace the first three emails by the three emails saved in exchange contact. Here is my code : 

      $UpdateItem = new EWSType_UpdateItemType();
      $UpdateItem->ConflictResolution = EWSType_ConflictResolutionType::ALWAYS_OVERWRITE;
      $change = new EWSType_ItemChangeType();
      $change->ItemId->Id = $update['id'];
     //Update others fields ...

      $i = 1;
      foreach ($array_of_mails as $email) {
            if($i < 4) {
                  $field = new EWSType_SetItemFieldType();
                  $field->IndexedFieldURI->FieldURI = EWSType_UnindexedFieldURIType::CONTACTS_EMAIL_ADDRESSES;
                  $field->IndexedFieldURI->FieldIndex = getEmailKey($i); //Return EWSType_EmailAddressKeyType::EMAIL_ADDRESS_X
                  $field->Contact = new EWSType_ContactItemType();
                  $field->Contact->EmailAddresses = new EWSType_EmailAddressDictionaryType();

                  $mail = new EWSType_EmailAddressDictionaryEntryType();
                  $mail->_ = $email;
                  $mail->Key = getEmailKey($i);
                  $field->Contact->EmailAddresses->Entry = $mail;
                  $change->Updates->SetItemField[] = $field;

                  $i++;
            } else {
                  break;
            }
      }

      $UpdateItem->ItemChanges[] = $change;
      $result = $client->UpdateItem($UpdateItem);

I think the code is ok, but when I execute it, I got an error "SoapFault : The request is invalid".
Do I need to delete  the three emails with (DeleteItemField) before set the three others (SetItemField) ?

Thanks

**Comment by Cracs22** [comment]
For the first question, the code was good, but I don't know if it's a bug but the constant variable "CONTACTS_EMAIL_ADDRESSES" in my version is equal to "contacts:EmailAddresses" but I need to return "contacts:EmailAddress"

`
//const CONTACTS_EMAIL_ADDRESSES = 'contacts:EmailAddresses';

const CONTACTS_EMAIL_ADDRESSES = 'contacts:EmailAddress';
`

I always need help about this question :

**Comment by jamesiarmes** [comment]
A couple of things to address your issue:

First, I see that you're using an old version of the library. I highly recommend updating to the latest release which includes a number of bug fixes.

Second, you're using the wrong constant for your `FieldURI`. You want `\jamesiarmes\PhpEws\Enumeration\DictionaryURIType::CONTACTS_EMAIL_ADDRESS`.

Finally, to address your last question, contacts do not have an updated date. If you want to sync items in Exchange, I recommend using the `SyncFolderItems` operation. There is an example of this for events, see [events/sync](https://github.com/jamesiarmes/php-ews/blob/master/examples/event/sync.php).

**Comment by Cracs22** [comment]
Thanks for the help !

I tried to use the latest version of PHP-EWS but i'm using it on DRUPAL and I don't know why the class aren't loaded. For exemple I call the class "FindItemtype" in my HOOK_libraries_infos but there is a Fatal error : 

Fatal error: Class 'jamesiarmes\PhpEws\Request\BaseRequestType' not found in /usr/share/teamberv3/sites/all/libraries/php-ews-new/src/Request/FindItemType.php on line 14 

I think it's because I don't have any autoload and I don't know how to use it on drupal. The solution will be to call all class one by one but there will be too much class.

Thanks for the `events/sync` class it's really good, but in my version I don't have the field `LastModifiedTime` in the return of the function :(

Thanks

**Comment by jamesiarmes** [comment]
I've used the library in a number of Drupal projects using the [composer_manager](https://www.drupal.org/project/composer_manager) module.

**Comment by Cracs22** [comment]
Ok I downloaded the module and put my composer.json in my "libraries" folder.
I used "composer install" and now I have all the php-ews and php-ntlm" in "sites/all/libraries/vendor" 
To use the lib now I have this code in my `HOOK_libraries_info`  : 

`
function mymoduleexchange_libraries_info() {
    include_once DRUPAL_ROOT . '/sites/all/libraries/vendor/autoload.php';

    $libraries = array(
       'php-ews-master' => array(
            'name' => 'vendor/php-ews-master',
            'vendor url' => 'https://github.com/jamesiarmes/',
            'download url' => 'https://github.com/jamesiarmes/php-ews/archive/master.zip',
            'version' => '1.0',
            'files' => array(
                'php' => array(
                    'vendor/php-ews/php-ews/src/Client.php',
                ),
                //'php' => $phpEWSClass,
            ),
        ),
        'php-ews-client' => array(
            'name' => 'php-ews-client',
            'vendor url' => 'https://github.com/jamesiarmes/php-ntlm/',
            'download url' => 'https://github.com/jamesiarmes/php-ntlm/archive/master.zip',
            'version' => '1.0',
            'files' => array(
                'php' => array(
                    'vendor/jamesiarmes/php-ntlm/src/SoapClient.php',
                ),
            ),
        ),
    );

    return $libraries;
}
`

But when I load my lib and called the "Client" class she isn't found.
Do you know how to use it next ?

**Comment by jamesiarmes** [comment]
I haven't done this with the libraries module. With composer_manager, just add a `composer.json` file to your module, something like so:

```json
{
  "name": "drupal/module_name",
  "description": "Module description.",
  "type": "drupal-module",
  "license": "GPL-2.0",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php-ews/php-ews": "~1.0.0"
  }
}
```

Then run the following drush commands to install or update dependencies. You may be able to do this from the admin UI if you don't have drush, I'm not sure though.

```
drush composer-rebuild
drush composer-manager [install/update]
```

**Comment by Cracs22** [comment]
Yes I can do that, so the "vendor" folder with the 2 libs will be in my module but how you used the lib in your .module file ?
Or maybe you create an external php with all the functionality (functions, use..) and call this external file in one HOOK_init or something like that ?

Thanks

**Comment by jamesiarmes** [comment]
I see you closed this, so I hope you were able to resolve your issue. However, just to be clear, composer_manager does not add a vendor directory to your module. Running `drush composer-rebuild` builds a `composer.json` and `composer.lock` file and places them in your files directory. These composer files will include the dependencies for all modules that define a composer file. Running `drush composer-manager install` installs the dependencies into sites/all/vendor. The composer_manager should handle including the auto-loader in requests.
