### ISSUE TITLE
Find messages on message:ToRecipients

### ISSUE THREAD

**Issue by gserneels** [jamesiarmes/php-ews#421]
I can build a request to find items based on "message:From" or "message:Sender".
But, I want to search in the recipient addresses, I can't get it to work.

How can I search in "message:ToRecipients"?

Thanks!

**Comment by jamesiarmes** [comment]
Closing this issue as it does not conform to the new issue template. If you require assistance, please open a new issue and complete the issue template, including what you've tried and what the results were.
