### ISSUE TITLE
Calendar : Multiple restriction (IsEqualTo and Contains)

### ISSUE THREAD

**Issue by Cracs22** [jamesiarmes/php-ews#424]
Version (e.g. 1.0, dev-master):
PHP version: PHP 5.5

Description of problem:

I'm trying to get the today events with the categories "Tasks" and the word"Test" in the subject.
I saw this issues (https://github.com/jamesiarmes/php-ews/issues/261) but I tried and it not works.
Here is my code (followed your response) Please don't look the form of the code because it's just a test for the moment : 

`

        $FindItem = new EWSType_FindItemType();
        $FindItem->Traversal = EWSType_ItemQueryTraversalType::SHALLOW;
        $FindItem->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;
        $FindItem->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;

        //Construct restriction array
        $condition1 = new EWSType_IsEqualToType();
        $condition1->FieldURI->FieldURI = EWSType_UnindexedFieldURIType::ITEM_CATEGORIES;
        $condition1->FieldURIOrConstant->Constant->Value = 'Tasks';

        //Return today date from midnight
        $start_date = new DateTime($options['start'], new DateTimeZone('Europe/Paris'));
        //Return tomorrow date from midnight
        $end_date = new DateTime($options['end'], new DateTimeZone('Europe/Paris'));

        $condition2 = new EWSType_IsEqualToType();
        $condition2->FieldURI->FieldURI = EWSType_UnindexedFieldURIType::CALENDAR_START;
        $condition2->FieldURIOrConstant->Constant->Value = $start_date->format('c');

        $condition3 = new EWSType_IsEqualToType();
        $condition3->FieldURI->FieldURI = EWSType_UnindexedFieldURIType::CALENDAR_END;
        $condition3->FieldURIOrConstant->Constant->Value = $end_date->format('c');

        $condition4 = new EWSType_ContainsExpressionType();
        $condition4->FieldURI->FieldURI = EWSType_UnindexedFieldURIType::ITEM_SUBJECT;
        $condition4->ContainmentMode = 'Substring';
        $condition4->Constant->Value = 'Test';

        $restriction = new EWSType_RestrictionType();
        $restriction->And = new EWSType_AndType;
        $restriction->And->IsEqualTo = $condition1;
        $restriction->And->And = new EWSType_AndType;
        $restriction->And->And->IsEqualTo = $condition2;
        $restriction->And->And->And = new EWSType_AndType;
        $restriction->And->And->And->IsEqualTo = $condition3;
        $restriction->And->And->And->And = new EWSType_AndType;
        $restriction->And->And->And->And->Contains = $condition4;

        $FindItem->Restriction = $restriction;
        $result = $client->FindItem($FindItem);
`

So if I well understand, to use multiple restrictions I need to put them in "And" or "Or" array but it's not working. Can you please explain me how to use multiple restrictions if it's possible ?

Thanks

**Comment by jamesiarmes** [comment]
You say this didn't work, but you don't say how. Does it throw an error? Not return the expected results? You also didn't specify which version of php-ews you are using.

**Comment by Cracs22** [comment]
I'm using the old version of the lib for the moment.
And yes there is no error but the result of the request isn't what I expect.
This is why I ask if it's the right process to use for multiple restriction ?
