### ISSUE TITLE
[event calendar]Getting null values in array ExtendedProperty

### ISSUE THREAD

**Issue by talalong** [jamesiarmes/php-ews#426]
Version (e.g. 1.0, dev-master):
PHP version: 5.6
Microsoft Exchange version: 2016

Description of problem:
Im trying to retrieve extended property of event, that I have added by creating a new event before.
Using `FindItem` Im able to get that event and its properties, but ExtendedProperty is still null.
here is how I added extended propertey:
Example request:

```php
$property = new ExtendedPropertyType();
$property->ExtendedFieldURI = new PathToExtendedFieldType();
$property->ExtendedFieldURI->PropertyTag = '0x3A11';
$property->ExtendedFieldURI->PropertyType = MapiPropertyTypeType::STRING;
$property->Value = 'Test123';
$event->ExtendedProperty = $property;

$request->Items->CalendarItem[] = $event;
$response = $client->CreateItem($request);
```

Example response:

```
 [ExtendedProperty] => Array
        (
        )
```
Additional details:

**Comment by jamesiarmes** [comment]
Extended properties are not returned by default; you need to add each one you want to your request. See the [event/describe](https://github.com/jamesiarmes/php-ews/blob/master/examples/event/describe.php#L43-L52) example.

**Comment by talalong** [comment]
Okay! I have added `Extended properties` to my `getEvent()`. But It still does not work.
Did I do something wrong here?
```
$property = new PathToExtendedFieldType();
$property->PropertyTag= '0x3A11';
$property->PropertyType = MapiPropertyTypeType::STRING;
$property->DistinguishedPropertySetId = DistinguishedPropertySetType::PUBLIC_STRINGS;
$additional_properties = new NonEmptyArrayOfPathsToElementType();
$additional_properties->ExtendedFieldURI[] = $property;
$request->ItemShape->AdditionalProperties = $additional_properties;
$response = $client->FindItem($request);
```
I got this error:

> The attribute combination of the extended property is invalid.

**Comment by sekjal** [comment]
According to the [Exchange documentation|https://msdn.microsoft.com/en-us/library/office/aa564843(v=exchg.150).aspx], you cannot use DistinguishedPropertySetId with PropertyTag.  I think if dropped the DistinguishedPropertySetId line, it might work...

I'm using PropertyName as my identifier on my application, rather than PropertyTag, so I may be having a different experience.  Hopefully this is helpful

**Comment by talalong** [comment]
@sekjal You were right about `DistinguishedPropertySetId `.
Even I changed `PropertyTag` to `PropertyName`, the problem is still there. I can only see an blank array.
Could you please show me an sample of setting and getting `Extended properties`?

**Comment by sekjal** [comment]
Here's what I'm using:

## Getting
```
$property = new PathToExtendedFieldType();
$property->PropertyName = 'MyPropertyName';
$property->PropertyType = MapiPropertyTypeType::STRING;
$property->DistinguishedPropertySetId = 'Appointment';
$additional_properties = new NonEmptyArrayOfPathsToElementType();
$additional_properties->ExtendedFieldURI[] = $property;
$request->ItemShape->AdditionalProperties = $additional_properties;

$response = $client->FindItem($request);
```
## Setting
```
$event = new CalendarItemType();

$property = new ExtendedPropertyType();
$property->ExtendedFieldURI = new PathToExtendedFieldType();
$property->ExtendedFieldURI->DistinguishedPropertySetId = "Appointment";
$property->ExtendedFieldURI->PropertyName = 'MyPropertyName';
$property->ExtendedFieldURI->PropertyType = MapiPropertyTypeType::STRING;
$property->Value = $MyValue;

$event->ExtendedProperty = $property;

```

**Comment by talalong** [comment]
@sekjal Thanks for your help. but unfortunately it doesn't work either. I am getting the same result.
I think this is not an issue, because your code runs at least on your project
