### ISSUE TITLE
PHP Version issue?

### ISSUE THREAD

**Issue by amoerke** [jamesiarmes/php-ews#428]
Hi James,

thanks again for your library. This helped a lot! I've implemented all functions we need to process events.
All works very well on our staging system (PHP5.6). Now i copied all classes/scripts on the production-system (PHP5.3) and it breaks by making the client request. Are there any known issues in conjunction to that php-version? I'm waiting for error logs of the provider. If i have more details, i'll attach them.

Here are the system information:

Version (e.g. 1.0, dev-master):
PHP version: 5.3
Microsoft Exchange version: 2016

Thanks in advance,
André

**Comment by Sajgoniarz** [comment]
PHP 5.4 or greater is required...

**Comment by jamesiarmes** [comment]
The [dependencies](https://github.com/jamesiarmes/php-ews#dependencies) clearly define PHP 5.4 as the minimum supported version. 5.3 reached end of life in August, 2014, I recommend using 5.6 or newer.
