### ISSUE TITLE
Uncaught RuntimeException: Curl error: SSL certificate problem

### ISSUE THREAD

**Issue by caglaror** [jamesiarmes/php-ews#429]
**Version (e.g. 1.0, dev-master):** dev-master

**PHP version:**  7.0.5

**Microsoft Exchange version:**
VERSION_2016

Description of problem: 
As shown below "SSL sertificate problem". 

Example request:
send.php example in vendor/php-ews sample.

Example response:
```
Fatal error: Uncaught RuntimeException: Curl error: SSL certificate problem: unable to get local issuer certificate in C:\xampp\htdocs\yebesis\vendor\jamesiarmes\php-ntlm\src\SoapClient.php:91 Stack trace: #0 [internal function]: jamesiarmes\PhpNtlm\SoapClient->__doRequest('<?xml version="...', 'https://mail.ti...', 'http://schemas....', 1, 0) #1 C:\xampp\htdocs\yebesis\vendor\php-ews\php-ews\src\Client.php(1631): SoapClient->__call('SendItem', Array) #2 C:\xampp\htdocs\yebesis\vendor\php-ews\php-ews\src\Client.php(1393): jamesiarmes\PhpEws\Client->makeRequest('SendItem', Object(jamesiarmes\PhpEws\Request\SendItemType)) #3 C:\xampp\htdocs\yebesis\test.php(51): jamesiarmes\PhpEws\Client->SendItem(Object(jamesiarmes\PhpEws\Request\SendItemType)) #4 {main} thrown in C:\xampp\htdocs\yebesis\vendor\jamesiarmes\php-ntlm\src\SoapClient.php on line 91
```

Additional details:
No idea

**Comment by Sajgoniarz** [comment]
It's a common issue with CURL at localhost : http://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok

**Comment by caglaror** [comment]
I followed the source you gave. I edited php.ini and add
` curl.cainfo = "C:\xampp\htdocs\yebesis\certs\cacert.pem"`
and restart Apache in local.

Now i am getting another error. 
`Fatal error: Uncaught Error: Class 'CreateItemType' not found in C:\xampp\htdocs\yebesis\test.php:35 Stack trace: #0 {main} thrown in C:\xampp\htdocs\yebesis\test.php on line 35`

PS: Should i open another issue with this err?

**Comment by Sajgoniarz** [comment]
Do you know what for issues are? You make them, when you are 100% sure, that is a library problem. In both cases you wrote PHP beginner problems, not related to library itself.

**Comment by caglaror** [comment]
You are right. This issue should be deleted. But forgive me as i am a beginner. Beginners are just beginners :) 
And it takes time to learn to be sure %100 if issues are related with library.
Thank you.
