### ISSUE TITLE
how can I create a task ?

### ISSUE THREAD

**Issue by mdemori** [jamesiarmes/php-ews#430]
Hi, 
I check the example folder but i can't find any example related to a simple task creation.
I need to create a task with a description, title and reminder date 

thank you very much

**Comment by mikaelcom** [comment]
Sorry to disturb but if you're using Office365, maybe you can try out the [CreateItem](https://github.com/WsdlToPhp/PackageEws365/blob/develop/samples/task/CreateItem.php) sample script from the [Task samples](https://github.com/WsdlToPhp/PackageEws365/tree/develop/samples/task).
Starting guide is [explained here](https://github.com/WsdlToPhp/PackageEws365#how-to-use-the-generated-package).
In any case, feel free to get back to me for any issue or needed help.

**Comment by mdemori** [comment]
@mikaelcom Sorry but I forgot to mention that i need to create tasks on exchange 2013, is this possible without using another library? I already wrote some code for other function using phpEws and if is possible I want use only one library for Exchange

**Comment by jamesiarmes** [comment]
The examples are not meant to be all inclusive, they are a meant to provide a simple starting point. Have you tried creating a task? Between the examples, code documentation and the resources linked in the README, there should be plenty of information to point you in the right direction

I'm closing this as it doesn't conform to the issue template. If you are still having trouble, please open a new issue and complete the template in full, including what you've tried so far.

**Comment by ManasaNagireddy** [comment]
// Build the request,
$request = new CreateItemType();
$request->Items = new NonEmptyArrayOfAllItemsType();
$abc = array();
$abc['Subject'] = $caldata['subject'];
$abc['StartDate'] = $start->format('c');
$abc['DueDate'] = $end->format('c');
$abc['Body'] = $caldata['description'];
$request->Items->Task[] =$abc;
$response = $client->CreateItem($request);

The above thing i have implemented in application.Working Perfectly. Hope this will help you.

**Comment by emerika** [comment]
This worked for me:

        $client = new Client(self::EXCHANGE_SERVER, $email, $password, self::EXCHANGE_VERSION);

        $request = new CreateItemType();
        $request->Items = new NonEmptyArrayOfAllItemsType();
        $task            = new TaskType();
        $task->Subject   = $task_data['subject'];
        $task->StartDate = $task_data['start_at']->format('c');
        $task->DueDate   = $task_data['due_at']->format('c');

        $task->Body              = new BodyType();
        $task->Body->_           = $task_data['description'];
        $task->Body->BodyType    = new BodyTypeType();
        $task->Body->BodyType->_ = BodyTypeType::TEXT;
        $task->Importance        = ImportanceChoicesType::NORMAL;
        $task->Status            = TaskStatusType::IN_PROGRESS;
        $task->PercentComplete   = 50.;

        $request->Items->Task[]  = $task;

        $response = $client->CreateItem($request);
