### ISSUE TITLE
Calendar filter reccuring events

### ISSUE THREAD

**Issue by Cracs22** [jamesiarmes/php-ews#431]
Version (e.g. 1.0, dev-master):
PHP version: PHP 5.5

Description of problem:

I'm having some problems with the restrictions. I'm using an old version of the lib but this is not the problem.
I'm trying to get all recurring events in my calendar.
So I found the field wich define if an event is recurring or not (CalendarItemType) : 
- RecurringMaster : Reccurent event
- Single : Simple event
- Occurent : Occurence of serie
- Exception : Exception of serie

In my restriction, how can I filter of "RecurringMaster " events ? I tried this but it's not working :

    $FindItem = new EWSType_FindItemType();
    $FindItem->Traversal = EWSType_ItemQueryTraversalType::SHALLOW;
    $FindItem->ItemShape = new EWSType_ItemResponseShapeType();
    $FindItem->ItemShape->BaseShape = EWSType_DefaultShapeNamesType::ALL_PROPERTIES;
    
    $FindItem->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
    $folder_id = new EWSType_DistinguishedFolderIdType();
    $folder_id->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;
    $FindItem->ParentFolderIds->DistinguishedFolderId[] = $folder_id;
    
    $restriction = new EWSType_RestrictionType();
    $condition = new EWSType_IsEqualToType();
    $condition->FieldURIOrConstant = new EWSType_FieldURIOrConstantType();
    $condition->FieldURIOrConstant->Constant = new EWSType_ConstantValueType();
    $condition->FieldURIOrConstant->Constant->Value = EWSType_CalendarItemTypeType::RECURRING_MASTER;
    $condition->FieldURI = new EWSType_PathToUnindexedFieldType();
    $condition->FieldURI->FieldURI = EWSType_UnindexedFieldURIType::CALENDAR_ITEM_TYPE;
    $restriction->IsEqualTo = $condition;
    $FindItem->Restriction = $restriction;
    
    $result = $client->FindItem($FindItem); 

The error returned is : The property can not be used with this type of restriction.
I think for this field I don't need to use `FieldURI`

Can you help me to find the recurring events ?
Is there a documentation for restriction ? For exemple, if I want to get all events where IsMeeting is equals to TRUE or isCancelled is equals to TRUE... ?

Thanks

**Comment by Cracs22** [comment]
Somebody know how to correct my problem ?

**Comment by jamesiarmes** [comment]
Exchange does not support the `Restriction` element when searching for calendar items. The only way to achieve what you're looking for is to find all calendar items in a time period then use a `foreach` to find the ones you want.

**Comment by Cracs22** [comment]
I can use Restriction with calendar items. 
For exemple I can get all events between some date with a specific subject and with special category.
But here my problem is just to get all reccuring events. 

I tried with IsEqualTo like above but I think it's more difficult than this.
