### ISSUE TITLE
Using another exchange server

### ISSUE THREAD

**Issue by Cracs22** [jamesiarmes/php-ews#438]
Version : Old version

Description of problem:

Hello,

I'm using your library but the old version (I haven't been able to integrate the new version with drupal for the moment). Everything works when I used the office365 server (outlook.office365.com), but now I wanna use the custom server of my firm.

So I found a lot of links like this : 
- https://exchange.mydomain.fr/ews/Services.wsdl
- https://IpExchangeServ/ews/exchange.asmx
- https://IpExchangeServ/owa/

I tried to used all of this servers with and without "https://" but none worked, I got some strange errors : 
- EWS_Exception : Curl error: Maximum (20) redirects followed dans NTLMSoapClient->__doRequest()
- SoapFault : The request failed when validating the schema : The required attribute of 'Traversal' is missing. in SoapClient->__call()

So my questions are : 
- How can I find the right name of the exchange server ?
- Can I use an username which is just a "pseudo" and not an email ?

Thanks

**Comment by jamesiarmes** [comment]
If the autodiscovery class does not work for determining your server's actual endpoint, you can try Microsoft's Remote Connectivity Analyzer. I'm not sure what you mean by a "pseudo" account, but all accounts should be associated with a user. The format of the username is dependent on the Exchange server, but it most commonly an email address.

I'm closing this, as the old version is not supported.
