### ISSUE TITLE
Is this automatically encapsulated into a XML request？

### ISSUE THREAD

**Issue by synlol** [jamesiarmes/php-ews#439]
public function test()
     {
         $start = new DateTime('next wednesday 00:00:00');

         $end = new DateTime('next thursday 00:00:00');

         $meeting_duration = 60;

         $timezone = 'UTC';//时区

         // 链接信息
         $host = '';

         $username = '';

         $password = '‘’;

         $version = ‘’;

         $client = new Client($host, $username, $password, $version);
         //设置请求时区
         $client->setTimezone($timezone);

         // 使用用户定义的参数，以获得可用的信息。
         $request = new GetUserAvailabilityRequestType();

         //表示要查询可用性信息的邮箱列表
         $request->MailboxDataArray                                       = new ArrayOfMailboxData();

         //定义获取会议建议信息的选项。
         $request->SuggestionsViewOptions                                 = new SuggestionsViewOptionsType();

         //指定会议每日正常工作时间以外的时间的建议结果的数量。
         $request->SuggestionsViewOptions->MaximumNonWorkHourResultsByDay = 0;

         //指定建议的会议的时间长度。
         $request->SuggestionsViewOptions->MeetingDurationInMinutes       = $meeting_duration;

         ///标识查询有关建议的会议时间的详细信息的时间跨度。
         $request->SuggestionsViewOptions->MinimumSuggestionQuality       = SuggestionQuality::EXCELLENT;

         //设置时间段
         $duration = new Duration();

         $duration->StartTime = $start->format('Y-m-d\TH:i:s.0000\Z');

         $duration->EndTime   = $end->format('Y-m-d\TH:i:s.0000\Z');

         $request->SuggestionsViewOptions->DetailedSuggestionsWindow = $duration;

          // 添加用户的建议。
          $mailbox = new MailboxData();

          $mailbox->Email = new EmailAddressType();

          $mailbox->Email->Address = $username;

          $mailbox->Email->RoutingType = 'SMTP';

          $mailbox->AttendeeType = 'Required';

          $mailbox->ExcludeConflicts = false;

          //表示一个单独的邮箱用户和数据类型的选项
          $request->MailboxDataArray->MailboxData[] = $mailbox;

         //提供详细信息的可用性的一组用户,*房间,在指定的时间和资源
          $response = $client->GetUserAvailability($request);

         //查看会议室列表
         // $meeting = $client->GetRoomLists($request);

         // 确保请求成功。
         $response_message = $response->SuggestionsResponse->ResponseMessage;

         if ($response_message->ResponseClass != ResponseClassType::SUCCESS)
         {

             $code = $response_message->ResponseCode;

             $message = $response_message->MessageText;

             fwrite(
                 STDERR,
                 "未能获得用户可用性 \"$code: $message\"\n"
             );

             exit;
         }

         // 获取建议会议时间
         $suggestion_days = $response->SuggestionsResponse->SuggestionDayResultArray;

         foreach ($suggestion_days->SuggestionDayResult as $day)
         {
             $date = new DateTime($day->Date);

             $output = '可用会议时间' . $date->format('Y-m-d:') . "\n";

             fwrite(fopen('php://stdout', 'w'), $output);

             // 迭代建议的时间并打印每一个。
             foreach ($day->SuggestionArray->Suggestion as $suggestion)
             {
                 $time = new DateTime($suggestion->MeetingTime);

                 fwrite(fopen('php://stdout', 'w'), '- ' . $time->format('H:i') . "\n");

                 echo $time->format('H:i')."<br/>";
             }

             echo $output;
         }

     }

**Comment by synlol** [comment]
hello jame!
this is Script generated XML
<?xml version="1.0" encoding="utf-8"?>

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:ns2="http://schemas.microsoft.com/exchange/services/2006/types">
  <SOAP-ENV:Header>
    <ns2:RequestServerVersion Version="Exchange2010_SP1"/>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <ns1:GetRoomLists/>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>



but Official is
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
  <soap:Header>
    <t:RequestServerVersion Version ="Exchange2010_SP1"/>
  </soap:Header>
  <soap:Body>
    <m:GetRoomLists />
  </soap:Body>
</soap:Envelope>

URL
https://msdn.microsoft.com/zh-cn/library/office/dd899416(v=exchg.150).aspx#另请参阅

   <m:GetRoomLists /> and <ns1:GetRoomLists/>

**Comment by jamesiarmes** [comment]
I don't understand what your issue is. Please re-open and fill out the issue template in full.
