### ISSUE TITLE
FindItemResponseMessage is now an array instead of a simple object record

### ISSUE THREAD

**Issue by patrick-mota** [jamesiarmes/php-ews#441]
Version latest
PHP version: 5.6/7
Microsoft Exchange version:
14.3.210.2 (2010)

Description of problem:
I'm currently migrating from a very old version of php-ews to the latest one.
But it seems now FindItemReponseMessage contains an array instead of the object directly.
So I have to add [0] because I always get only 1 record (and with the older version of php-ews we always had only 1 result)

I just wanted to know what changed and why now we get an array with 1 record instead of the record directly.

Example request:

```php
$response->ResponseMessages->FindItemResponseMessage->ResponseCode
```
And now I have to do
```php
$response->ResponseMessages->FindItemResponseMessage[0]->ResponseCode
```
Example response:

If I do the first one I get an error 
```
looks like we got no XML document
```
The second one using var_dump($response->ResponseMessages->FindItemResponseMessage->ResponseCode)
```
array (size=1)
  0 => 
    object(jamesiarmes\PhpEws\Response\FindItemResponseMessageType)[192]
      public 'RootFolder' => 
        object(jamesiarmes\PhpEws\Type\FindItemParentType)[187]
          public 'AbsoluteDenominator' => null
          public 'Groups' => null
          public 'IncludesLastItemInRange' => boolean true
          public 'IndexedPagingOffset' => null
          public 'Items' => 
            object(jamesiarmes\PhpEws\ArrayType\ArrayOfRealItemsType)[188]
              ...
          public 'NumeratorOffset' => null
          public 'TotalItemsInView' => int 0
      public 'DescriptiveLinkKey' => null
      public 'MessageText' => null
      public 'MessageXml' => null
      public 'ResponseClass' => string 'Success' (length=7)
      public 'ResponseCode' => string 'NoError' (length=7)
```

Additional details:
I got the same thing with 
```
response->ResponseMessages->CreateItemResponseMessage
```
Have to add [0] since the older version didn't return an array and now we got one...

I just want to figure out why this change was made in the library.

**Comment by jamesiarmes** [comment]
This change was intentional. Any element that can be an array is now always array. This allows your code to be more consistent and prevents the need to check if a value is an array before operating on it. You can see this noted in the changelog entry for 1.0.0-beta.1.

**Comment by patrick-mota** [comment]
Ah ok, thanks for your answer ! 
I thought they didn't return an array.
Example: CreateItemREsponseMessage 
https://msdn.microsoft.com/en-us/library/office/aa581037(v=exchg.150).aspx

> The CreateItemResponseMessage element contains the status and result of a single CreateItem operation request.
