### ISSUE TITLE
500 PHP Error

### ISSUE THREAD

**Issue by beatkind** [jamesiarmes/php-ews#444]
Version (e.g. 1.0, dev-master): 1.0 dev-master
PHP version: 5.6.30
Microsoft Exchange version: 14.01.0438.000

Getting this error by using the free-busy.php from the examples:

`PHP Fatal error:  Uncaught SoapFault exception: [Client] Call to undefined function jamesiarmes\\PhpNtlm\\curl_init() in /var/www/nitex/parken/vendor/jamesiarmes/php-ntlm/src/SoapClient.php:80\nStack trace:\n#0 /var/www/nitex/parken/vendor/jamesiarmes/php-ntlm/src/SoapClient.php(80): jamesiarmes\\PhpNtlm\\SoapClient->__doRequest()\n#1 [internal function]: jamesiarmes\\PhpNtlm\\SoapClient->__doRequest('<?xml version="...', 'https://s123002...', 'http://schemas....', 1, 0)\n#2 /var/www/nitex/parken/vendor/php-ews/php-ews/src/Client.php(1631): SoapClient->__call('GetUserAvailabi...', Array)\n#3 /var/www/nitex/parken/vendor/php-ews/php-ews/src/Client.php(1631): jamesiarmes\\PhpNtlm\\SoapClient->GetUserAvailability(Object(jamesiarmes\\PhpEws\\Request\\GetUserAvailabilityRequestType))\n#4 /var/www/nitex/parken/vendor/php-ews/php-ews/src/Client.php(1126): jamesiarmes\\PhpEws\\Client->makeRequest('GetUserAvailabi...', Object(jamesiarmes\\PhpEws\\Request\\GetUserAvailabilityRequestType))\n#5 /var/www/nitex/parken/parken.php(61): jamesiarmes\\PhpEws\\Client->Ge in /var/www/nitex/parken/vendor/jamesiarmes/php-ntlm/src/SoapClient.php on line 80`

**Comment by jamesiarmes** [comment]
It sounds like you're missing PHP's curl extension.
