### ISSUE TITLE
How to Update Contacts Physical Address Country 

### ISSUE THREAD

**Issue by ManasaNagireddy** [jamesiarmes/php-ews#448]
Version (e.g. 1.0, dev-master):
PHP version:
Microsoft Exchange version:
2017
Description of problem:
How to update Address fields in outlook.
I have done code like this
Example request:

```php
if($entity->get('mailingcountry') != ''){
		$field = new SetItemFieldType();
        $field->IndexedFieldURI = new PathToIndexedFieldType();
        $field->IndexedFieldURI->FieldURI = DictionaryURIType::CONTACTS_PHYSICAL_ADDRESS_COUNTRY;
        $field->IndexedFieldURI->FieldIndex = PhysicalAddressKeyType::HOME;
		$field->Contact = new ContactItemType();
        $entry = new PhysicalAddressDictionaryEntryType();
		$entry->Key = PhysicalAddressKeyType::HOME;
        $entry->CountryOrRegion = $entity->get('mailingcountry');
        $field->Contact->PhysicalAddresses->Entry = $entry;
        $change->Updates->SetItemField[] = $field;
	}else {
        $field = new DeleteItemFieldType();
        $field->IndexedFieldURI = new PathToUnindexedFieldType();
        $field->IndexedFieldURI->FieldURI = DictionaryURIType::CONTACTS_PHYSICAL_ADDRESS_COUNTRY;
        $field->IndexedFieldURI->FieldIndex = PhysicalAddressKeyType::HOME;
        $change->Updates->DeleteItemField[] = $field;
    }
```

Example response:

Fatal error: Uncaught SoapFault exception: [a:ErrorInvalidRequest] The request is invalid. in /var/www/modules/Outlook/src/Client.php:1631
Stack trace:

Additional details:

**Comment by ManasaNagireddy** [comment]
if($entity->get('mailingcountry') != ''){
		$field = new SetItemFieldType();
        $field->IndexedFieldURI = new PathToIndexedFieldType();
        $field->IndexedFieldURI->FieldURI = DictionaryURIType::CONTACTS_PHYSICAL_ADDRESS_CITY;
		$field->IndexedFieldURI->Key = PhysicalAddressKeyType::HOME;
        $field->IndexedFieldURI->FieldIndex = PhysicalAddressKeyType::HOME;
		$field->Contact = new ContactItemType();
        $entry = new PhysicalAddressDictionaryEntryType();
		$entry->Key = PhysicalAddressKeyType::HOME;
        $entry->City = $entity->get('mailingcountry');
        $field->Contact->PhysicalAddresses->Entry = $entry;
        $change->Updates->SetItemField[] = $field;
	}else {
        $field = new DeleteItemFieldType();
        $field->IndexedFieldURI = new PathToUnindexedFieldType();
        $field->IndexedFieldURI->FieldURI = DictionaryURIType::CONTACTS_PHYSICAL_ADDRESS_CITY;
		$field->IndexedFieldURI->Key = PhysicalAddressKeyType::HOME;
        $field->IndexedFieldURI->FieldIndex = PhysicalAddressKeyType::HOME;
        $change->Updates->DeleteItemField[] = $field;
    }
Use above code. Working for me. Thanks.

**Comment by fabpico** [comment]
> Mh? You ask for support to update the country value, (i need to set this too) and you post some example to update the CITY and closed the issue? Seems strange... please post the correct example for COUNTRY (currently invalid request?)

I had the same issue with the country.
I noticed that the string behind `DictionaryURIType::CONTACTS_PHYSICAL_ADDRESS_COUNTRY` is `contacts:PhysicalAddress:Country`.
But the property to use for the country in `PhysicalAddressDictionaryEntryType` is `CountryOrRegion`.
So i tried to use `contacts:PhysicalAddress:CountryOrRegion` for the `FieldURI` and it worked!
