### ISSUE TITLE
fwrite to STDERR / STDOUT - fwrite() expects parameter 1 to be resource, string given

### ISSUE THREAD

**Issue by doit-itservice** [jamesiarmes/php-ews#450]
Version: Release 1.0.0-rc.2
PHP version: 5.6.23
Microsoft Exchange version: 2013

Description of problem:
e.g. https://github.com/jamesiarmes/php-ews/blob/master/examples/contact/create.php

`fwrite(STDERR, "Contact failed to create with \"$code: $message\"\n");`
and
`fwrite(STDOUT, "Created contact $id\n");`

return: PHP Warning: fwrite() expects parameter 1 to be resource, string given in  ...

Additional details:
CreateItem contact was successful.
Running script in Firefox-browser with IIS10 webserver (win2016).

I replace fwrite with `echo "Created contact $id\n";` but was is the right way to use fwrite? 
Have I to define something to bringing up fwrite()?

Thank you

**Comment by sydetion** [comment]
use example with php-cli

workaround with echo is fine for browser use if it does the job for you

**Comment by jamesiarmes** [comment]
From the readme: "These examples are meant to be run from the command line."
