### ISSUE TITLE
Issue cancelling an appointment

### ISSUE THREAD

**Issue by keithslater** [jamesiarmes/php-ews#458]
Version (e.g. 1.0, dev-master): 1.0.0-rc.2
PHP version: 7.0
Microsoft Exchange version: Office 365

Description of problem: 
When doing a cancellation I am getting the following error - 

At least one recipient isn't valid. A message can't be sent because it contains no recipients

Example request:

```php
                $request = new CreateItemType();
		$request->MessageDisposition = MessageDispositionType::SEND_AND_SAVE_COPY;
		$request->Items = new NonEmptyArrayOfAllItemsType();

		$cancellation = new CancelCalendarItemType();
		$cancellation->ReferenceItemId = new ItemIdType();
		$cancellation->ReferenceItemId->Id = $outlook_response['outlook_response_id'];
		$cancellation->ReferenceItemId->ChangeKey = $new_changekey;
		$request->Items->CancelCalendarItem[] = $cancellation;

		$response = $ews->CreateItem($request);
```

This used to work and then it stopped. I'm wondering if something changed with Office 365?

**Comment by jamesiarmes** [comment]
What do you mean by "this used to work and then it stopped?" How does it not work? You haven't included an example response, and I just tried this against Office 365 and it worked without issue.

I'm closing this as there's not enough information and I haven't been able to reproduce. If you have more information, feel free to re-open.

**Comment by keithslater** [comment]
The response says - "At least one recipient isn't valid. A message can't be sent because it contains no recipients."

Is that not enough from the response or did you need more?
