### ISSUE TITLE
Completing Task

### ISSUE THREAD

**Issue by BirdyB** [jamesiarmes/php-ews#459]
Hi,
i'm trying to complete a task via php-ews. I tried to build some code by studying the examples and it looks like this:
function completeTask($id, $changekey) {
    require 'config.php';
    $event_updates = array(
        array(
            'id' => $id,
	    'changekey' => $changekey,
            'isCompleted' => "true",
        )
    );
    $request = new UpdateItemType();
    $request->ConflictResolution = ConflictResolutionType::ALWAYS_OVERWRITE;

echo 'event_updates<br>';
print_r($event_updates);
echo '<br><br>';

    // Iterate over the updated to be applied, adding each to the request.
    foreach ($event_updates as $update) {
        // Build out item change request.
        $change = new ItemChangeType();
        $change->ItemId = new ItemIdType();
        $change->ItemId->Id = $update['id'];
	$change->ItemId->ChangeKey = $update['changekey'];
        $change->Updates = new NonEmptyArrayOfItemChangeDescriptionsType();
       
echo 'change<br>';
print_r($change);
echo '<br><br>';

	 $field = new SetItemFieldType();
        $field->FieldURI = new PathToUnindexedFieldType();
        $field->FieldURI->FieldURI = UnindexedFieldURIType::TASK_IS_COMPLETE;
        $field->Task = new TaskType();
        $field->Task->IsComplete = 'true';
        $change->Updates->SetItemField[] = $field;
        $request->ItemChanges[] = $change;
    }

echo 'request<br>';
print_r($request);
echo '<br><br>';

    $response = $client->UpdateItem($request);

echo 'response<br>';
print_r($response);
echo '<br><br>';

// Iterate over the results, printing any error messages or ids of events that
// were updated.
    $response_messages = $response->ResponseMessages->UpdateItemResponseMessage;
    foreach ($response_messages as $response_message) {
        // Make sure the request succeeded.
        if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
            $code = $response_message->ResponseCode;
            $message = $response_message->MessageText;
            echo("Failed to update event with \"$code: $message\"<br>");
            continue;
        }

        // Iterate over the updated events, printing the id of each.
        foreach ($response_message->Items->CalendarItem as $item) {
            $id = $item->ItemId->Id;
            echo("Updated event $id\n");
        }
    }
}

Unfortunately i get Failed to update event with "ErrorInvalidIdMalformed: Id is malformed." as response. Any ideas what i did wrong?

Thanks in advance...

**Comment by BirdyB** [comment]
I apologize, i had an issue with HTTP and POST of the ID...

But now im getting the following error: Failed to update event with "ErrorInvalidPropertySet: Set action is invalid for property."

How can i set a task as completed?

**Comment by BirdyB** [comment]
Okay, i just got it... I have to set the CompletedDate...

**Comment by VGinfotec** [comment]
I already  set the CompletedDate but still i am facing 



                            [ResponseClass] => Error
                            [ResponseCode] => ErrorInvalidPropertySet
