### ISSUE TITLE
"use" fails when using hyphens in its path

### ISSUE THREAD

**Issue by rodnikosh** [jamesiarmes/php-ews#461]
**Version (e.g. 1.0, dev-master):** 
Don't know where can i see the version, but got this from the "lock" file:
"packages": [
        {
            "name": "jamesiarmes/php-ntlm",
            "version": "1.0.0-beta.1",

           "extra": {
                "branch-alias": {
                    "dev-master": "1.0.x-dev"
                }

**PHP version:** 5.4.16
**Microsoft Exchange version:** 2010

**Description of problem:**

used the composer to get the php-ews:

{
	"minimum-stability": "dev",
	"prefer-stable": true,
	"require": 
	{
		"php-ews/php-ews": "dev-master"
	}
}

but the php doesn't accept hyphens (-) in its "use" command path, so how can i include anything....

Example request:

require_once 'composer/vendor/autoload.php';
use \php-ews\php-ews\src\Client;

$host = 'my.server.co.il';
$username = 'user@server.co.il';
$password = 'myPass';
$version = Client::VERSION_2010;
		
$client = new Client($host, $username, $password, $version);

Example response:

"PHP Parse error:  syntax error, unexpected '-', expecting ',' or ';' in /var/www/html"

also, the paths of the "use" phrases in all the other files, does not match the project files at all. for example, in the "create.php" there are "use" phrases:

se \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Request\CreateItemType;

use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfAllItemsType;
use \jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfAttendeesType;

use \jamesiarmes\PhpEws\Enumeration\BodyTypeType;
use \jamesiarmes\PhpEws\Enumeration\CalendarItemCreateOrDeleteOperationType;
use \jamesiarmes\PhpEws\Enumeration\ResponseClassType;
use \jamesiarmes\PhpEws\Enumeration\RoutingType;

The above paths does not exist in the project at all.... there are only /jameslarmes/php-ntlm folder.
what is going on????!!!

Additional details:
![php-ews_path](https://user-images.githubusercontent.com/13796542/30897477-209d0a6a-a35f-11e7-8254-c62510366960.JPG)

**Comment by rodnikosh** [comment]
anyone? please?

**Comment by Dragnucs** [comment]
Try using the `use` like this:

```php
require_once 'composer/vendor/autoload.php';
use \jamesiarmes\PhpEws\Client;
```

Instead of:

```php
require_once 'composer/vendor/autoload.php';
use \php-ews\php-ews\src\Client;
```

**Comment by jamesiarmes** [comment]
The `use` statement does not correspond to file paths, but to namespaces. You need to include the the composer autoloader and use the proper namespace as indicated in the readme, examples and @Dragnucs comment above.
