### ISSUE TITLE
Message: Curl error: Failed to connect to mail.xxx.lk port 443: Timed out

### ISSUE THREAD

**Issue by nuwaninfo** [jamesiarmes/php-ews#469]
Version (e.g. 1.0, dev-master):
PHP version: 5.6
Microsoft Exchange version: 2013 SP1

Description of problem:

I am using this for send email via Exchange Server.  I am using code in php-ews/php-ews/examples/messag/ecreate.php. But I an not give any port like 443. But it gave the error mentioned in heading.

I provided below values in php-ews/php-ews/examples/messag/ecreate.php.

$host = 'mail.xxxx.lk';
$username = 'xxxxx';
$password = 'xxxxx';
$version = Client::VERSION_2013;

Example request:

```php

```

Example response:

```

```

Additional details:

**Comment by jamesiarmes** [comment]
As user credentials are passed as plain-text, this library only supports the HTTPS protocol, which uses port 443. You must have this enabled on your Exchange server.
