### ISSUE TITLE
Error installing   dev-master requires ext-soap 

### ISSUE THREAD

**Issue by mordechaihorowitz** [jamesiarmes/php-ews#478]
Version dev-master
PHP version:5.6

Description of problem:
  Problem 1
    - Installation request for jamesiarmes/php-ntlm 1.0.x-dev -> satisfiable by jamesiarmes/php-ntlm[1.0.x-dev].
    - jamesiarmes/php-ntlm 1.0.x-dev requires ext-soap * -> the requested PHP extension soap is missing from your system.
  Problem 2
    - Installation request for jamesiarmes/php-ntlm dev-master -> satisfiable by jamesiarmes/php-ntlm[dev-master].
    - jamesiarmes/php-ntlm dev-master requires ext-soap * -> the requested PHP extension soap is missing from your system.
  Problem 3
    - Installation request for php-ews/php-ews 1.0.x-dev -> satisfiable by php-ews/php-ews[1.0.x-dev].
    - php-ews/php-ews 1.0.x-dev requires ext-soap * -> the requested PHP extension soap is missing from your system.
  Problem 4
    - Installation request for php-ews/php-ews dev-master -> satisfiable by php-ews/php-ews[dev-master].
    - php-ews/php-ews dev-master requires ext-soap * -> the requested PHP extension soap is missing from your system.

I am trying to run an install command and am getting these message.  I have soap installed
If I try to reinstall soap I get told its up to date on the system 

I am using ubuntu as my OS

**Comment by jamesiarmes** [comment]
The errors indicate you are missing the PHP SOAP extension. If it's already installed, make sure it has been enabled.
