### ISSUE TITLE
Update Calendar Item Required Attendees

### ISSUE THREAD

**Issue by robp2175** [jamesiarmes/php-ews#487]
Version (e.g. 1.0, dev-master):
PHP version:  5.6.32
Microsoft Exchange version: 2013

Description of problem:
I am trying to update the required attendees for a calendar item, but I am not sure of the syntax. To create the calendar item I use

Example request:

```
$guests = array(
					array(			
						'name' => $row["location_short"],
						'email' => strtolower($row["location_short"]) . '@domain.edu',
					),				
				);

```
then
```
foreach ($guests as $guest) {
				$attendee = new AttendeeType();
				$attendee->Mailbox = new EmailAddressType();
				$attendee->Mailbox->EmailAddress = $guest['email'];
				$attendee->Mailbox->Name = $guest['name'];
				$attendee->Mailbox->RoutingType = RoutingType::SMTP;
				$event->RequiredAttendees->Attendee[] = $attendee;
			}
```

However, I am not sure how to update this if the attendees change. This is how I update the location:

```
		$field = new SetItemFieldType();
		$field->FieldURI = new PathToUnindexedFieldType();
		$field->FieldURI->FieldURI = UnindexedFieldURIType::CALENDAR_LOCATION;
		$field->CalendarItem = new CalendarItemType();
		$field->CalendarItem->Location = $update['location'];
		$change->Updates->SetItemField[] = $field;  
```

just not sure of attendees. Thank you for any assistance.

**Comment by robp2175** [comment]
My thinking is that it will be something like this
````
foreach ($guests as $guest) {
                $field = new SetItemFieldType();
		$field->FieldURI = new PathToUnindexedFieldType();
		$field->FieldURI->FieldURI = UnindexedFieldURIType::CALENDAR_REQUIRED_ATTENDEES;
		$field->CalendarItem = new CalendarItemType();
		$field->CalendarItem->RequiredAttendees = $guest['email'];
		$change->Updates->SetItemField[] = $field;  
}

````
but I would appreciate any guidance

**Comment by robp2175** [comment]
Found my answer here https://github.com/jamesiarmes/php-ews/issues/62. #62

**Comment by KuSai18** [comment]
if (count($guests) > 0){
            $field = new SetItemFieldType();
            $field->FieldURI = new PathToUnindexedFieldType();
            $field->FieldURI->FieldURI = UnindexedFieldURIType::CALENDAR_REQUIRED_ATTENDEES;
            $field->CalendarItem = new CalendarItemType();
            $field->CalendarItem->RequiredAttendees = new NonEmptyArrayOfAttendeesType();

            $guestNo = 0;
            foreach ($guests as $guest) {
                $field->CalendarItem->RequiredAttendees->Attendee[$guestNo] = new SingleRecipientType();
                $field->CalendarItem->RequiredAttendees->Attendee[$guestNo]->Mailbox = new EmailAddressType();
                $field->CalendarItem->RequiredAttendees->Attendee[$guestNo]->Mailbox->Name = $guest["name"];
                $field->CalendarItem->RequiredAttendees->Attendee[$guestNo]->Mailbox->EmailAddress = $guest["email"];
                $field->CalendarItem->RequiredAttendees->Attendee[$guestNo]->Mailbox->RoutingType = RoutingType::SMTP;
                $guestNo+=1;
            }
            $change->Updates->SetItemField[] = $field;
        }

**Comment by KuSai18** [comment]
answer as #62.  receive error "Creating default object from empty value", updated at above.
