### ISSUE TITLE
Working with mailbox aliases

### ISSUE THREAD

**Issue by WWRFresource** [jamesiarmes/php-ews#505]
Version (e.g. 1.0, dev-master): 1.0
PHP version: 7+
Microsoft Exchange version: 2016

Description of problem:
Not exactly a problem but I'd like to be able to manipulate aliases on my server (create, destroy, etc.). I don't see anything listed in the Types relating to aliases. Any help is appreciated.

Example request:

```php

```

Example response:

```

```

Additional details:

**Comment by jamesiarmes** [comment]
Unfortunately, Exchange Web Services does not support managing mailbox aliases.
