### ISSUE TITLE
Missing "MaxItemsReturned" in FindItems

### ISSUE THREAD

**Issue by igittigitt** [jamesiarmes/php-ews#535]
As for your example in fetching calendar items for a specific mailbox, i'd like to have only a given number of items returned and sorted ("like give me the next two upcoming events").

The Microsoft EWS-Documentation about this names the attribute "MaxItemsReturned" to do the clipping. https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.calendarview.maxitemsreturned?view=exchange-ews-api

But it does not seems to be handled, because using this:
```php
$request->CalendarView->MaxItemsReturned = 2;
```
will result in as many events as they are in a given timerange.

**Comment by jamesiarmes** [comment]
Please complete the issue template in full so that I can properly attempt to reproduce the issue.
