### ISSUE TITLE
How to add shared calendar group  by EWS API? Thanks

### ISSUE THREAD

**Issue by beyond8848** [jamesiarmes/php-ews#538]
Version (e.g. 1.0, dev-master):
PHP version:
Microsoft Exchange version:

Description of problem:

Example request:

```php
// Formatted example request.
```

Example response:

```
// Formatted example response.
```

Additional details:

**Comment by beyond8848** [comment]
I tried to created one shared group based on MS doc https://msdn.microsoft.com/en-us/library/ee217241(v=exchg.80).aspx

**Comment by jamesiarmes** [comment]
Please complete the issue template in full.
