### ISSUE TITLE
Resources member of finded calendar events.

### ISSUE THREAD

**Issue by varolo** [jamesiarmes/php-ews#539]
Hi everyone, first of all thanks for this library.
Mi question is related to examples/event/find.php :
is there a way to populate the Resources member of CalendarItemType response items?

The Resources member is empty for all items if I use **$response = $client->FindItem($request);** in examples/event/find.php when I perform an iteration through the items:

`
...
            [OriginalStart] => 
            [Recurrence] => 
            [RecurrenceId] => 
            [RequiredAttendees] => 
            [Resources] =>
            [Start] => 2018-12-12T12:00:00-05:00
            [StartTimeZone] => 
            [TimeZone] => (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
...
`

..but is correctly populated when I use **$response = $client->GetItem($request);** in /examples/event/describe.php passing the correct event ids:

`
...

    [Resources] => jamesiarmes\PhpEws\ArrayType\NonEmptyArrayOfAttendeesType Object
        (
            [Attendee] => Array
                (
                    [0] => jamesiarmes\PhpEws\Type\AttendeeType Object
                        (
                            [LastResponseTime] => 2018-12-12T10:38:15-05:00
                            [Mailbox] => jamesiarmes\PhpEws\Type\EmailAddressType Object
                                (
                                    [EmailAddress] => IT-AN_CR_Room@company.com
                                    [ItemId] => 
                                    [MailboxType] => Mailbox
                                    [Name] => Conf. Room(12) 
                                    [RoutingType] => SMTP
                                )

                            [ResponseType] => Accept
                        )

                )

        )

    [Start] => 2018-12-12T12:00:00-05:00
    [StartTimeZone] => 
    [TimeZone] => (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
...
`

Thanks!

**Comment by jamesiarmes** [comment]
Some properties are not returned in find operations and can only be retrieved via a `GetItem` operation. Since you didn't include your example request (in the future, please complete the issue template in full), I can only assume that you're using the `\jamesiarmes\PhpEws\Enumeration\DefaultShapeNamesType::ALL_PROPERTIES` shape as in the example, so if you're not see the property in the response it is likely not available.
