### ISSUE TITLE
Adding phan to composer changed the min required php version to 7.0

### ISSUE THREAD

**Issue by krstan4o** [jamesiarmes/php-ews#541]
Version (e.g. 1.0, dev-master):
PHP version:
Microsoft Exchange version:

Description of problem:

Example request:

```php
// Formatted example request.
```

Example response:

```
// Formatted example response.
```

Additional details:

**Comment by UnderDogg** [comment]
You have to be more specific with your actual, question. What is 'phan' and give your composer.json as example. Give the error messages, because that might help to solve your error

**Comment by jamesiarmes** [comment]
Updated minimum PHP version in eaad3c8d3c40721e2acf0732c1f398829e772c3c
