### ISSUE TITLE
How to Invite Attendees to new Calendar Event?

### ISSUE THREAD

**Issue by phpftw** [jamesiarmes/php-ews#55]
First I would like to thank everyone who has made this project. It is pretty neat to be able to add Calendar events to MS Exchange servers via PHP. 

I have a put together a script to add calendar events, and it is working great. 

I would like to invite attendees to the events, 1 or more. 
## Below is code for adding it to my calendar only.

``` php
<?php
$ews = new ExchangeWebServices($host, $username, $password, $version);

$request = new EWSType_CreateItemType();

$event_details = new EWSType_CalendarEventDetails();

$event = new EWSType_CalendarEvent();
$event->CalendarEventDetails = $event_details;

$event->Start = '2012-07-21T09:00:00+02:00';
$event->End = '2012-07-21T18:00:00+02:00';
$event->Subject = "Subject";
$event->Location = "Location";
$event->BusyType = "Busy";

$request->Items->CalendarItem[] = $event;
$request->SendMeetingInvitations = EWSType_CalendarItemCreateOrDeleteOperationType::SEND_TO_NONE;

$response = $ews->CreateItem($request);
echo '<pre>'.print_r($response, true).'</pre>';
```

**Comment by halucin0g3n** [comment]
$request->Items->CalendarItem->RequiredAttendees = new EWSType_NonEmptyArrayOfAllItemsType ();
				foreach ( $results as $key => $attendee ) {
					$sanitized_email = filter_var ( $attendee, FILTER_SANITIZE_EMAIL );
					if (filter_var ( $sanitized_email, FILTER_VALIDATE_EMAIL )) {
						$request->Items->CalendarItem->RequiredAttendees->Attendee [$key] = new EWSType_SingleRecipientType ();
						$request->Items->CalendarItem->RequiredAttendees->Attendee [$key]->Mailbox = new EWSType_EmailAddressType ();
						$request->Items->CalendarItem->RequiredAttendees->Attendee [$key]->Mailbox->EmailAddress = $sanitized_email;
						$request->Items->CalendarItem->RequiredAttendees->Attendee [$key]->Mailbox->RoutingType = 'SMTP';
					}
				}
