### ISSUE TITLE
SoapFault exception: looks like we got no XML document

### ISSUE THREAD

**Issue by paulhaggo** [jamesiarmes/php-ews#67]
Hi guys. I'm using the same code that I used to connect to a different exchange server previously. I've been trying, with no success, to connect to a different server. I am getting the following errors/exceptions:

<b>Fatal error</b>:  Uncaught SoapFault exception: [Client] looks like we got no XML document in /var/www/html/ews_exchange/ms_exchange/ExchangeWebServices.php:327
Stack trace:
#0 /var/www/html/ews_exchange/ms_exchange/ExchangeWebServices.php(327): SoapClient-&gt;__call('FindItem', Array)
#1 /var/www/html/ews_exchange/ms_exchange/ExchangeWebServices.php(327): NTLMSoapClient_Exchange-&gt;FindItem(Object(EWSType_FindItemType))
#2 /var/www/html/ews_exchange/ms_exchange/get_contacts_test.php(70): ExchangeWebServices-&gt;FindItem(Object(EWSType_FindItemType))
#3 /var/www/html/ews_exchange/ms_exchange/get_contacts_test.php(87): get_exchange_contacts('autodiscover.hp...', 'Trixy', 'helloworld', 'Exchange2010')
#4 {main}

  thrown in <b>/var/www/html/ews_exchange/ms_exchange/ExchangeWebServices.php</b> on line <b>327</b><br />

Any help would be greatly appreciated. If you need to know anything else, I'm happy to help.

Paul.

**Comment by metaseit** [comment]
The reason you got "SoapFault: looks like we got no XML document" is because you are getting a non-XML response from server.

To read the response, you could output it in NTLMSoapClient::__doRequest() method.  Most likely, you are having an authentication error.

My case is that I was using email as username (e.g. someone@domain.com) when calling "new ExchangeWebServices(...)".  After removing the domain from username, everything is fine.

**Comment by viraj97** [comment]
Hi,
I have tried so many times. I am getting same error message. But seems, I am facing login timeout issue. Do anyone have idea about this?

![no xml error](https://cloud.githubusercontent.com/assets/9080687/11300456/3323ca08-8fb5-11e5-978b-aee83d51b7b0.PNG)

**Comment by synlol** [comment]
hello,jamesiarmes.
 require_once(/var/www/html/application/third_party/jamesiarmes/src/SoapClient.php): failed to open stream: No such file or directory
help me.Thank you very much!
