### ISSUE TITLE
Change key error since Exchange 2010 upgrade

### ISSUE THREAD

**Issue by keithslater** [jamesiarmes/php-ews#81]
We recently upgraded our Exchange 2007 server to Exchange 2010. Since then, I am getting random change key errors from Exchange. The error is the following:

```
The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
```

Basically when I do the first Calendar appt create, I store the Item Id and the ChangeKey in the database. Then every time I call and update, I give it to the Id and ChangeKey and then I store the new change key that is returned. This has worked fine until we upgraded to Exchange 2010, now it works randomly. The creates always work, the updates will fail about 50% of the time. I have tried to trace the issue but I don't see anything wrong.

It almost seems like it failed because every once in a while I'm missing a character on the changekey randomly or something, but I have verified that I am getting the whole change key, before and after the update.

Does anyone have any clues or ideas on what the issue could be? Here's the code where I assign the keys (pretty basic):

```
 $change = new EWSType_ItemChangeType();
$change->ItemId = new EWSType_ItemIdType();
$change->ItemId->Id = $contact_id;
$change->ItemId->ChangeKey = $change_key;
```

**Comment by tixsys** [comment]
Got into same problem, but w/o getItem, the problem is when using Exchange  delegation. I can create appointment, and then first update will work, after that, next updates will fail randomly. Anybody have same problem?

**Comment by SlawomirBoczek** [comment]
Had the same problem. What caused it?

I was creating an e-mail, then adding an attachment - after adding attachment changeKey has been updated.

That's why after every operation on the e-mail, you need to update your changeKey with the corresponding response!
