### ISSUE TITLE
Missing the SuppressReadReceipt-Method 

### ISSUE THREAD

**Issue by GreatestPhPfreakEver** [jamesiarmes/php-ews#92]
Ok, I have realized with the help of the Exchange managed API that there is a "SuppressReadReceipt" -Method in the Emailmessage-Class to suppress the read-receipt of each single message before the isRead-property is set to true.

Is there a way to doe the same with the help of php-ews.
If not, is it possible to implement this feature?

Thanks in advance for any reply and/or help!

**Comment by jamesiarmes** [comment]
This issue is over four years old. If you are still having trouble with the latest version from master, please open a new issue.
